// @generated by Cursor AI (Claude) — verified by Kevin Mendy
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import PriorityBadge from './PriorityBadge';
import { Loader2 } from 'lucide-react';

/**
 * Formulaire pour mettre à jour la priorité d'un signalement
 * 
 * Fonctionnalités :
 * - Affiche la priorité actuelle (badge)
 * - Dropdown pour sélectionner la nouvelle priorité
 * - Bouton de soumission
 * 
 * @param {Object} props
 * @param {string} props.currentPriority - Priorité actuelle du signalement (low, normal, high, urgent)
 * @param {Function} props.onSubmit - Callback à la soumission (newPriority)
 * @param {boolean} [props.loading] - Affiche un spinner pendant l'update
 * @param {string} [props.className] - Classes CSS additionnelles
 * 
 * @example
 * <PriorityUpdateForm
 *   currentPriority="normal"
 *   onSubmit={(newPriority) => updatePriority(reportId, newPriority)}
 *   loading={updating}
 * />
 */
function PriorityUpdateForm({
  currentPriority,
  onSubmit,
  loading = false,
  className = ''
}) {
  const { t } = useTranslation('common');
  const [selectedPriority, setSelectedPriority] = useState('');

  /**
   * Configuration des priorités
   */
  const priorityOptions = [
    { 
      value: 'urgent', 
      label: t('priority.urgent', { defaultValue: 'Urgent' }),
      emoji: '🔴'
    },
    { 
      value: 'high', 
      label: t('priority.high', { defaultValue: 'Élevée' }),
      emoji: '🟠'
    },
    { 
      value: 'normal', 
      label: t('priority.normal', { defaultValue: 'Normal' }),
      emoji: '🔵'
    },
    { 
      value: 'low', 
      label: t('priority.low', { defaultValue: 'Faible' }),
      emoji: '⚪'
    }
  ];

  /**
   * Gérer la soumission du formulaire
   */
  const handleSubmit = (e) => {
    e.preventDefault();
    
    if (!selectedPriority) {
      console.warn('⚠️ Aucune priorité sélectionnée');
      return;
    }

    if (selectedPriority === currentPriority) {
      console.warn('⚠️ La priorité sélectionnée est identique à la priorité actuelle');
      return;
    }

    onSubmit(selectedPriority);
  };

  return (
    <form onSubmit={handleSubmit} className={`space-y-4 ${className}`}>
      {/* Priorité actuelle */}
      <div>
        <Label className="text-sm font-medium text-neutral-700">
          Priorité actuelle
        </Label>
        <div className="mt-2">
          <PriorityBadge priority={currentPriority} />
        </div>
      </div>

      {/* Nouvelle priorité */}
      <div>
        <Label htmlFor="new-priority" className="text-sm font-medium text-neutral-700">
          Nouvelle priorité <span className="text-error-500">*</span>
        </Label>
        <Select
          value={selectedPriority}
          onValueChange={setSelectedPriority}
          disabled={loading}
        >
          <SelectTrigger id="new-priority" className="mt-2">
            <SelectValue placeholder="Sélectionnez une priorité" />
          </SelectTrigger>
          <SelectContent>
            {priorityOptions.map((option) => (
              <SelectItem key={option.value} value={option.value}>
                {option.emoji} {option.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <p className="text-xs text-neutral-500 mt-1">
          Évaluez la priorité en fonction de la gravité et de l'urgence du problème
        </p>
      </div>

      {/* Bouton de soumission */}
      <Button
        type="submit"
        disabled={!selectedPriority || loading || selectedPriority === currentPriority}
        className="w-full"
      >
        {loading ? (
          <>
            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            Mise à jour en cours...
          </>
        ) : (
          'Mettre à jour la priorité'
        )}
      </Button>
    </form>
  );
}

export default PriorityUpdateForm;

