// @generated by Cursor AI (Claude) — verified by Kevin

import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Loader2 } from 'lucide-react';

/**
 * Composant TypeUpdateForm - Formulaire de mise à jour du type de signalement
 * 
 * Permet aux agents de modifier le type d'un signalement après avoir écouté l'audio
 * 
 * @param {Object} props
 * @param {string} props.currentType - Type actuel du signalement
 * @param {Function} props.onSubmit - Callback appelé avec le nouveau type (newType)
 * @param {boolean} [props.loading] - Si la mise à jour est en cours
 * 
 * @example
 * <TypeUpdateForm
 *   currentType="autre"
 *   onSubmit={handleUpdateType}
 *   loading={updating}
 * />
 */
function TypeUpdateForm({ currentType, onSubmit, loading = false }) {
  const { t } = useTranslation('agent');
  const [selectedType, setSelectedType] = useState(currentType || '');

  /**
   * Types de signalements disponibles
   */
  const reportTypes = [
    { value: 'voirie', label: t('report.types.voirie', { defaultValue: 'Voirie' }) },
    { value: 'eclairage', label: t('report.types.eclairage', { defaultValue: 'Éclairage public' }) },
    { value: 'eau', label: t('report.types.eau', { defaultValue: 'Eau' }) },
    { value: 'proprete', label: t('report.types.proprete', { defaultValue: 'Propreté / Déchets' }) },
    { value: 'securite', label: t('report.types.securite', { defaultValue: 'Sécurité' }) },
    { value: 'sante', label: t('report.types.sante', { defaultValue: 'Santé' }) },
    { value: 'electricite', label: t('report.types.electricite', { defaultValue: 'Électricité' }) },
    { value: 'assainissement', label: t('report.types.assainissement', { defaultValue: 'Assainissement' }) },
    { value: 'espaces_verts', label: t('report.types.espaces_verts', { defaultValue: 'Espaces verts' }) },
    { value: 'autre', label: t('report.types.autre', { defaultValue: 'Autre' }) },
  ];

  /**
   * Gérer la soumission
   */
  const handleSubmit = (e) => {
    e.preventDefault();
    if (selectedType && selectedType !== currentType) {
      onSubmit(selectedType);
    }
  };

  /**
   * Formater le type pour l'affichage
   */
  const formatType = (type) => {
    return type?.replace('_', ' ') || '';
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      {/* Type actuel */}
      <div>
        <p className="text-xs text-neutral-600 mb-1">
          {t('type.current', { defaultValue: 'Type actuel' })}
        </p>
        <p className="text-sm font-medium text-neutral-900 capitalize">
          {formatType(currentType)}
        </p>
      </div>

      {/* Sélection du nouveau type */}
      <div>
        <label className="text-xs text-neutral-600 mb-1 block">
          {t('type.new', { defaultValue: 'Nouveau type' })}
        </label>
        <Select
          value={selectedType}
          onValueChange={setSelectedType}
          disabled={loading}
        >
          <SelectTrigger className="w-full">
            <SelectValue placeholder={t('type.select', { defaultValue: 'Sélectionner un type' })} />
          </SelectTrigger>
          <SelectContent>
            {reportTypes.map((type) => (
              <SelectItem key={type.value} value={type.value}>
                {type.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {/* Bouton de confirmation */}
      <Button
        type="submit"
        disabled={loading || !selectedType || selectedType === currentType}
        className="w-full"
        size="sm"
      >
        {loading ? (
          <>
            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            {t('type.updating', { defaultValue: 'Mise à jour...' })}
          </>
        ) : (
          t('type.update', { defaultValue: 'Mettre à jour le type' })
        )}
      </Button>

      {selectedType === currentType && selectedType && (
        <p className="text-xs text-neutral-500 text-center">
          {t('type.same', { defaultValue: 'Le type sélectionné est identique au type actuel' })}
        </p>
      )}
    </form>
  );
}

export default TypeUpdateForm;

