// @generated by Cursor AI (Claude) — verified by Kevin

import { useTranslation } from 'react-i18next';
import { MapPin, Calendar, Clock, CheckCircle, XCircle, AlertCircle, FileText } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';

/**
 * Composant CitizenReportList - Liste des signalements d'un citoyen
 * 
 * @param {Object} props
 * @param {Array} props.reports - Liste des signalements
 * @param {boolean} props.loading - Si les signalements sont en cours de chargement
 * @param {Object} props.error - Erreur éventuelle
 * @param {Function} props.onReportClick - Callback quand on clique sur un signalement (reportId)
 * 
 * @example
 * <CitizenReportList 
 *   reports={reports} 
 *   loading={false} 
 *   error={null}
 *   onReportClick={(reportId) => setSelectedReportId(reportId)}
 * />
 */
function CitizenReportList({ reports = [], loading = false, error = null, onReportClick }) {
  const { t } = useTranslation('common');

  const getStatusConfig = (status) => {
    const configs = {
      pending: {
        label: t('report.status.pending', { defaultValue: 'En attente' }),
        icon: Clock,
        color: 'bg-yellow-100 text-yellow-800 border-yellow-200',
      },
      in_progress: {
        label: t('report.status.in_progress', { defaultValue: 'En cours' }),
        icon: AlertCircle,
        color: 'bg-blue-100 text-blue-800 border-blue-200',
      },
      resolved: {
        label: t('report.status.resolved', { defaultValue: 'Résolu' }),
        icon: CheckCircle,
        color: 'bg-green-100 text-green-800 border-green-200',
      },
      rejected: {
        label: t('report.status.rejected', { defaultValue: 'Rejeté' }),
        icon: XCircle,
        color: 'bg-red-100 text-red-800 border-red-200',
      },
    };
    return configs[status] || configs.pending;
  };

  const getTypeLabel = (type) => {
    const types = {
      voirie: t('report.type.voirie', { defaultValue: 'Voirie' }),
      eclairage: t('report.type.eclairage', { defaultValue: 'Éclairage' }),
      eau: t('report.type.eau', { defaultValue: 'Eau' }),
      dechets: t('report.type.dechets', { defaultValue: 'Déchets' }),
      securite: t('report.type.securite', { defaultValue: 'Sécurité' }),
      espaces_verts: t('report.type.espaces_verts', { defaultValue: 'Espaces verts' }),
      assainissement: t('report.type.assainissement', { defaultValue: 'Assainissement' }),
      transport: t('report.type.transport', { defaultValue: 'Transport' }),
      autre: t('report.type.autre', { defaultValue: 'Autre' }),
    };
    return types[type] || type;
  };

  const formatDate = (dateString) => {
    if (!dateString) return '';
    const date = new Date(dateString);
    return new Intl.DateTimeFormat('fr-FR', {
      day: 'numeric',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    }).format(date);
  };

  if (loading) {
    return (
      <div className="space-y-4">
        {[1, 2, 3].map((i) => (
          <Card key={i} className="animate-pulse">
            <CardContent className="p-6">
              <div className="h-4 bg-neutral-200 rounded w-3/4 mb-2" />
              <div className="h-4 bg-neutral-200 rounded w-1/2" />
            </CardContent>
          </Card>
        ))}
      </div>
    );
  }

  if (error) {
    return (
      <Card className="border-red-200 bg-red-50">
        <CardContent className="p-6">
          <div className="flex items-center gap-3">
            <AlertCircle className="w-5 h-5 text-red-600" />
            <div>
              <p className="font-semibold text-red-900">
                {t('citizen.reports.error', { defaultValue: 'Erreur lors du chargement' })}
              </p>
              <p className="text-sm text-red-700">{error.message || error}</p>
            </div>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (!reports || reports.length === 0) {
    return (
      <Card>
        <CardContent className="p-12 text-center">
          <FileText className="w-12 h-12 text-neutral-400 mx-auto mb-4" />
          <p className="text-lg font-semibold text-neutral-900 mb-2">
            {t('citizen.reports.empty', { defaultValue: 'Aucun signalement' })}
          </p>
          <p className="text-sm text-neutral-600">
            {t('citizen.reports.empty_desc', {
              defaultValue: 'Vous n\'avez pas encore créé de signalement.',
            })}
          </p>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-4">
      {reports.map((report) => {
        const statusConfig = getStatusConfig(report.status);
        const StatusIcon = statusConfig.icon;

        return (
          <Card
            key={report.id}
            className="hover:shadow-md transition-shadow cursor-pointer"
            onClick={() => {
              if (onReportClick) {
                onReportClick(report.id);
              }
            }}
          >
            <CardHeader className="pb-3">
              <div className="flex items-start justify-between gap-3">
                <div className="flex-1">
                  <CardTitle className="text-lg mb-1">{getTypeLabel(report.type)}</CardTitle>
                  {report.commune && (
                    <CardDescription className="flex items-center gap-1 mt-1">
                      <MapPin className="w-4 h-4" />
                      {report.commune.name}
                      {report.commune.region && ` (${report.commune.region})`}
                    </CardDescription>
                  )}
                </div>
                <Badge className={statusConfig.color} variant="outline">
                  <StatusIcon className="w-3 h-3 mr-1" />
                  {statusConfig.label}
                </Badge>
              </div>
            </CardHeader>
            <CardContent>
              {report.description && (
                <p className="text-sm text-neutral-700 mb-3 line-clamp-2">{report.description}</p>
              )}
              <div className="flex items-center justify-between text-xs text-neutral-500">
                <div className="flex items-center gap-1">
                  <Calendar className="w-4 h-4" />
                  {formatDate(report.created_at)}
                </div>
                {report.audio_url && (
                  <Badge variant="outline" className="text-xs">
                    🎤 {t('citizen.reports.has_audio', { defaultValue: 'Audio' })}
                  </Badge>
                )}
                {report.image_url && (
                  <Badge variant="outline" className="text-xs">
                    📷 {t('citizen.reports.has_photo', { defaultValue: 'Photo' })}
                  </Badge>
                )}
              </div>
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}

export default CitizenReportList;

