// @generated by Cursor AI (Claude) — verified by Kevin

import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useAuth } from '@/context/AuthContext';
import { X, Loader2, AlertCircle } from 'lucide-react';
import CitizenReportList from '@/components/citizen/CitizenReportList';
import ReportDetailBottomSheet from '@/components/citizen/ReportDetailBottomSheet';
import * as reportApi from '@/api/reportApi';

/**
 * Composant DashboardBottomSheet - Bottom sheet pour le dashboard citoyen
 * 
 * S'affiche comme un modal qui remonte depuis le bas de l'écran
 * Affiche l'historique et le suivi des signalements du citoyen
 * 
 * @param {Object} props
 * @param {boolean} props.open - Si le bottom sheet est ouvert
 * @param {Function} props.onClose - Callback quand l'utilisateur ferme le sheet
 * 
 * @example
 * <DashboardBottomSheet
 *   open={showDashboard}
 *   onClose={() => setShowDashboard(false)}
 * />
 */
function DashboardBottomSheet({ open, onClose }) {
  const { t } = useTranslation('common');
  const { user } = useAuth();

  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [statusFilter, setStatusFilter] = useState(null); // null = tous
  const [selectedReportId, setSelectedReportId] = useState(null);
  const [showDetailSheet, setShowDetailSheet] = useState(false);

  // Charger les signalements quand le sheet s'ouvre
  useEffect(() => {
    if (open && user?.id) {
      loadReports();
    }
  }, [open, user?.id, statusFilter]);

  const loadReports = async () => {
    if (!user?.id) return;

    setLoading(true);
    setError(null);

    try {
      const reportsResult = await reportApi.getCitizenReports(user.id, {
        status: statusFilter || undefined,
        limit: 50,
      });

      if (reportsResult.error) {
        setError(reportsResult.error);
      } else {
        setReports(reportsResult.data || []);
      }
    } catch (err) {
      console.error('❌ Erreur chargement signalements:', err);
      setError({
        message: err.message || t('citizen.dashboard.load_error', { defaultValue: 'Erreur lors du chargement' }),
      });
    } finally {
      setLoading(false);
    }
  };

  // Empêcher le scroll du body quand le sheet est ouvert
  useEffect(() => {
    if (open) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [open]);

  if (!open) return null;

  return (
    <>
      {/* Overlay */}
      <div
        className="fixed inset-0 bg-black/50 z-40 animate-in fade-in-0"
        onClick={onClose}
        aria-hidden="true"
      />

      {/* Bottom Sheet */}
      <div
        className="fixed bottom-0 left-0 right-0 z-50 bg-white rounded-t-2xl shadow-2xl animate-in slide-in-from-bottom duration-300 max-h-[90vh] overflow-y-auto"
        role="dialog"
        aria-modal="true"
        aria-labelledby="dashboard-sheet-title"
      >
        {/* Handle bar */}
        <div className="flex justify-center pt-3 pb-2">
          <div className="w-12 h-1.5 bg-neutral-300 rounded-full" />
        </div>

        {/* Header */}
        <div className="flex items-center justify-between px-6 pb-4 border-b border-neutral-200">
          <div>
            <h2
              id="dashboard-sheet-title"
              className="text-lg font-semibold text-neutral-900"
            >
              {t('citizen.dashboard.title', { defaultValue: 'Mes signalements' })}
            </h2>
            <p className="text-sm text-neutral-600 mt-1">
              {t('citizen.dashboard.subtitle', {
                defaultValue: 'Consultez l\'historique et le statut de vos signalements',
              })}
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-full hover:bg-neutral-100 transition-colors"
            aria-label={t('buttons.close', { defaultValue: 'Fermer' })}
          >
            <X className="w-5 h-5 text-neutral-600" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-4">
          {/* Filtres */}
          <div className="flex flex-wrap gap-2">
            <button
              onClick={() => setStatusFilter(null)}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                statusFilter === null
                  ? 'bg-primary-600 text-white'
                  : 'bg-neutral-100 text-neutral-700 hover:bg-neutral-200'
              }`}
            >
              {t('citizen.dashboard.filter.all', { defaultValue: 'Tous' })}
            </button>
            <button
              onClick={() => setStatusFilter('pending')}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                statusFilter === 'pending'
                  ? 'bg-primary-600 text-white'
                  : 'bg-neutral-100 text-neutral-700 hover:bg-neutral-200'
              }`}
            >
              {t('citizen.dashboard.filter.pending', { defaultValue: 'En attente' })}
            </button>
            <button
              onClick={() => setStatusFilter('in_progress')}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                statusFilter === 'in_progress'
                  ? 'bg-primary-600 text-white'
                  : 'bg-neutral-100 text-neutral-700 hover:bg-neutral-200'
              }`}
            >
              {t('citizen.dashboard.filter.in_progress', { defaultValue: 'En cours' })}
            </button>
            <button
              onClick={() => setStatusFilter('resolved')}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                statusFilter === 'resolved'
                  ? 'bg-primary-600 text-white'
                  : 'bg-neutral-100 text-neutral-700 hover:bg-neutral-200'
              }`}
            >
              {t('citizen.dashboard.filter.resolved', { defaultValue: 'Résolus' })}
            </button>
          </div>

          {/* Liste des signalements */}
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="w-8 h-8 animate-spin text-primary-600" />
            </div>
          ) : error ? (
            <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
              <div className="flex items-center gap-3">
                <AlertCircle className="w-5 h-5 text-red-600" />
                <div>
                  <p className="font-semibold text-red-900">
                    {t('citizen.dashboard.error', { defaultValue: 'Erreur' })}
                  </p>
                  <p className="text-sm text-red-700">{error.message || error}</p>
                </div>
              </div>
            </div>
          ) : (
            <CitizenReportList 
              reports={reports} 
              loading={false} 
              error={null}
              onReportClick={(reportId) => {
                setSelectedReportId(reportId);
                setShowDetailSheet(true);
              }}
            />
          )}
        </div>
      </div>

      {/* Bottom Sheet pour les détails d'un signalement */}
      <ReportDetailBottomSheet
        open={showDetailSheet}
        onClose={() => {
          setShowDetailSheet(false);
          setSelectedReportId(null);
        }}
        reportId={selectedReportId}
      />
    </>
  );
}

export default DashboardBottomSheet;

