// @generated by Cursor AI (Claude) — verified by Kevin

import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { X, Loader2, AlertCircle, MapPin, Calendar, Clock, CheckCircle, XCircle, Play, Image as ImageIcon } from 'lucide-react';
import * as reportApi from '@/api/reportApi';
import { Badge } from '@/components/ui/badge';

/**
 * Composant ReportDetailBottomSheet - Bottom sheet pour afficher les détails d'un signalement
 * 
 * S'affiche comme un modal qui remonte depuis le bas de l'écran
 * Affiche les détails complets d'un signalement (statut, description, photo, audio, etc.)
 * 
 * @param {Object} props
 * @param {boolean} props.open - Si le bottom sheet est ouvert
 * @param {Function} props.onClose - Callback quand l'utilisateur ferme le sheet
 * @param {string} props.reportId - ID du signalement à afficher
 * 
 * @example
 * <ReportDetailBottomSheet
 *   open={showDetail}
 *   onClose={() => setShowDetail(false)}
 *   reportId={selectedReportId}
 * />
 */
function ReportDetailBottomSheet({ open, onClose, reportId }) {
  const { t } = useTranslation('common');
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  // Charger les détails du signalement quand le sheet s'ouvre
  useEffect(() => {
    if (open && reportId) {
      loadReportDetails();
    } else {
      // Réinitialiser quand le sheet se ferme
      setReport(null);
      setError(null);
    }
  }, [open, reportId]);

  const loadReportDetails = async () => {
    if (!reportId) return;

    setLoading(true);
    setError(null);

    try {
      const result = await reportApi.getReportById(reportId);

      if (result.error) {
        setError(result.error);
      } else {
        setReport(result.data);
      }
    } catch (err) {
      console.error('❌ Erreur chargement détails signalement:', err);
      setError({
        message: err.message || t('citizen.report_detail.load_error', { defaultValue: 'Erreur lors du chargement' }),
      });
    } finally {
      setLoading(false);
    }
  };

  // Empêcher le scroll du body quand le sheet est ouvert
  useEffect(() => {
    if (open) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [open]);

  const getStatusConfig = (status) => {
    const configs = {
      pending: {
        label: t('report.status.pending', { defaultValue: 'En attente' }),
        icon: Clock,
        color: 'bg-yellow-100 text-yellow-800 border-yellow-200',
      },
      in_progress: {
        label: t('report.status.in_progress', { defaultValue: 'En cours' }),
        icon: AlertCircle,
        color: 'bg-blue-100 text-blue-800 border-blue-200',
      },
      resolved: {
        label: t('report.status.resolved', { defaultValue: 'Résolu' }),
        icon: CheckCircle,
        color: 'bg-green-100 text-green-800 border-green-200',
      },
      rejected: {
        label: t('report.status.rejected', { defaultValue: 'Rejeté' }),
        icon: XCircle,
        color: 'bg-red-100 text-red-800 border-red-200',
      },
    };
    return configs[status] || configs.pending;
  };

  const getTypeLabel = (type) => {
    const types = {
      voirie: t('report.type.voirie', { defaultValue: 'Voirie' }),
      eclairage: t('report.type.eclairage', { defaultValue: 'Éclairage' }),
      eau: t('report.type.eau', { defaultValue: 'Eau' }),
      dechets: t('report.type.dechets', { defaultValue: 'Déchets' }),
      securite: t('report.type.securite', { defaultValue: 'Sécurité' }),
      espaces_verts: t('report.type.espaces_verts', { defaultValue: 'Espaces verts' }),
      assainissement: t('report.type.assainissement', { defaultValue: 'Assainissement' }),
      transport: t('report.type.transport', { defaultValue: 'Transport' }),
      autre: t('report.type.autre', { defaultValue: 'Autre' }),
    };
    return types[type] || type;
  };

  const formatDate = (dateString) => {
    if (!dateString) return '';
    const date = new Date(dateString);
    return new Intl.DateTimeFormat('fr-FR', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    }).format(date);
  };

  if (!open) return null;

  return (
    <>
      {/* Overlay */}
      <div
        className="fixed inset-0 bg-black/50 z-[60] animate-in fade-in-0"
        onClick={onClose}
        aria-hidden="true"
      />

      {/* Bottom Sheet */}
      <div
        className="fixed bottom-0 left-0 right-0 z-[70] bg-white rounded-t-2xl shadow-2xl animate-in slide-in-from-bottom duration-300 max-h-[90vh] overflow-y-auto"
        role="dialog"
        aria-modal="true"
        aria-labelledby="report-detail-title"
      >
        {/* Handle bar */}
        <div className="flex justify-center pt-3 pb-2">
          <div className="w-12 h-1.5 bg-neutral-300 rounded-full" />
        </div>

        {/* Header */}
        <div className="flex items-center justify-between px-6 pb-4 border-b border-neutral-200">
          <h2
            id="report-detail-title"
            className="text-lg font-semibold text-neutral-900"
          >
            {t('citizen.report_detail.title', { defaultValue: 'Détails du signalement' })}
          </h2>
          <button
            onClick={onClose}
            className="p-2 rounded-full hover:bg-neutral-100 transition-colors"
            aria-label={t('buttons.close', { defaultValue: 'Fermer' })}
          >
            <X className="w-5 h-5 text-neutral-600" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6">
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="w-8 h-8 animate-spin text-primary-600" />
            </div>
          ) : error ? (
            <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
              <div className="flex items-center gap-3">
                <AlertCircle className="w-5 h-5 text-red-600" />
                <div>
                  <p className="font-semibold text-red-900">
                    {t('citizen.report_detail.error', { defaultValue: 'Erreur' })}
                  </p>
                  <p className="text-sm text-red-700">{error.message || error}</p>
                </div>
              </div>
            </div>
          ) : report ? (
            <>
              {/* Type et Statut */}
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1">
                  <h3 className="text-xl font-bold text-neutral-900 mb-2">
                    {getTypeLabel(report.type)}
                  </h3>
                  <p className="text-sm text-neutral-500 font-mono">
                    #{report.id.slice(0, 8)}
                  </p>
                </div>
                <Badge className={getStatusConfig(report.status).color} variant="outline">
                  {(() => {
                    const StatusIcon = getStatusConfig(report.status).icon;
                    return (
                      <>
                        <StatusIcon className="w-3 h-3 mr-1" />
                        {getStatusConfig(report.status).label}
                      </>
                    );
                  })()}
                </Badge>
              </div>

              {/* Description */}
              {report.description && (
                <div className="space-y-2">
                  <h4 className="text-sm font-semibold text-neutral-700">
                    {t('citizen.report_detail.description', { defaultValue: 'Description' })}
                  </h4>
                  <p className="text-sm text-neutral-600 bg-neutral-50 p-4 rounded-lg">
                    {report.description}
                  </p>
                </div>
              )}

              {/* Photo */}
              {report.image_url && (
                <div className="space-y-2">
                  <h4 className="text-sm font-semibold text-neutral-700 flex items-center gap-2">
                    <ImageIcon className="w-4 h-4" />
                    {t('citizen.report_detail.photo', { defaultValue: 'Photo' })}
                  </h4>
                  <div className="rounded-lg overflow-hidden border border-neutral-200">
                    <img
                      src={report.image_url}
                      alt={t('citizen.report_detail.photo_alt', { defaultValue: 'Photo du signalement' })}
                      className="w-full h-auto object-cover"
                    />
                  </div>
                </div>
              )}

              {/* Audio */}
              {report.audio_url && (
                <div className="space-y-2">
                  <h4 className="text-sm font-semibold text-neutral-700 flex items-center gap-2">
                    <Play className="w-4 h-4" />
                    {t('citizen.report_detail.audio', { defaultValue: 'Enregistrement audio' })}
                  </h4>
                  <div className="bg-neutral-50 p-4 rounded-lg">
                    <audio controls className="w-full">
                      <source src={report.audio_url} type="audio/webm" />
                      <source src={report.audio_url} type="audio/mpeg" />
                      <source src={report.audio_url} type="audio/wav" />
                      {t('citizen.report_detail.audio_not_supported', {
                        defaultValue: 'Votre navigateur ne supporte pas la lecture audio.',
                      })}
                    </audio>
                  </div>
                </div>
              )}

              {/* Informations */}
              <div className="space-y-3 pt-4 border-t border-neutral-200">
                <h4 className="text-sm font-semibold text-neutral-700">
                  {t('citizen.report_detail.informations', { defaultValue: 'Informations' })}
                </h4>

                {/* Date */}
                <div className="flex items-start gap-3">
                  <Calendar className="w-4 h-4 text-neutral-500 mt-0.5" />
                  <div className="flex-1">
                    <p className="text-xs text-neutral-600">
                      {t('citizen.report_detail.created_at', { defaultValue: 'Date de création' })}
                    </p>
                    <p className="text-sm font-medium text-neutral-900">
                      {formatDate(report.created_at)}
                    </p>
                  </div>
                </div>

                {/* Commune */}
                {report.commune && (
                  <div className="flex items-start gap-3">
                    <MapPin className="w-4 h-4 text-neutral-500 mt-0.5" />
                    <div className="flex-1">
                      <p className="text-xs text-neutral-600">
                        {t('citizen.report_detail.commune', { defaultValue: 'Commune' })}
                      </p>
                      <p className="text-sm font-medium text-neutral-900">
                        {report.commune.name}
                        {report.commune.region && ` (${report.commune.region})`}
                      </p>
                    </div>
                  </div>
                )}

                {/* Position GPS */}
                {report.latitude && report.longitude && (
                  <div className="flex items-start gap-3">
                    <MapPin className="w-4 h-4 text-neutral-500 mt-0.5" />
                    <div className="flex-1">
                      <p className="text-xs text-neutral-600">
                        {t('citizen.report_detail.location', { defaultValue: 'Localisation GPS' })}
                      </p>
                      <p className="text-sm font-medium text-neutral-900 font-mono">
                        {report.latitude.toFixed(6)}, {report.longitude.toFixed(6)}
                      </p>
                    </div>
                  </div>
                )}
              </div>
            </>
          ) : null}
        </div>
      </div>
    </>
  );
}

export default ReportDetailBottomSheet;

