// @generated by Cursor AI (Claude) — verified by Kevin

import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { AlertCircle, CheckCircle, Edit2, ArrowLeft, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

/**
 * Composant d'affichage et modification du résumé d'inscription
 * 
 * Affiche toutes les données collectées via la voix et permet
 * à l'utilisateur de les modifier avant validation.
 * 
 * @param {Object} data - Données collectées
 * @param {Array} communes - Liste des communes disponibles
 * @param {Function} onConfirm - Callback appelé avec les données finales
 * @param {Function} onBack - Callback pour revenir au flux vocal
 * @param {Function} onCancel - Callback pour annuler
 */
function SignupSummaryCard({ data, communes = [], onConfirm, onBack, onCancel }) {
  const { t } = useTranslation('common');

  const [formData, setFormData] = useState({
    firstName: data.firstName || '',
    lastName: data.lastName || '',
    age: data.age || '',
    commune_id: data.commune_id || '',
    phone: data.phone || '',
    address: data.address || '',
    email: data.email || '',
  });

  const [editing, setEditing] = useState(null);
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState({});

  /**
   * Trouver le nom de la commune par ID
   */
  const getCommuneName = (communeId) => {
    if (!communeId) return '';
    const commune = communes.find(c => c.id === communeId);
    return commune ? `${commune.name} (${commune.region})` : '';
  };

  /**
   * Valider un champ
   */
  const validateField = (field, value) => {
    const fieldErrors = { ...errors };

    switch (field) {
      case 'firstName':
      case 'lastName':
        if (!value || value.trim().length < 2) {
          fieldErrors[field] = t('voiceSignup.summary.errors.nameRequired', { defaultValue: 'Ce champ est obligatoire (min 2 caractères)' });
        } else {
          delete fieldErrors[field];
        }
        break;

      case 'age':
        const age = parseInt(value);
        if (!value || isNaN(age) || age < 1 || age > 120) {
          fieldErrors[field] = t('voiceSignup.summary.errors.ageInvalid', { defaultValue: 'Âge invalide (1-120)' });
        } else {
          delete fieldErrors[field];
        }
        break;

      case 'commune_id':
        if (!value) {
          fieldErrors[field] = t('voiceSignup.summary.errors.communeRequired', { defaultValue: 'La commune est obligatoire' });
        } else {
          delete fieldErrors[field];
        }
        break;

      case 'phone':
        const digits = value.replace(/\D/g, '');
        if (!value || digits.length !== 9) {
          fieldErrors[field] = t('voiceSignup.summary.errors.phoneInvalid', { defaultValue: 'Numéro invalide (9 chiffres)' });
        } else {
          delete fieldErrors[field];
        }
        break;

      case 'email':
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!value || !emailRegex.test(value)) {
          fieldErrors[field] = t('voiceSignup.summary.errors.emailInvalid', { defaultValue: 'Format d\'email invalide' });
        } else {
          delete fieldErrors[field];
        }
        break;

      case 'address':
        if (!value || value.trim().length < 5) {
          fieldErrors[field] = t('voiceSignup.summary.errors.addressRequired', { defaultValue: 'Adresse invalide (min 5 caractères)' });
        } else {
          delete fieldErrors[field];
        }
        break;
    }

    setErrors(fieldErrors);
    return !fieldErrors[field];
  };

  /**
   * Valider tout le formulaire
   */
  const validateForm = () => {
    const fields = ['firstName', 'lastName', 'age', 'commune_id', 'phone', 'address', 'email'];
    let isValid = true;

    fields.forEach(field => {
      if (!validateField(field, formData[field])) {
        isValid = false;
      }
    });

    return isValid;
  };

  /**
   * Gérer le changement de valeur
   */
  const handleChange = (field, value) => {
    setFormData(prev => ({ ...prev, [field]: value }));
    if (editing === field) {
      validateField(field, value);
    }
  };

  /**
   * Activer/désactiver l'édition d'un champ
   */
  const toggleEdit = (field) => {
    if (editing === field) {
      // Valider avant de désactiver
      if (validateField(field, formData[field])) {
        setEditing(null);
      }
    } else {
      setEditing(field);
    }
  };

  /**
   * Gérer la soumission
   */
  const handleSubmit = async () => {
    if (!validateForm()) {
      return;
    }

    setLoading(true);
    try {
      // Préparer les données finales
      const finalData = {
        ...formData,
        age: parseInt(formData.age),
        phone: formData.phone.replace(/\D/g, ''), // Nettoyer le téléphone
      };

      if (onConfirm) {
        onConfirm(finalData);
      }
    } catch (err) {
      console.error('Erreur soumission résumé:', err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle className="text-xl">
          {t('voiceSignup.summary.title', { defaultValue: 'Résumé de vos informations' })}
        </CardTitle>
        <CardDescription>
          {t('voiceSignup.summary.subtitle', { defaultValue: 'Vérifiez et modifiez si nécessaire' })}
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Prénom */}
        <div className="space-y-2">
          <Label htmlFor="firstName">
            {t('voiceSignup.summary.firstName', { defaultValue: 'Prénom' })}
          </Label>
          <div className="flex gap-2">
            {editing === 'firstName' ? (
              <Input
                id="firstName"
                value={formData.firstName}
                onChange={(e) => handleChange('firstName', e.target.value)}
                onBlur={() => toggleEdit('firstName')}
                className={errors.firstName ? 'border-error-500' : ''}
                autoFocus
                aria-invalid={!!errors.firstName}
                aria-describedby={errors.firstName ? 'firstName-error' : undefined}
                aria-label={t('voiceSignup.summary.firstName', { defaultValue: 'Prénom' })}
              />
            ) : (
              <div className="flex-1 flex items-center justify-between p-2 border rounded-md bg-neutral-50">
                <span>{formData.firstName || '-'}</span>
                <Button
                  variant="ghost"
                  size="icon-sm"
                  onClick={() => toggleEdit('firstName')}
                  aria-label={t('voiceSignup.summary.editField', { defaultValue: 'Modifier le prénom', field: t('voiceSignup.summary.firstName', { defaultValue: 'Prénom' }) })}
                >
                  <Edit2 className="h-4 w-4" aria-hidden="true" />
                </Button>
              </div>
            )}
          </div>
          {errors.firstName && (
            <p className="text-sm text-error-600 flex items-center gap-1" role="alert" aria-live="polite">
              <AlertCircle className="h-4 w-4" aria-hidden="true" />
              <span id="firstName-error">{errors.firstName}</span>
            </p>
          )}
        </div>

        {/* Nom */}
        <div className="space-y-2">
          <Label htmlFor="lastName">
            {t('voiceSignup.summary.lastName', { defaultValue: 'Nom' })}
          </Label>
          <div className="flex gap-2">
            {editing === 'lastName' ? (
              <Input
                id="lastName"
                value={formData.lastName}
                onChange={(e) => handleChange('lastName', e.target.value)}
                onBlur={() => toggleEdit('lastName')}
                className={errors.lastName ? 'border-error-500' : ''}
                autoFocus
              />
            ) : (
              <div className="flex-1 flex items-center justify-between p-2 border rounded-md bg-neutral-50">
                <span>{formData.lastName || '-'}</span>
                <Button
                  variant="ghost"
                  size="icon-sm"
                  onClick={() => toggleEdit('lastName')}
                >
                  <Edit2 className="h-4 w-4" />
                </Button>
              </div>
            )}
          </div>
          {errors.lastName && (
            <p className="text-sm text-error-600 flex items-center gap-1">
              <AlertCircle className="h-4 w-4" />
              {errors.lastName}
            </p>
          )}
        </div>

        {/* Âge */}
        <div className="space-y-2">
          <Label htmlFor="age">
            {t('voiceSignup.summary.age', { defaultValue: 'Âge' })}
          </Label>
          <div className="flex gap-2">
            {editing === 'age' ? (
              <Input
                id="age"
                type="number"
                min="1"
                max="120"
                value={formData.age}
                onChange={(e) => handleChange('age', e.target.value)}
                onBlur={() => toggleEdit('age')}
                className={errors.age ? 'border-error-500' : ''}
                autoFocus
              />
            ) : (
              <div className="flex-1 flex items-center justify-between p-2 border rounded-md bg-neutral-50">
                <span>{formData.age || '-'}</span>
                <Button
                  variant="ghost"
                  size="icon-sm"
                  onClick={() => toggleEdit('age')}
                >
                  <Edit2 className="h-4 w-4" />
                </Button>
              </div>
            )}
          </div>
          {errors.age && (
            <p className="text-sm text-error-600 flex items-center gap-1">
              <AlertCircle className="h-4 w-4" />
              {errors.age}
            </p>
          )}
        </div>

        {/* Commune */}
        <div className="space-y-2">
          <Label htmlFor="commune">
            {t('voiceSignup.summary.commune', { defaultValue: 'Commune' })}
          </Label>
          <div className="flex gap-2">
            {editing === 'commune_id' ? (
              <Select
                value={formData.commune_id}
                onValueChange={(value) => {
                  handleChange('commune_id', value);
                  toggleEdit('commune_id');
                }}
              >
                <SelectTrigger id="commune" className={errors.commune_id ? 'border-error-500' : ''}>
                  <SelectValue placeholder={t('voiceSignup.summary.selectCommune', { defaultValue: 'Sélectionnez une commune' })} />
                </SelectTrigger>
                <SelectContent className="z-[1002]">
                  {communes.map((commune) => (
                    <SelectItem key={commune.id} value={commune.id}>
                      {commune.name} ({commune.region})
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            ) : (
              <div className="flex-1 flex items-center justify-between p-2 border rounded-md bg-neutral-50">
                <span>{getCommuneName(formData.commune_id) || '-'}</span>
                <Button
                  variant="ghost"
                  size="icon-sm"
                  onClick={() => toggleEdit('commune_id')}
                >
                  <Edit2 className="h-4 w-4" />
                </Button>
              </div>
            )}
          </div>
          {errors.commune_id && (
            <p className="text-sm text-error-600 flex items-center gap-1">
              <AlertCircle className="h-4 w-4" />
              {errors.commune_id}
            </p>
          )}
        </div>

        {/* Téléphone */}
        <div className="space-y-2">
          <Label htmlFor="phone">
            {t('voiceSignup.summary.phone', { defaultValue: 'Numéro de téléphone' })}
          </Label>
          <div className="flex gap-2">
            {editing === 'phone' ? (
              <Input
                id="phone"
                type="tel"
                value={formData.phone}
                onChange={(e) => handleChange('phone', e.target.value)}
                onBlur={() => toggleEdit('phone')}
                className={errors.phone ? 'border-error-500' : ''}
                placeholder="77 123 45 67"
                autoFocus
              />
            ) : (
              <div className="flex-1 flex items-center justify-between p-2 border rounded-md bg-neutral-50">
                <span>{formData.phone || '-'}</span>
                <Button
                  variant="ghost"
                  size="icon-sm"
                  onClick={() => toggleEdit('phone')}
                >
                  <Edit2 className="h-4 w-4" />
                </Button>
              </div>
            )}
          </div>
          {errors.phone && (
            <p className="text-sm text-error-600 flex items-center gap-1">
              <AlertCircle className="h-4 w-4" />
              {errors.phone}
            </p>
          )}
        </div>

        {/* Adresse */}
        <div className="space-y-2">
          <Label htmlFor="address">
            {t('voiceSignup.summary.address', { defaultValue: 'Adresse' })}
          </Label>
          <div className="flex gap-2">
            {editing === 'address' ? (
              <Input
                id="address"
                value={formData.address}
                onChange={(e) => handleChange('address', e.target.value)}
                onBlur={() => toggleEdit('address')}
                className={errors.address ? 'border-error-500' : ''}
                autoFocus
              />
            ) : (
              <div className="flex-1 flex items-center justify-between p-2 border rounded-md bg-neutral-50">
                <span>{formData.address || '-'}</span>
                <Button
                  variant="ghost"
                  size="icon-sm"
                  onClick={() => toggleEdit('address')}
                >
                  <Edit2 className="h-4 w-4" />
                </Button>
              </div>
            )}
          </div>
          {errors.address && (
            <p className="text-sm text-error-600 flex items-center gap-1">
              <AlertCircle className="h-4 w-4" />
              {errors.address}
            </p>
          )}
        </div>

        {/* Email */}
        <div className="space-y-2">
          <Label htmlFor="email">
            {t('voiceSignup.summary.email', { defaultValue: 'Email' })}
          </Label>
          <div className="flex gap-2">
            {editing === 'email' ? (
              <Input
                id="email"
                type="email"
                value={formData.email}
                onChange={(e) => handleChange('email', e.target.value)}
                onBlur={() => toggleEdit('email')}
                className={errors.email ? 'border-error-500' : ''}
                autoFocus
              />
            ) : (
              <div className="flex-1 flex items-center justify-between p-2 border rounded-md bg-neutral-50">
                <span>{formData.email || '-'}</span>
                <Button
                  variant="ghost"
                  size="icon-sm"
                  onClick={() => toggleEdit('email')}
                >
                  <Edit2 className="h-4 w-4" />
                </Button>
              </div>
            )}
          </div>
          {errors.email && (
            <p className="text-sm text-error-600 flex items-center gap-1">
              <AlertCircle className="h-4 w-4" />
              {errors.email}
            </p>
          )}
        </div>

        {/* Actions */}
        <div className="flex flex-col gap-2 pt-4">
          <Button
            onClick={handleSubmit}
            disabled={loading || Object.keys(errors).length > 0}
            className="w-full"
            aria-label={t('voiceSignup.summary.confirm', { defaultValue: 'Confirmer et créer mon compte' })}
          >
            {loading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                {t('voiceSignup.summary.creating', { defaultValue: 'Création en cours...' })}
              </>
            ) : (
              <>
                <CheckCircle className="mr-2 h-4 w-4" />
                {t('voiceSignup.summary.confirm', { defaultValue: 'Confirmer et créer mon compte' })}
              </>
            )}
          </Button>
          <div className="flex gap-2">
            <Button
              variant="outline"
              onClick={onBack}
              className="flex-1"
            >
              <ArrowLeft className="mr-2 h-4 w-4" />
              {t('voiceSignup.summary.back', { defaultValue: 'Retour' })}
            </Button>
            <Button
              variant="outline"
              onClick={onCancel}
              className="flex-1"
            >
              {t('voiceSignup.summary.cancel', { defaultValue: 'Annuler' })}
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

export default SignupSummaryCard;

