// @generated by Cursor AI (Claude) — verified by Kevin

import { useState, useEffect, useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { useLanguage } from '@/context/LangContext';
import { Mic, MicOff, Loader2, AlertCircle, RotateCcw, X, Keyboard } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import useVoiceSignupFlow from '@/hooks/useVoiceSignupFlow';
import { createSignupQuestions } from '@/utils/voiceSignupQuestions';
import useCommunes from '@/hooks/useCommunes';
import SignupSummaryCard from './SignupSummaryCard';

/**
 * Composant principal du flux d'inscription vocale
 * 
 * Fonctionnalités :
 * - Animation de l'agent (indicateur visuel)
 * - Indicateur d'écoute (microphone animé)
 * - Affichage de la question actuelle
 * - Affichage de la réponse transcrit
 * - Boutons de contrôle (répéter, annuler, saisie manuelle)
 * - Gestion des états (permission, écoute, traitement, erreur)
 * 
 * @param {Function} onComplete - Callback appelé quand l'inscription est terminée
 * @param {Function} onCancel - Callback appelé quand l'utilisateur annule
 */
function VoiceSignupFlow({ onComplete, onCancel }) {
  const { t, i18n } = useTranslation('common');
  const { currentLanguage } = useLanguage();
  const { communes, loading: communesLoading } = useCommunes();

  const [showSummary, setShowSummary] = useState(false);
  const [showManualInput, setShowManualInput] = useState(false);

  // Créer les questions avec les communes et la langue
  const questions = createSignupQuestions(communes, currentLanguage);

  // Hook du flux vocal
  const {
    start,
    currentStep,
    collectedData,
    isAsking,
    isGenerating,
    isListening,
    isProcessing,
    isComplete,
    isStarted,
    showQuestionText,
    error,
    retryCurrentQuestion,
    reset,
    currentQuestion,
    totalSteps,
  } = useVoiceSignupFlow(questions, {
    language: currentLanguage,
    maxRetries: 2,
    onComplete: (data) => {
      setShowSummary(true);
    },
  });

  const normalizedError = useMemo(() => {
    if (!error) {
      return null;
    }
    if (typeof error === 'string') {
      return { code: undefined, message: error };
    }
    return error;
  }, [error]);

  const shouldShowError = normalizedError 
    && normalizedError.code !== 'NOT_SUPPORTED' 
    && normalizedError.code !== 'PERMISSION_DENIED';

  const resolvedErrorMessage = useMemo(() => {
    if (!normalizedError) {
      return null;
    }
    if (normalizedError.code === 'RETRY_LIMIT') {
      return t('voiceSignup.error.retryLimit', { 
        defaultValue: 'Je n’ai pas compris après plusieurs tentatives. Touchez « Répéter » ou utilisez la saisie manuelle.' 
      });
    }
    return normalizedError.message 
      || t('voiceSignup.error.recognitionFailed', { defaultValue: 'Je n\'ai pas compris. Pouvez-vous répéter ?' });
  }, [normalizedError, t]);

  /**
   * Démarrer le flux au montage
   */
  useEffect(() => {
    if (!isStarted && !communesLoading && communes.length > 0) {
      start();
    }
  }, [isStarted, communesLoading, communes.length, start]);

  /**
   * Gérer l'annulation
   */
  const handleCancel = () => {
    reset();
    if (onCancel) {
      onCancel();
    }
  };

  /**
   * Gérer la confirmation du résumé
   */
  const handleSummaryConfirm = (finalData) => {
    if (onComplete) {
      onComplete(finalData);
    }
  };

  /**
   * Gérer le retour au flux vocal depuis le résumé
   */
  const handleBackToFlow = () => {
    setShowSummary(false);
  };

  // Si le résumé est affiché
  if (showSummary) {
    return (
      <SignupSummaryCard
        data={collectedData}
        communes={communes}
        onConfirm={handleSummaryConfirm}
        onBack={handleBackToFlow}
        onCancel={handleCancel}
      />
    );
  }

  // État initial : pas encore démarré
  if (!isStarted) {
    return (
      <Card className="w-full">
        <CardContent className="pt-6">
          <div className="flex flex-col items-center space-y-4">
            <div className="w-16 h-16 rounded-full bg-primary-100 flex items-center justify-center">
              <Mic className="h-8 w-8 text-primary-600" />
            </div>
            <div className="text-center space-y-2">
              <h3 className="text-lg font-semibold text-neutral-900">
                {t('voiceSignup.ready', { defaultValue: 'Prêt à commencer' })}
              </h3>
              <p className="text-sm text-neutral-600">
                {t('voiceSignup.readyDesc', { defaultValue: 'L\'agent IA va vous poser quelques questions' })}
              </p>
            </div>
            {communesLoading && (
              <div className="flex items-center gap-2 text-sm text-neutral-500">
                <Loader2 className="h-4 w-4 animate-spin" />
                <span>{t('voiceSignup.loading', { defaultValue: 'Chargement...' })}</span>
              </div>
            )}
          </div>
        </CardContent>
      </Card>
    );
  }

  // État d'erreur (API non supportée, permission refusée)
  if (error && error.code === 'NOT_SUPPORTED') {
    return (
      <Card className="w-full">
        <CardContent className="pt-6">
          <div className="flex flex-col items-center space-y-4">
            <AlertCircle className="h-12 w-12 text-error-600" />
            <div className="text-center space-y-2">
              <h3 className="text-lg font-semibold text-neutral-900">
                {t('voiceSignup.error.notSupported', { defaultValue: 'Fonctionnalité non supportée' })}
              </h3>
              <p className="text-sm text-neutral-600">
                {error.message || t('voiceSignup.error.notSupportedDesc', { defaultValue: 'Votre navigateur ne supporte pas la reconnaissance vocale.' })}
              </p>
            </div>
            <Button
              variant="outline"
              onClick={() => setShowManualInput(true)}
            >
              <Keyboard className="mr-2 h-4 w-4" />
              {t('voiceSignup.controls.manual', { defaultValue: 'Saisie manuelle' })}
            </Button>
          </div>
        </CardContent>
      </Card>
    );
  }

  // État d'erreur de permission
  if (error && error.code === 'PERMISSION_DENIED') {
    return (
      <Card className="w-full">
        <CardContent className="pt-6">
          <div className="flex flex-col items-center space-y-4">
            <MicOff className="h-12 w-12 text-error-600" />
            <div className="text-center space-y-2">
              <h3 className="text-lg font-semibold text-neutral-900">
                {t('voiceSignup.error.permissionDenied', { defaultValue: 'Accès au microphone refusé' })}
              </h3>
              <p className="text-sm text-neutral-600">
                {error.message || t('voiceSignup.error.permissionDeniedDesc', { defaultValue: 'Veuillez autoriser l\'accès au microphone dans les paramètres de votre navigateur.' })}
              </p>
            </div>
            <div className="flex gap-2">
              <Button
                variant="outline"
                onClick={retryCurrentQuestion}
              >
                <RotateCcw className="mr-2 h-4 w-4" />
                {t('voiceSignup.controls.retry', { defaultValue: 'Réessayer' })}
              </Button>
              <Button
                variant="outline"
                onClick={() => setShowManualInput(true)}
              >
                <Keyboard className="mr-2 h-4 w-4" />
                {t('voiceSignup.controls.manual', { defaultValue: 'Saisie manuelle' })}
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>
    );
  }

  // État normal : flux en cours
  return (
    <Card className="w-full">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-lg">
              {t('voiceSignup.title', { defaultValue: 'Inscription vocale' })}
            </CardTitle>
            <CardDescription>
              {t('voiceSignup.progress', { 
                defaultValue: 'Question {{current}} sur {{total}}',
                current: currentStep + 1,
                total: totalSteps,
              })}
            </CardDescription>
          </div>
          <Button
            variant="ghost"
            size="icon"
            onClick={handleCancel}
            aria-label={t('voiceSignup.controls.cancel', { defaultValue: 'Annuler' })}
          >
            <X className="h-4 w-4" />
          </Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Indicateur visuel de l'agent */}
        <div className="flex justify-center" role="status" aria-live="polite" aria-atomic="true">
          <div 
            className={`relative w-24 h-24 rounded-full flex items-center justify-center transition-all ${
              isAsking 
                ? 'bg-primary-100 scale-110' 
                : isListening 
                  ? 'bg-success-100 scale-110' 
                  : 'bg-neutral-100'
            }`}
            aria-label={
              isAsking 
                ? t('voiceSignup.agentSpeaking', { defaultValue: 'L\'agent parle...' })
                : isListening 
                  ? t('voiceSignup.listening', { defaultValue: 'J\'écoute...' })
                  : t('voiceSignup.ready', { defaultValue: 'Prêt à commencer' })
            }
          >
            {isAsking && (
              <div className="absolute inset-0 rounded-full border-4 border-primary-400 animate-ping opacity-75" aria-hidden="true" />
            )}
            {isListening && (
              <div className="absolute inset-0 rounded-full border-4 border-success-400 animate-pulse opacity-75" aria-hidden="true" />
            )}
            {isAsking ? (
              <div className="w-12 h-12 rounded-full bg-primary-600 flex items-center justify-center" aria-hidden="true">
                <div className="w-6 h-6 rounded-full bg-white animate-pulse" />
              </div>
            ) : isListening ? (
              <Mic className="h-12 w-12 text-success-600 animate-pulse" aria-hidden="true" />
            ) : (
              <Mic className="h-12 w-12 text-neutral-400" aria-hidden="true" />
            )}
          </div>
        </div>

        {/* Question actuelle */}
        {currentQuestion && (
          <div className="text-center space-y-2" role="region" aria-live="polite" aria-atomic="true">
            {/* Afficher le texte de la question seulement quand la synthèse vocale a commencé */}
            {showQuestionText ? (
              <h3 className="text-lg font-medium text-neutral-900" id="current-question">
                {typeof currentQuestion.question === 'function' 
                  ? currentQuestion.question(collectedData)
                  : currentQuestion.question}
              </h3>
            ) : (
              <h3 className="text-lg font-medium text-neutral-500" id="current-question">
                {t('voiceSignup.agentSpeaking', { defaultValue: 'L\'agent parle...' })}
              </h3>
            )}
            {isGenerating && (
              <p className="text-sm text-neutral-500 flex items-center justify-center gap-2 animate-pulse" aria-hidden="true">
                <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />
                {t('voiceSignup.generating', { defaultValue: 'Génération de la voix...' })}
              </p>
            )}
            {isAsking && !showQuestionText && !isGenerating && (
              <p className="text-sm text-neutral-500 animate-pulse" aria-hidden="true">
                {t('voiceSignup.agentSpeaking', { defaultValue: 'L\'agent parle...' })}
              </p>
            )}
            {isListening && (
              <p className="text-sm text-success-600 font-medium animate-pulse" aria-hidden="true">
                {t('voiceSignup.listening', { defaultValue: 'J\'écoute...' })}
              </p>
            )}
            {isProcessing && (
              <p className="text-sm text-neutral-500 flex items-center justify-center gap-2" aria-hidden="true">
                <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />
                {t('voiceSignup.processing', { defaultValue: 'Traitement en cours...' })}
              </p>
            )}
          </div>
        )}

        {/* Erreur */}
        {shouldShowError && resolvedErrorMessage && (
          <div 
            className="p-3 rounded-lg bg-error-50 border border-error-200" 
            role="alert" 
            aria-live="assertive"
            aria-atomic="true"
          >
            <p className="text-sm text-error-700 flex items-center gap-2">
              <AlertCircle className="h-4 w-4 flex-shrink-0" aria-hidden="true" />
              {resolvedErrorMessage}
            </p>
          </div>
        )}

        {/* Contrôles */}
        <div className="flex flex-col gap-2" role="toolbar" aria-label={t('voiceSignup.controls.toolbar', { defaultValue: 'Contrôles de l\'inscription vocale' })}>
          <Button
            variant="outline"
            onClick={retryCurrentQuestion}
            className="w-full"
            disabled={isAsking || isGenerating || isProcessing}
            aria-label={t('voiceSignup.controls.repeat', { defaultValue: 'Répéter la question' })}
          >
            <RotateCcw className={`mr-2 h-4 w-4 ${isProcessing ? 'animate-spin' : ''}`} aria-hidden="true" />
            {t('voiceSignup.controls.repeat', { defaultValue: 'Répéter la question' })}
          </Button>
          <div className="flex gap-2">
            <Button
              variant="outline"
              onClick={() => setShowManualInput(true)}
              className="flex-1"
              aria-label={t('voiceSignup.controls.manual', { defaultValue: 'Saisie manuelle' })}
            >
              <Keyboard className="mr-2 h-4 w-4" aria-hidden="true" />
              {t('voiceSignup.controls.manual', { defaultValue: 'Saisie manuelle' })}
            </Button>
            <Button
              variant="outline"
              onClick={handleCancel}
              className="flex-1"
              aria-label={t('voiceSignup.controls.cancel', { defaultValue: 'Annuler' })}
            >
              <X className="mr-2 h-4 w-4" aria-hidden="true" />
              {t('voiceSignup.controls.cancel', { defaultValue: 'Annuler' })}
            </Button>
          </div>
        </div>

        {/* Barre de progression */}
        <div className="space-y-1" role="progressbar" aria-valuenow={currentStep + 1} aria-valuemin={1} aria-valuemax={totalSteps} aria-label={t('voiceSignup.progress', { 
          defaultValue: 'Question {{current}} sur {{total}}',
          current: currentStep + 1,
          total: totalSteps,
        })}>
          <div className="flex justify-between text-xs text-neutral-500">
            <span>{t('voiceSignup.progress', { 
              defaultValue: 'Question {{current}} sur {{total}}',
              current: currentStep + 1,
              total: totalSteps,
            })}</span>
            <span aria-hidden="true">{Math.round(((currentStep + 1) / totalSteps) * 100)}%</span>
          </div>
          <div className="w-full h-3 bg-neutral-200 rounded-full overflow-hidden relative" aria-hidden="true">
            <div
              className="h-full bg-gradient-to-r from-primary-500 to-primary-600 transition-all duration-500 ease-out relative"
              style={{ width: `${((currentStep + 1) / totalSteps) * 100}%` }}
            >
              {/* Animation de chargement shimmer */}
              <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/40 to-transparent animate-shimmer" />
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

export default VoiceSignupFlow;

