
// @generated by Cursor AI (Claude) — verified by Kevin

import { NavLink } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Settings, FileText } from 'lucide-react';

/**
 * Bottom Navigation pour citoyens (Mobile-first)
 * 
 * Rôle :
 * - Navigation principale en bas de l'écran
 * - 2 onglets : Mes signalements, Paramètres
 * - Design moderne avec animations fluides
 * - Active state visuellement clair
 * 
 * Usage :
 * <BottomNavigation />
 * 
 * Features :
 * - Fixé en bas de l'écran
 * - Responsive (mobile, tablet, desktop)
 * - Traductions i18n (FR/Wolof)
 * - Transitions douces
 * 
 * Note : Le bouton "Signaler" a été retiré car les types de signalement
 * sont maintenant accessibles directement depuis la page d'accueil
 */
function BottomNavigation() {
  const { t } = useTranslation('common');

  const navItems = [
    {
      to: '/citizen/dashboard',
      icon: FileText,
      label: t('nav.my_reports', { defaultValue: 'Mes signalements' }),
    },
    {
      to: '/parametres',
      icon: Settings,
      label: t('nav.settings', { defaultValue: 'Paramètres' }),
    },
  ];

  return (
    <nav 
      className="fixed bottom-0 left-0 right-0 z-50 bg-black backdrop-blur-sm border-t border-neutral-800 shadow-2xl"
      aria-label="Navigation principale"
    >
      <div className="max-w-screen-xl mx-auto">
        <div className="flex items-center justify-around h-20 px-2">
          {navItems.map((item) => {
            const Icon = item.icon;
            return (
              <NavLink
                key={item.to}
                to={item.to}
                end={item.exact}
                className={({ isActive }) =>
                  `group flex flex-col items-center justify-center flex-1 h-full gap-1 px-3 rounded-xl transition-all duration-300 relative overflow-hidden ${
                    isActive
                      ? 'text-white scale-105 bg-white/20'
                      : 'text-white/80 hover:text-white hover:bg-white/10 hover:scale-105'
                  }`
                }
              >
                {({ isActive }) => (
                  <>
                    {/* Effet de brillance au hover */}
                    {!isActive && (
                      <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/30 to-transparent -translate-x-full group-hover:translate-x-full transition-transform duration-700" />
                    )}
                    
                    {/* Indicateur actif en bas */}
                    {isActive && (
                      <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-12 h-1 bg-white rounded-t-full" />
                    )}
                    
                    <div className={`relative z-10 p-2 rounded-lg transition-all duration-300 ${
                      isActive 
                        ? 'bg-blue-500/30' 
                        : 'bg-blue-500/20 group-hover:bg-blue-500/30'
                    }`}>
                      <Icon 
                        className={`transition-all duration-300 ${
                          isActive 
                            ? 'w-8 h-8 drop-shadow-sm' 
                            : 'w-7 h-7 group-hover:w-8 group-hover:h-8 group-hover:drop-shadow-sm'
                        }`}
                        strokeWidth={isActive ? 2.5 : 2}
                      />
                    </div>
                    <span 
                      className={`relative z-10 text-sm transition-all duration-300 ${
                        isActive 
                          ? 'font-semibold' 
                          : 'font-medium group-hover:font-semibold'
                      }`}
                    >
                      {item.label}
                    </span>
                  </>
                )}
              </NavLink>
            );
          })}
        </div>
      </div>
    </nav>
  );
}

export default BottomNavigation;

