// @generated by Cursor AI (Claude) — verified by Kevin Mendy
import { NavLink } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Home, Map, PlusCircle, Settings } from 'lucide-react';

/**
 * Bottom Navigation pour citoyens (Mobile-first)
 * 
 * Rôle :
 * - Navigation principale en bas de l'écran
 * - 4 onglets : Accueil, Carte, Signaler, Paramètres
 * - Design moderne avec animations fluides
 * - Active state visuellement clair
 * 
 * Usage :
 * <BottomNavigation />
 * 
 * Features :
 * - Fixé en bas de l'écran
 * - Responsive (mobile, tablet, desktop)
 * - Traductions i18n (FR/Wolof)
 * - Transitions douces
 */
function BottomNavigation() {
  const { t } = useTranslation('common');

  const navItems = [
    {
      to: '/',
      icon: Home,
      label: t('nav.home', { defaultValue: 'Accueil' }),
      exact: true, // Match exact pour "/"
    },
    {
      to: '/carte',
      icon: Map,
      label: t('nav.map', { defaultValue: 'Carte' }),
    },
    {
      to: '/signalements/nouveau',
      icon: PlusCircle,
      label: t('nav.report', { defaultValue: 'Signaler' }),
    },
    {
      to: '/parametres',
      icon: Settings,
      label: t('nav.settings', { defaultValue: 'Paramètres' }),
    },
  ];

  return (
    <nav 
      className="fixed bottom-0 left-0 right-0 z-50 bg-white/95 backdrop-blur-sm border-t border-neutral-200 shadow-2xl"
      aria-label="Navigation principale"
    >
      <div className="max-w-screen-xl mx-auto">
        <div className="flex items-center justify-around h-16 px-2">
          {navItems.map((item) => {
            const Icon = item.icon;
            return (
              <NavLink
                key={item.to}
                to={item.to}
                end={item.exact}
                className={({ isActive }) =>
                  `flex flex-col items-center justify-center flex-1 h-full gap-1 px-3 rounded-lg transition-all duration-200 ${
                    isActive
                      ? 'text-primary-600 scale-105'
                      : 'text-neutral-500 hover:text-primary-500 hover:bg-primary-50/50'
                  }`
                }
              >
                {({ isActive }) => (
                  <>
                    <Icon 
                      className={`transition-all duration-200 ${
                        isActive ? 'w-7 h-7' : 'w-6 h-6'
                      }`}
                      strokeWidth={isActive ? 2.5 : 2}
                    />
                    <span 
                      className={`text-xs transition-all duration-200 ${
                        isActive ? 'font-semibold' : 'font-medium'
                      }`}
                    >
                      {item.label}
                    </span>
                  </>
                )}
              </NavLink>
            );
          })}
        </div>
      </div>
    </nav>
  );
}

export default BottomNavigation;

