// @generated by Cursor AI (Claude) — verified by Kevin

import { MapPin, CheckCircle2, AlertCircle, Loader2, RefreshCcw } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { Button } from '@/components/ui/button';

function LocationConfirmationCard({
  status = 'idle',
  elapsed = 0,
  position,
  accuracy,
  error,
  isConfirmed,
  onConfirm,
  onRetry,
  onManualSelect,
}) {
  const { t } = useTranslation('common');
  const label = t(`locationCard.status.${status}.label`, {
    defaultValue: {
      idle: 'Localisation automatique prête',
      searching: 'Recherche de votre position…',
      success: 'Position détectée',
      error: 'Impossible de récupérer la position',
      denied: 'Permission GPS refusée',
      timeout: 'GPS trop long',
    }[status] || 'Localisation automatique prête',
  });

  const description = t(`locationCard.status.${status}.description`, {
    defaultValue: {
      idle: 'Le GPS attend votre enregistrement pour lancer la détection.',
      searching: 'Restez quelques secondes, nous capturons votre position automatiquement.',
      success: 'Confirmez ou ajustez si nécessaire avant de valider.',
      error: 'Relancez la détection ou sélectionnez manuellement sur la carte.',
      denied: 'Autorisez l’accès au GPS ou choisissez votre position manuellement.',
      timeout: 'Relancez ou sélectionnez manuellement la position.',
    }[status] || 'Le GPS attend votre enregistrement pour lancer la détection.',
  });

  const hasPosition = Boolean(position);

  return (
    <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-5 space-y-4">
      <div className="flex items-start gap-3">
        <div className="mt-1 rounded-full bg-primary-100 p-2">
          {status === 'searching' ? (
            <Loader2 className="h-5 w-5 text-primary-600 animate-spin" />
          ) : status === 'success' ? (
            <CheckCircle2 className="h-5 w-5 text-primary-600" />
          ) : status === 'error' || status === 'denied' || status === 'timeout' ? (
            <AlertCircle className="h-5 w-5 text-red-600" />
          ) : (
            <MapPin className="h-5 w-5 text-primary-600" />
          )}
        </div>
        <div className="flex-1">
          <p className="text-sm font-semibold text-neutral-900">{label}</p>
          <p className="text-sm text-neutral-600">{description}</p>
          {status === 'searching' && (
            <p className="text-xs text-neutral-500 mt-1">
              {t('locationCard.elapsed', {
                defaultValue: '{{count}}s écoulées',
                count: elapsed,
              })}
            </p>
          )}
          {error && (
            <p className="text-xs text-red-500 mt-1">{error.message}</p>
          )}
        </div>
      </div>

      <div className="rounded-xl border border-dashed border-neutral-300 bg-white p-4">
        {hasPosition ? (
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div>
              <p className="text-sm font-medium text-neutral-900">
                      {t('locationCard.coordinates', {
                        defaultValue: 'Lat {{lat}} · Lon {{lng}}',
                        lat: position.lat?.toFixed(5),
                        lng: position.lng?.toFixed(5),
                      })}
              </p>
              {accuracy && (
                <p className="text-xs text-neutral-500">
                        {t('locationCard.accuracy', {
                          defaultValue: 'Précision ~ {{meters}} m',
                          meters: Math.round(accuracy),
                        })}
                </p>
              )}
            </div>
            {isConfirmed && (
              <span className="inline-flex items-center rounded-full bg-success-50 px-3 py-1 text-xs font-medium text-success-700">
                <CheckCircle2 className="mr-1 h-3.5 w-3.5" />
                      {t('locationCard.confirmed', { defaultValue: 'Confirmé' })}
              </span>
            )}
          </div>
        ) : (
                <p className="text-sm text-neutral-500">
                  {t('locationCard.waiting', { defaultValue: 'En attente de coordonnées GPS…' })}
                </p>
        )}
      </div>

      <div className="flex flex-wrap gap-2">
        <Button
          type="button"
          onClick={onConfirm}
          disabled={!hasPosition || isConfirmed}
          className="flex-1 md:flex-none"
        >
          <CheckCircle2 className="mr-2 h-4 w-4" />
          {t('locationCard.actions.confirm', { defaultValue: 'Confirmer cette position' })}
        </Button>
        <Button
          type="button"
          variant="outline"
          onClick={onManualSelect}
          className="flex-1 md:flex-none"
        >
          <MapPin className="mr-2 h-4 w-4" />
          {t('locationCard.actions.manual', { defaultValue: 'Ajuster sur la carte' })}
        </Button>
        <Button
          type="button"
          variant="ghost"
          onClick={onRetry}
          className="flex-1 md:flex-none"
        >
          <RefreshCcw className="mr-2 h-4 w-4" />
          {t('locationCard.actions.retry', { defaultValue: 'Relancer le GPS' })}
        </Button>
      </div>
    </div>
  );
}

export default LocationConfirmationCard;


