// @generated by Cursor AI (Claude) — verified by Kevin Mendy

import { Link } from 'react-router-dom';

/**
 * Composant Logo de WattU
 * 
 * Utilisé dans :
 * - Header public (citoyens)
 * - Header agent
 * - Header admin
 * - Page de login
 * 
 * Props:
 * @param {string} [size='md'] - Taille du logo (sm, md, lg, xl)
 * @param {boolean} [withLink=true] - Si le logo doit être cliquable
 * @param {string} [linkTo='/'] - URL de destination du lien
 * @param {boolean} [withText=false] - Afficher le texte "WattU" (logo contient déjà le texte)
 * @param {string} [className=''] - Classes CSS additionnelles
 * 
 * @example
 * <Logo size="lg" withLink={false} />
 */
function Logo({ 
  size = 'md', 
  withLink = true, 
  linkTo = '/', 
  withText = false,
  className = '' 
}) {
  // Définir les tailles (hauteur du logo)
  const sizes = {
    sm: 'h-6',
    md: 'h-10',
    lg: 'h-12',
    xl: 'h-16'
  };

  const currentSize = sizes[size] || sizes.md;

  // Contenu du logo
  const LogoContent = () => (
    <div className={`flex items-center gap-3 ${className}`}>
      {/* Logo personnalisé */}
      <img 
        src="/logo wattumvp.jpg" 
        alt="WattU Logo" 
        className={`${currentSize} w-auto object-contain`}
      />
      
      {/* Texte "WattU" (optionnel si le logo ne contient pas déjà le texte) */}
      {withText && (
        <span className="font-bold text-2xl text-gray-900">
          Watt<span className="text-blue-600">U</span>
        </span>
      )}
    </div>
  );

  // Si cliquable, wrapper dans un Link
  if (withLink) {
    return (
      <Link 
        to={linkTo} 
        className="flex items-center hover:opacity-80 transition-opacity duration-200"
      >
        <LogoContent />
      </Link>
    );
  }

  // Sinon, retourner directement le contenu
  return <LogoContent />;
}

export default Logo;

