// @generated by Cursor AI (Claude) — verified by Kevin

import { useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { X, Camera, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import useImageUpload from '@/hooks/useImageUpload';

/**
 * Composant PhotoBottomSheet - Bottom sheet pour sélectionner une photo
 * 
 * S'affiche comme un modal qui remonte depuis le bas de l'écran
 * Permet de sélectionner une photo optionnelle pour le signalement
 * 
 * @param {Object} props
 * @param {boolean} props.open - Si le bottom sheet est ouvert
 * @param {Function} props.onClose - Callback quand l'utilisateur ferme le sheet
 * @param {Function} props.onPhotoSelected - Callback quand une photo est sélectionnée (File)
 * @param {Function} props.onSkip - Callback quand l'utilisateur choisit de passer cette étape
 * 
 * @example
 * <PhotoBottomSheet
 *   open={showPhotoSheet}
 *   onClose={() => setShowPhotoSheet(false)}
 *   onPhotoSelected={(file) => console.log('Photo sélectionnée:', file)}
 *   onSkip={() => setShowPhotoSheet(false)}
 * />
 */
function PhotoBottomSheet({ open, onClose, onPhotoSelected, onSkip }) {
  const { t } = useTranslation('common');
  const {
    imageFile,
    imagePreview,
    isCompressing,
    error: imageError,
    selectImage,
    removeImage,
  } = useImageUpload();

  // Note: onPhotoSelected n'est appelé que manuellement via le bouton "Confirmer"
  // pour éviter les doubles appels

  // Empêcher le scroll du body quand le sheet est ouvert
  useEffect(() => {
    if (open) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [open]);

  if (!open) return null;

  return (
    <>
      {/* Overlay */}
      <div
        className="fixed inset-0 bg-black/50 z-40 animate-in fade-in-0"
        onClick={onClose}
        aria-hidden="true"
      />

      {/* Bottom Sheet */}
      <div
        className="fixed bottom-0 left-0 right-0 z-50 bg-white rounded-t-2xl shadow-2xl animate-in slide-in-from-bottom duration-300 max-h-[90vh] overflow-y-auto"
        role="dialog"
        aria-modal="true"
        aria-labelledby="photo-sheet-title"
      >
        {/* Handle bar */}
        <div className="flex justify-center pt-3 pb-2">
          <div className="w-12 h-1.5 bg-neutral-300 rounded-full" />
        </div>

        {/* Header */}
        <div className="flex items-center justify-between px-6 pb-4 border-b border-neutral-200">
          <h2
            id="photo-sheet-title"
            className="text-lg font-semibold text-neutral-900"
          >
            {t('photo_sheet.title', { defaultValue: 'Ajouter une photo' })}
          </h2>
          <button
            onClick={onClose}
            className="p-2 rounded-full hover:bg-neutral-100 transition-colors"
            aria-label={t('buttons.close', { defaultValue: 'Fermer' })}
          >
            <X className="w-5 h-5 text-neutral-600" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-4">
          <p className="text-sm text-neutral-600">
            {t('photo_sheet.description', {
              defaultValue: 'Prenez une photo pour illustrer le problème (optionnel)',
            })}
          </p>

          {/* Photo upload area */}
          {!imagePreview ? (
            <label
              htmlFor="photo-sheet-input"
              className="block w-full p-8 border-2 border-dashed border-neutral-300 rounded-xl hover:border-primary-500 transition-colors cursor-pointer"
            >
              <div className="flex flex-col items-center gap-3">
                {isCompressing ? (
                  <>
                    <Loader2 className="w-12 h-12 text-primary-600 animate-spin" />
                    <p className="text-sm text-primary-600 font-medium">
                      {t('form.compressing', { defaultValue: 'Compression en cours...' })}
                    </p>
                  </>
                ) : (
                  <>
                    <Camera className="w-12 h-12 text-neutral-400" />
                    <p className="text-sm text-neutral-600 font-medium">
                      {t('photo_sheet.select_photo', {
                        defaultValue: 'Touchez pour prendre une photo',
                      })}
                    </p>
                    <p className="text-xs text-neutral-500">
                      JPEG, PNG, WebP (max 5MB)
                    </p>
                  </>
                )}
              </div>
              <input
                id="photo-sheet-input"
                type="file"
                accept="image/*"
                capture="environment"
                onChange={selectImage}
                className="hidden"
                disabled={isCompressing}
              />
            </label>
          ) : (
            <div className="relative">
              <img
                src={imagePreview}
                alt="Preview"
                className="w-full h-64 object-cover rounded-xl border-2 border-neutral-200"
              />
              <button
                type="button"
                onClick={removeImage}
                className="absolute top-3 right-3 p-2 bg-red-500 text-white rounded-full hover:bg-red-600 transition-colors shadow-lg"
                aria-label={t('photo_sheet.remove_photo', {
                  defaultValue: 'Supprimer la photo',
                })}
              >
                <X className="w-4 h-4" />
              </button>
            </div>
          )}

          {imageError && (
            <div className="p-3 rounded-lg bg-red-50 border border-red-200">
              <p className="text-sm text-red-700">{imageError.message}</p>
            </div>
          )}

          {/* Actions */}
          <div className="flex flex-col gap-3 pt-4">
            {imagePreview && (
              <Button
                onClick={() => {
                  if (imageFile) {
                    onPhotoSelected?.(imageFile);
                  }
                  onClose();
                }}
                className="w-full"
                disabled={isCompressing}
              >
                {t('photo_sheet.confirm', {
                  defaultValue: 'Confirmer la photo',
                })}
              </Button>
            )}
            <Button
              variant="outline"
              onClick={() => {
                removeImage();
                onSkip?.();
                onClose();
              }}
              className="w-full"
              disabled={isCompressing}
            >
                {imagePreview
                ? t('photo_sheet.skip', {
                    defaultValue: 'Passer cette étape',
                  })
                : t('photo_sheet.skip_no_photo', {
                    defaultValue: 'Continuer sans photo',
                  })}
            </Button>
          </div>
        </div>
      </div>
    </>
  );
}

export default PhotoBottomSheet;

