// @generated by Cursor AI (Claude) — verified by Kevin

import { Navigate, useLocation } from 'react-router-dom';
import { useAuth } from '@/context/AuthContext';
import { Loader2 } from 'lucide-react';

/**
 * Composant de protection des routes pour les citoyens
 * 
 * Rôle :
 * - Vérifie si l'utilisateur est authentifié (même sans role, car citoyens ont role = null)
 * - Si OUI → Affiche le contenu de la route (children)
 * - Si NON → Redirige vers /welcome (page d'inscription)
 * 
 * Différence avec RequireAuth :
 * - RequireAuth redirige vers /login (pour agents/admins)
 * - RequireCitizenAuth redirige vers /welcome (pour citoyens)
 * - Accepte les utilisateurs avec role = null (citoyens)
 * - Rejette les utilisateurs avec role = 'agent' ou 'admin' (doivent aller sur /login)
 * 
 * Usage dans App.jsx :
 * <Route element={<RequireCitizenAuth><PublicLayout /></RequireCitizenAuth>}>
 *   <Route path="/" element={<HomePage />} />
 * </Route>
 * 
 * @param {Object} props
 * @param {ReactNode} props.children - Composants à protéger
 */
function RequireCitizenAuth({ children }) {
  const { isAuthenticated, hasSession, user, isCitizen, isAgent, isAdmin, loading, isVoiceAuthenticated } = useAuth();
  const location = useLocation();

  // ═══════════════════════════════════════════════════════════
  // ÉTAT 1 : En cours de vérification (loading)
  // ═══════════════════════════════════════════════════════════

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-neutral-50">
        <div className="flex flex-col items-center gap-4">
          <Loader2 className="h-12 w-12 animate-spin text-primary-600" />
          <p className="text-sm text-neutral-600">
            Vérification de la session...
          </p>
        </div>
      </div>
    );
  }

  // ═══════════════════════════════════════════════════════════
  // ÉTAT 2 : Authentifié via voix (Voice User) ✅
  // ═══════════════════════════════════════════════════════════
  // 
  // Les utilisateurs vocaux sont authentifiés via localStorage
  // Pas besoin de session Supabase

  if (isVoiceAuthenticated()) {
    return children;
  }

  // ═══════════════════════════════════════════════════════════
  // ÉTAT 3 : Non authentifié (pas de session Supabase) → Rediriger vers /welcome
  // ═══════════════════════════════════════════════════════════
  // 
  // IMPORTANT : On vérifie hasSession (session Supabase) et non user
  // car user peut être null même si session existe (profil pas encore créé)
  // Mais pour les citoyens, on a besoin du profil pour vérifier le role

  if (!hasSession || !isAuthenticated) {
    // Pas de session Supabase → Utilisateur non connecté
    return (
      <Navigate 
        to="/welcome" 
        state={{ from: location }} 
        replace 
      />
    );
  }

  // ═══════════════════════════════════════════════════════════
  // ÉTAT 4 : Authentifié mais avec role agent/admin → Rediriger vers leur dashboard
  // ═══════════════════════════════════════════════════════════
  // 
  // Les agents/admins ne doivent pas accéder aux pages citoyennes
  // Ils doivent utiliser leur propre interface

  if (isAgent || isAdmin) {
    const redirectPath = isAdmin 
      ? '/admin/dashboard' 
      : '/agent/dashboard';
    
    return (
      <Navigate 
        to={redirectPath} 
        replace 
      />
    );
  }

  // ═══════════════════════════════════════════════════════════
  // ÉTAT 5 : Authentifié en tant que citoyen (role = 'citizen') ✅
  // ═══════════════════════════════════════════════════════════
  // 
  // hasSession = true ET role = 'citizen'
  // → Utilisateur connecté en tant que citoyen
  // → Accès autorisé aux pages citoyennes

  if (isCitizen) {
    return children;
  }

  // ═══════════════════════════════════════════════════════════
  // ÉTAT 6 : Cas de fallback (ne devrait pas arriver)
  // ═══════════════════════════════════════════════════════════
  // 
  // Si on arrive ici, c'est qu'il y a une session mais le profil
  // n'est pas encore chargé ou a un problème
  // → Rediriger vers /welcome pour forcer la reconnexion

  return (
    <Navigate 
      to="/welcome" 
      state={{ from: location }} 
      replace 
    />
  );
}

export default RequireCitizenAuth;

