// @generated by Cursor AI (Claude) — verified by Kevin

import { useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { BarChart3, Loader2 } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import {
  BarChart,
  Bar,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer
} from 'recharts';

/**
 * Graphique en barres pour la répartition par commune (top 10)
 * 
 * @param {Object} props
 * @param {Array} props.byCommune - Répartition par commune [{ commune_id, commune_name, count }, ...]
 * @param {boolean} [props.loading] - État de chargement
 * 
 * @example
 * <CommuneDistributionChart byCommune={[{ commune_name: 'Dakar', count: 50 }, ...]} />
 */
function CommuneDistributionChart({ byCommune = [], loading = false }) {
  const { t } = useTranslation('admin');

  // Couleurs pour les barres (dégradé de bleu)
  const COLORS = [
    '#3b82f6', // blue-500
    '#60a5fa', // blue-400
    '#93c5fd', // blue-300
    '#bfdbfe', // blue-200
    '#dbeafe', // blue-100
    '#2563eb', // blue-600
    '#1d4ed8', // blue-700
    '#1e40af', // blue-800
    '#1e3a8a', // blue-900
    '#172554', // blue-950
  ];

  // Préparer les données pour le graphique (mémorisé)
  const data = useMemo(() => {
    return byCommune.map((item, index) => ({
      name: item.commune_name || 'Commune inconnue',
      value: item.count || 0,
      index: index
    }));
  }, [byCommune]);

  if (loading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <BarChart3 className="w-5 h-5 text-primary-600" />
            {t('analytics.by_commune.title', { defaultValue: 'Répartition par commune' })}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="h-80 bg-neutral-100 rounded-lg animate-pulse" />
        </CardContent>
      </Card>
    );
  }

  if (data.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <BarChart3 className="w-5 h-5 text-primary-600" />
            {t('analytics.by_commune.title', { defaultValue: 'Répartition par commune' })}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-neutral-500 text-center py-12">
            {t('analytics.no_data', { defaultValue: 'Aucune donnée disponible' })}
          </p>
        </CardContent>
      </Card>
    );
  }

  const CustomTooltip = ({ active, payload }) => {
    if (active && payload && payload.length) {
      const data = payload[0].payload;
      return (
        <div className="bg-white border-2 border-primary-200 rounded-lg p-3 shadow-lg">
          <p className="text-sm font-medium text-neutral-900">{data.name}</p>
          <p className="text-lg font-bold text-primary-600">
            {data.value} signalement{data.value > 1 ? 's' : ''}
          </p>
        </div>
      );
    }
    return null;
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <BarChart3 className="w-5 h-5 text-primary-600" />
          {t('analytics.by_commune.title', { defaultValue: 'Répartition par commune' })}
        </CardTitle>
        <p className="text-sm text-neutral-500 mt-1">
          {t('analytics.by_commune.subtitle', { defaultValue: 'Top 10 communes' })}
        </p>
      </CardHeader>
      <CardContent>
        <ResponsiveContainer width="100%" height={320}>
          <BarChart data={data} margin={{ top: 5, right: 20, left: 0, bottom: 60 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
            <XAxis 
              dataKey="name" 
              tick={{ fontSize: 11 }}
              stroke="#6b7280"
              angle={-45}
              textAnchor="end"
              height={80}
            />
            <YAxis 
              tick={{ fontSize: 12 }}
              stroke="#6b7280"
              allowDecimals={false}
            />
            <Tooltip content={<CustomTooltip />} />
            <Bar dataKey="value" radius={[8, 8, 0, 0]}>
              {data.map((entry, index) => (
                <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
              ))}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </CardContent>
    </Card>
  );
}

export default CommuneDistributionChart;

