// @generated by Cursor AI (Claude) — verified by Kevin Mendy
import { useState, useEffect, useCallback } from 'react';
import * as reportService from '@/services/reportService';
import * as reportApi from '@/api/reportApi';

/**
 * Hook personnalisé pour gérer les signalements d'un agent
 * 
 * Fonctionnalités :
 * - Récupérer les signalements de la commune de l'agent (via RLS)
 * - Appliquer des filtres (status, type, priority)
 * - Mettre à jour le statut d'un signalement
 * - Mettre à jour la priorité d'un signalement
 * - Rafraîchir la liste
 * 
 * @param {string} communeId - UUID de la commune de l'agent
 * @param {Object} [filters={}] - Filtres optionnels
 * @param {string} [filters.status] - Filtrer par statut
 * @param {string} [filters.type] - Filtrer par type
 * @param {string} [filters.priority] - Filtrer par priorité
 * 
 * @returns {{
 *   reports: Array,
 *   loading: boolean,
 *   error: string|null,
 *   updateStatus: Function,
 *   updatePriority: Function,
 *   refetch: Function
 * }}
 * 
 * @example
 * function ReportList() {
 *   const { user } = useAuth();
 *   const { reports, loading, updateStatus } = useAgentReports(user.commune_id);
 * 
 *   return (
 *     <div>
 *       {reports.map(report => (
 *         <div key={report.id}>
 *           <h3>{report.type}</h3>
 *           <button onClick={() => updateStatus(report.id, 'in_progress')}>
 *             Prendre en charge
 *           </button>
 *         </div>
 *       ))}
 *     </div>
 *   );
 * }
 */
export function useAgentReports(communeId, filters = {}) {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  /**
   * Récupérer les signalements de la commune avec filtres
   */
  const fetchReports = useCallback(async () => {
    if (!communeId) {
      setError('ID de commune requis');
      setLoading(false);
      return;
    }

    try {
      setLoading(true);
      setError(null);

      // Options de requête
      const options = {
        commune_id: communeId,
        limit: 100,
        orderBy: 'created_at',
        ascending: false // Plus récents en premier
      };

      // Appliquer les filtres
      if (filters.status) {
        options.status = filters.status;
      }
      if (filters.type) {
        options.type = filters.type;
      }
      if (filters.priority) {
        options.priority = filters.priority;
      }

      const { data, error: fetchError } = await reportService.getAllReports(options);

      if (fetchError) {
        setError(fetchError.message || 'Erreur lors de la récupération des signalements');
        setReports([]);
      } else {
        setReports(data || []);
        setError(null);
      }

    } catch (err) {
      console.error('❌ Erreur useAgentReports:', err);
      setError(err.message || 'Une erreur est survenue');
      setReports([]);
    } finally {
      setLoading(false);
    }
  }, [communeId, filters.status, filters.type, filters.priority]);

  /**
   * Mettre à jour le statut d'un signalement
   * 
   * @param {string} reportId - UUID du signalement
   * @param {string} newStatus - Nouveau statut (pending, in_progress, resolved, rejected)
   * @returns {Promise<{success: boolean, error: Object|null}>}
   */
  const updateStatus = useCallback(async (reportId, newStatus) => {
    try {
      console.log(`🔄 Mise à jour du statut: ${reportId} → ${newStatus}`);

      const { data, error: updateError } = await reportApi.updateReportStatus(reportId, newStatus);

      if (updateError) {
        console.error('❌ Erreur mise à jour statut:', updateError);
        return { success: false, error: updateError };
      }

      console.log('✅ Statut mis à jour avec succès');

      // Rafraîchir la liste des signalements
      await fetchReports();

      return { success: true, error: null };

    } catch (err) {
      console.error('❌ Erreur updateStatus:', err);
      return {
        success: false,
        error: {
          message: err.message || 'Erreur lors de la mise à jour du statut',
          code: 'UPDATE_ERROR'
        }
      };
    }
  }, [fetchReports]);

  /**
   * Mettre à jour la priorité d'un signalement
   * 
   * @param {string} reportId - UUID du signalement
   * @param {string} newPriority - Nouvelle priorité (low, normal, high, urgent)
   * @returns {Promise<{success: boolean, error: Object|null}>}
   */
  const updatePriority = useCallback(async (reportId, newPriority) => {
    try {
      console.log(`⚡ Mise à jour de la priorité: ${reportId} → ${newPriority}`);

      const { data, error: updateError } = await reportApi.updateReportPriority(reportId, newPriority);

      if (updateError) {
        console.error('❌ Erreur mise à jour priorité:', updateError);
        return { success: false, error: updateError };
      }

      console.log('✅ Priorité mise à jour avec succès');

      // Rafraîchir la liste des signalements
      await fetchReports();

      return { success: true, error: null };

    } catch (err) {
      console.error('❌ Erreur updatePriority:', err);
      return {
        success: false,
        error: {
          message: err.message || 'Erreur lors de la mise à jour de la priorité',
          code: 'UPDATE_ERROR'
        }
      };
    }
  }, [fetchReports]);

  /**
   * Charger les signalements au montage du composant et quand les filtres changent
   */
  useEffect(() => {
    fetchReports();
  }, [fetchReports]);

  return {
    reports,
    loading,
    error,
    updateStatus,
    updatePriority,
    refetch: fetchReports
  };
}

export default useAgentReports;

