// @generated by Cursor AI (Claude) — verified by Kevin

import { useState, useEffect, useCallback, useRef } from 'react';
import { GoogleGenAI } from '@google/genai';
import geminiConfig from '@/config/gemini';

/**
 * Custom Hook pour la synthèse vocale avec Gemini TTS
 * 
 * Utilise l'API Gemini TTS pour convertir du texte en parole avec des voix naturelles.
 * Remplace le Web Speech API par Gemini pour une meilleure qualité vocale.
 * 
 * Fonctionnalités :
 * - Parler un texte avec une voix Gemini configurée
 * - Arrêter la parole en cours
 * - Gérer les erreurs (API non disponible, erreurs réseau)
 * - Détecter quand la parole est terminée
 * - Support multilingue (FR, Wolof)
 * 
 * @param {Object} [options] - Options du hook
 * @param {string} [options.language='fr-FR'] - Langue de la voix
 * @param {string} [options.voiceName='Kore'] - Nom de la voix Gemini (voir docs pour les 30 voix disponibles)
 * 
 * @returns {Object} État et fonctions de synthèse vocale
 * @property {boolean} isSpeaking - true si la synthèse vocale est en cours
 * @property {boolean} isSupported - true si Gemini TTS est disponible
 * @property {Object|null} error - Erreur éventuelle
 * @property {function} speak - Parler un texte
 * @property {function} stop - Arrêter la parole en cours
 * 
 * @example
 * const { speak, stop, isSpeaking, isSupported } = useGeminiTextToSpeech({ language: 'fr-FR', voiceName: 'Kore' });
 * 
 * // Parler un texte
 * speak("Bonjour ! Je vais vous aider à créer votre compte.");
 * 
 * // Arrêter
 * if (isSpeaking) {
 *   stop();
 * }
 */
export function useGeminiTextToSpeech(options = {}) {
  const {
    language = 'fr-FR',
    voiceName = 'Kore', // Voix par défaut : Kore (ferme, professionnelle)
  } = options;

  const [isSpeaking, setIsSpeaking] = useState(false);
  const [isSupported, setIsSupported] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false); // État pour la génération audio
  const [error, setError] = useState(null);

  const audioContextRef = useRef(null);
  const audioSourceRef = useRef(null);
  const onEndCallbackRef = useRef(null);
  const onStartCallbackRef = useRef(null);
  const geminiClientRef = useRef(null);

  /**
   * Initialiser le client Gemini et vérifier la disponibilité
   */
  useEffect(() => {
    console.log('🔧 Initialisation Gemini TTS...', {
      enabled: geminiConfig.enabled,
      hasApiKey: !!geminiConfig.apiKey,
      apiKeyLength: geminiConfig.apiKey?.length || 0,
    });

    if (!geminiConfig.enabled || !geminiConfig.apiKey) {
      console.warn('⚠️ Gemini TTS non configuré:', {
        enabled: geminiConfig.enabled,
        hasApiKey: !!geminiConfig.apiKey,
      });
      setIsSupported(false);
      setError({
        code: 'NOT_SUPPORTED',
        message: 'Gemini TTS n\'est pas configuré. Vérifiez VITE_GEMINI_API_KEY dans .env.local',
      });
      return;
    }

    try {
      // Dans le navigateur, GoogleGenAI attend un objet avec apiKey
      geminiClientRef.current = new GoogleGenAI({ apiKey: geminiConfig.apiKey });
      setIsSupported(true);
      setError(null);
      console.log('✅ Gemini TTS initialisé avec succès');
    } catch (err) {
      console.error('❌ Erreur initialisation Gemini TTS:', err);
      setIsSupported(false);
      setError({
        code: 'INIT_ERROR',
        message: 'Erreur lors de l\'initialisation de Gemini TTS',
        originalError: err,
      });
    }
  }, []);

  /**
   * Créer un AudioContext pour jouer l'audio
   */
  const getAudioContext = useCallback(() => {
    if (!audioContextRef.current) {
      const AudioContextClass = window.AudioContext || window.webkitAudioContext;
      if (AudioContextClass) {
        audioContextRef.current = new AudioContextClass();
      }
    }
    return audioContextRef.current;
  }, []);

  /**
   * Convertir les données PCM en AudioBuffer et les jouer
   */
  const playAudioBuffer = useCallback(async (pcmData, onEnd, onStart) => {
    try {
      const audioContext = getAudioContext();
      if (!audioContext) {
        throw new Error('AudioContext non disponible');
      }

      // Les données PCM de Gemini sont en format 24kHz, 16-bit, mono
      const sampleRate = 24000;
      const channels = 1;
      const sampleWidth = 2; // 16-bit = 2 bytes

      // Créer un AudioBuffer
      const frameCount = pcmData.length / sampleWidth;
      const audioBuffer = audioContext.createBuffer(channels, frameCount, sampleRate);

      // Convertir les données PCM (Int16Array) en Float32Array pour Web Audio API
      const channelData = audioBuffer.getChannelData(0);
      
      // Créer un DataView pour lire les données Int16 (little-endian)
      const dataView = new DataView(pcmData.buffer, pcmData.byteOffset, pcmData.length);

      for (let i = 0; i < frameCount; i++) {
        // Lire un Int16 (little-endian) depuis les données PCM
        const int16Value = dataView.getInt16(i * sampleWidth, true); // true = little-endian
        // Convertir Int16 (-32768 à 32767) en Float32 (-1.0 à 1.0)
        channelData[i] = int16Value / 32768.0;
      }

      // Créer une source audio
      const source = audioContext.createBufferSource();
      source.buffer = audioBuffer;
      source.connect(audioContext.destination);

      // Stocker la référence pour pouvoir l'arrêter
      audioSourceRef.current = source;

      // Gérer les événements
      source.onended = () => {
        setIsSpeaking(false);
        audioSourceRef.current = null;
        console.log('✅ Synthèse vocale Gemini terminée');

        if (onEndCallbackRef.current) {
          onEndCallbackRef.current();
          onEndCallbackRef.current = null;
        }
        onStartCallbackRef.current = null;
      };

      // Appeler onStart avant de jouer
      if (onStartCallbackRef.current) {
        onStartCallbackRef.current();
        onStartCallbackRef.current = null;
      }

      // Démarrer la lecture
      source.start(0);
      setIsSpeaking(true);
      console.log('🔊 Synthèse vocale Gemini démarrée');

    } catch (err) {
      console.error('❌ Erreur lecture audio:', err);
      setIsSpeaking(false);
      setError({
        code: 'AUDIO_PLAYBACK_ERROR',
        message: 'Erreur lors de la lecture de l\'audio',
        originalError: err,
      });

      if (onEndCallbackRef.current) {
        onEndCallbackRef.current();
        onEndCallbackRef.current = null;
      }
      onStartCallbackRef.current = null;
    }
  }, [getAudioContext]);

  /**
   * Parler un texte avec Gemini TTS
   * 
   * @param {string} text - Texte à prononcer
   * @param {Object} [overrides] - Options à surcharger (language, voiceName)
   * @param {Function} [onEnd] - Callback appelé quand la parole est terminée
   * @param {Function} [onStart] - Callback appelé quand la parole commence
   * 
   * @returns {Promise<void>}
   */
  const speak = useCallback(async (text, overrides = {}, onEnd = null, onStart = null) => {
    console.log('📢 Appel speak()', {
      text: text?.substring(0, 50) + '...',
      isSupported,
      hasClient: !!geminiClientRef.current,
    });

    if (!isSupported || !geminiClientRef.current) {
      console.error('❌ Gemini TTS non disponible:', {
        isSupported,
        hasClient: !!geminiClientRef.current,
      });
      setError({
        code: 'NOT_SUPPORTED',
        message: 'Gemini TTS n\'est pas disponible',
      });
      return;
    }

    if (!text || typeof text !== 'string' || text.trim() === '') {
      setError({
        code: 'INVALID_TEXT',
        message: 'Le texte à prononcer ne peut pas être vide',
      });
      return;
    }

    try {
      // Arrêter toute parole en cours
      stop();

      // Stocker les callbacks
      onEndCallbackRef.current = onEnd;
      onStartCallbackRef.current = onStart;

      setError(null);

      const client = geminiClientRef.current;
      const finalVoiceName = overrides.voiceName || voiceName;
      const finalLanguage = overrides.language || language;

      console.log('🎤 Génération audio Gemini TTS:', {
        text: text.substring(0, 50) + '...',
        voice: finalVoiceName,
        language: finalLanguage,
      });

      // Indiquer que la génération est en cours
      setIsGenerating(true);
      const generationStartTime = Date.now();

      // Appeler Gemini TTS API
      const response = await client.models.generateContent({
        model: 'gemini-2.5-flash-preview-tts', // Modèle TTS Gemini
        contents: [{ parts: [{ text: text }] }],
        config: {
          responseModalities: ['AUDIO'],
          speechConfig: {
            voiceConfig: {
              prebuiltVoiceConfig: { voiceName: finalVoiceName },
            },
          },
        },
      });

      // Calculer le temps de génération
      const generationTime = Date.now() - generationStartTime;
      console.log(`⏱️ Génération audio terminée en ${generationTime}ms`);

      // Extraire les données audio
      const audioData = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
      
      if (!audioData) {
        console.error('❌ Structure de réponse inattendue:', JSON.stringify(response, null, 2));
        setIsGenerating(false);
        throw new Error('Aucune donnée audio retournée par Gemini TTS. Vérifiez la structure de la réponse.');
      }
      
      console.log('✅ Données audio reçues:', {
        dataLength: audioData.length,
        generationTime: `${generationTime}ms`,
      });

      // La génération est terminée, on va maintenant jouer l'audio
      setIsGenerating(false);

      // Convertir les données base64 en ArrayBuffer (navigateur)
      const binaryString = atob(audioData);
      const bytes = new Uint8Array(binaryString.length);
      for (let i = 0; i < binaryString.length; i++) {
        bytes[i] = binaryString.charCodeAt(i);
      }

      // Jouer l'audio
      await playAudioBuffer(bytes, onEnd, onStart);

    } catch (err) {
      console.error('❌ Erreur synthèse vocale Gemini:', err);
      setIsSpeaking(false);
      setIsGenerating(false);
      setError({
        code: 'SPEECH_ERROR',
        message: err.message || 'Erreur lors de la synthèse vocale Gemini',
        originalError: err,
      });

      if (onEndCallbackRef.current) {
        onEndCallbackRef.current();
        onEndCallbackRef.current = null;
      }
      onStartCallbackRef.current = null;
    }
  }, [isSupported, voiceName, language, playAudioBuffer]);

  /**
   * Arrêter la parole en cours
   */
  const stop = useCallback(() => {
    if (audioSourceRef.current) {
      try {
        audioSourceRef.current.stop();
        audioSourceRef.current = null;
      } catch (err) {
        // Ignorer les erreurs si la source est déjà arrêtée
      }
    }

    setIsSpeaking(false);
    onEndCallbackRef.current = null;
    onStartCallbackRef.current = null;
    console.log('⏹️ Synthèse vocale Gemini arrêtée');
  }, []);

  /**
   * Nettoyer lors du démontage
   */
  useEffect(() => {
    return () => {
      stop();
      if (audioContextRef.current) {
        audioContextRef.current.close().catch(() => {});
      }
    };
  }, [stop]);

  return {
    isSpeaking,
    isGenerating, // Nouvel état : génération en cours
    isSupported,
    error,
    speak,
    stop,
    // Note: pause et resume ne sont pas supportés par Gemini TTS
    pause: () => {}, // Pas de pause pour Gemini TTS
    resume: () => {}, // Pas de resume pour Gemini TTS
  };
}

export default useGeminiTextToSpeech;

