// @generated by Cursor AI (Claude) — verified by Kevin Mendy
import { useState, useCallback } from 'react';
import * as reportService from '@/services/reportService';

/**
 * Custom Hook pour la gestion d'upload d'images
 * 
 * Fonctionnalités :
 * - Sélection de fichier image
 * - Preview de l'image avant upload
 * - Compression automatique
 * - Validation (type, taille)
 * - Suppression/Réinitialisation
 * 
 * @returns {Object} État et fonctions d'upload
 * @property {File|null} imageFile - Fichier image sélectionné
 * @property {string|null} imagePreview - URL de preview de l'image
 * @property {boolean} isCompressing - true si compression en cours
 * @property {Object|null} error - Erreur éventuelle
 * @property {function} selectImage - Sélectionner une image depuis un input
 * @property {function} removeImage - Supprimer l'image sélectionnée
 * @property {function} resetState - Réinitialiser tout l'état
 * 
 * @example
 * const { imageFile, imagePreview, error, selectImage, removeImage } = useImageUpload();
 * 
 * <input type="file" accept="image/*" onChange={selectImage} />
 * {imagePreview && <img src={imagePreview} alt="Preview" />}
 * {error && <p>{error.message}</p>}
 * <button onClick={removeImage}>Supprimer</button>
 */
export function useImageUpload() {
  const [imageFile, setImageFile] = useState(null);
  const [imagePreview, setImagePreview] = useState(null);
  const [isCompressing, setIsCompressing] = useState(false);
  const [error, setError] = useState(null);

  /**
   * Sélectionner une image depuis un input file
   * 
   * @param {Event} event - Event du input file
   * @returns {Promise<void>}
   */
  const selectImage = useCallback(async (event) => {
    try {
      setError(null);

      const file = event.target.files?.[0];
      if (!file) {
        return;
      }

      console.log(`📷 Image sélectionnée: ${file.name} (${(file.size / 1024).toFixed(2)}KB)`);

      // Validation 1: Type MIME
      const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'];
      if (!allowedTypes.includes(file.type)) {
        const errorObj = {
          code: 'INVALID_TYPE',
          message: 'Type de fichier non autorisé. Formats acceptés: JPEG, PNG, WebP'
        };
        setError(errorObj);
        console.error('❌', errorObj.message);
        return;
      }

      // Validation 2: Taille max 5MB (avant compression)
      const maxSize = 5 * 1024 * 1024; // 5MB
      if (file.size > maxSize) {
        const errorObj = {
          code: 'FILE_TOO_LARGE',
          message: `Fichier trop volumineux (max 5MB). Taille actuelle: ${(file.size / 1024 / 1024).toFixed(2)}MB`
        };
        setError(errorObj);
        console.error('❌', errorObj.message);
        return;
      }

      // Compression de l'image
      setIsCompressing(true);
      console.log('🗜️ Compression en cours...');

      const compressionResult = await reportService.compressImage(file);

      setIsCompressing(false);

      if (compressionResult.error) {
        setError(compressionResult.error);
        console.error('❌ Erreur compression:', compressionResult.error.message);
        return;
      }

      const compressedFile = compressionResult.compressedFile;

      // Génération de la preview
      const previewUrl = URL.createObjectURL(compressedFile);

      setImageFile(compressedFile);
      setImagePreview(previewUrl);
      setError(null);

      console.log(`✅ Image prête: ${(compressedFile.size / 1024).toFixed(2)}KB (compression ${compressionResult.originalSize > 0 ? ((1 - compressedFile.size / compressionResult.originalSize) * 100).toFixed(1) : 0}%)`);

    } catch (err) {
      setIsCompressing(false);
      const errorObj = {
        code: 'UNEXPECTED_ERROR',
        message: err.message || 'Une erreur est survenue lors de la sélection de l\'image'
      };
      setError(errorObj);
      console.error('❌ Erreur inattendue selectImage:', err);
    }
  }, []);

  /**
   * Supprimer l'image sélectionnée et révoquer la preview
   */
  const removeImage = useCallback(() => {
    if (imagePreview) {
      URL.revokeObjectURL(imagePreview);
    }

    setImageFile(null);
    setImagePreview(null);
    setError(null);
    setIsCompressing(false);

    console.log('🗑️ Image supprimée');
  }, [imagePreview]);

  /**
   * Réinitialiser tout l'état du hook
   */
  const resetState = useCallback(() => {
    removeImage();
  }, [removeImage]);

  /**
   * Vérifier si une image est sélectionnée
   * 
   * @returns {boolean}
   */
  const hasImage = useCallback(() => {
    return imageFile !== null;
  }, [imageFile]);

  /**
   * Obtenir les informations sur l'image sélectionnée
   * 
   * @returns {Object|null}
   */
  const getImageInfo = useCallback(() => {
    if (!imageFile) {
      return null;
    }

    return {
      name: imageFile.name,
      size: imageFile.size,
      type: imageFile.type,
      sizeInKB: (imageFile.size / 1024).toFixed(2),
      sizeInMB: (imageFile.size / 1024 / 1024).toFixed(2)
    };
  }, [imageFile]);

  return {
    imageFile,
    imagePreview,
    isCompressing,
    error,
    selectImage,
    removeImage,
    resetState,
    hasImage,
    getImageInfo
  };
}

export default useImageUpload;

