// @generated by Cursor AI (Claude) — verified by Kevin

import { useState, useEffect, useCallback, useRef } from 'react';

/**
 * Custom Hook pour la reconnaissance vocale (Speech-to-Text)
 * 
 * Utilise l'API Web Speech API SpeechRecognition pour convertir la parole en texte.
 * 
 * Fonctionnalités :
 * - Démarrer/arrêter l'écoute
 * - Capturer le texte transcrit
 * - Gérer les permissions microphone
 * - Gérer les erreurs (permission refusée, API non supportée)
 * - Support multilingue (FR, Wolof)
 * 
 * @param {Object} [options] - Options du hook
 * @param {string} [options.language='fr-FR'] - Langue de reconnaissance
 * @param {boolean} [options.continuous=false] - Continuer l'écoute après une pause
 * @param {boolean} [options.interimResults=true] - Afficher les résultats intermédiaires
 * @param {number} [options.maxAlternatives=1] - Nombre d'alternatives de transcription
 * 
 * @returns {Object} État et fonctions de reconnaissance vocale
 * @property {string} transcript - Texte transcrit
 * @property {boolean} isListening - true si l'écoute est en cours
 * @property {boolean} isSupported - true si l'API est supportée
 * @property {Object|null} error - Erreur éventuelle
 * @property {function} startListening - Démarrer l'écoute
 * @property {function} stopListening - Arrêter l'écoute
 * @property {function} abort - Abandonner l'écoute
 * @property {function} clearTranscript - Effacer le transcript
 * 
 * @example
 * const { startListening, stopListening, transcript, isListening, error } = useSpeechRecognition();
 * 
 * // Démarrer l'écoute
 * startListening();
 * 
 * // Arrêter et récupérer le transcript
 * stopListening();
 * console.log(transcript); // "Amadou"
 */
export function useSpeechRecognition(options = {}) {
  const {
    language = 'fr-FR',
    continuous = false,
    interimResults = true,
    maxAlternatives = 1,
  } = options;

  const [transcript, setTranscript] = useState('');
  const [isListening, setIsListening] = useState(false);
  const [isSupported, setIsSupported] = useState(false);
  const [error, setError] = useState(null);

  const recognitionRef = useRef(null);
  const finalTranscriptRef = useRef('');

  /**
   * Vérifier si l'API SpeechRecognition est supportée
   */
  useEffect(() => {
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    
    if (SpeechRecognition) {
      try {
        const recognition = new SpeechRecognition();
        recognitionRef.current = recognition;
        setIsSupported(true);
        setError(null);
        console.log('✅ SpeechRecognition supporté');
      } catch (err) {
        setIsSupported(false);
        setError({
          code: 'INIT_ERROR',
          message: 'Impossible d\'initialiser la reconnaissance vocale',
          originalError: err,
        });
        console.error('❌ Erreur initialisation SpeechRecognition:', err);
      }
    } else {
      setIsSupported(false);
      setError({
        code: 'NOT_SUPPORTED',
        message: 'La reconnaissance vocale n\'est pas supportée par ce navigateur',
      });
      console.warn('⚠️ SpeechRecognition non supporté');
    }
  }, []);

  /**
   * Configurer la reconnaissance vocale
   */
  useEffect(() => {
    if (!recognitionRef.current) return;

    const recognition = recognitionRef.current;

    // Configurer les options
    recognition.lang = language;
    recognition.continuous = continuous;
    recognition.interimResults = interimResults;
    recognition.maxAlternatives = maxAlternatives;

    // Gérer les événements
    recognition.onstart = () => {
      setIsListening(true);
      setError(null);
      finalTranscriptRef.current = '';
      setTranscript('');
      console.log('🎤 Écoute démarrée');
    };

    recognition.onresult = (event) => {
      let interimTranscript = '';
      let finalTranscript = finalTranscriptRef.current;

      // Parcourir tous les résultats
      for (let i = event.resultIndex; i < event.results.length; i++) {
        const transcript = event.results[i][0].transcript;
        
        if (event.results[i].isFinal) {
          finalTranscript += transcript;
        } else {
          interimTranscript += transcript;
        }
      }

      finalTranscriptRef.current = finalTranscript;
      
      // Afficher le transcript final + interim
      if (interimResults) {
        setTranscript(finalTranscript + interimTranscript);
      } else {
        setTranscript(finalTranscript);
      }
    };

    recognition.onerror = (event) => {
      setIsListening(false);
      
      let errorMessage = 'Erreur lors de la reconnaissance vocale';
      let errorCode = 'RECOGNITION_ERROR';

      switch (event.error) {
        case 'no-speech':
          errorMessage = 'Aucune parole détectée. Veuillez réessayer.';
          errorCode = 'NO_SPEECH';
          break;
        case 'audio-capture':
          errorMessage = 'Aucun microphone détecté. Vérifiez votre matériel.';
          errorCode = 'NO_MICROPHONE';
          break;
        case 'not-allowed':
          errorMessage = 'L\'accès au microphone a été refusé. Veuillez autoriser l\'accès dans les paramètres.';
          errorCode = 'PERMISSION_DENIED';
          break;
        case 'network':
          errorMessage = 'Erreur réseau. Vérifiez votre connexion.';
          errorCode = 'NETWORK_ERROR';
          break;
        case 'aborted':
          // Ignorer les erreurs d'abandon (arrêt manuel)
          return;
        default:
          errorMessage = event.error || errorMessage;
      }

      setError({
        code: errorCode,
        message: errorMessage,
        originalError: event,
      });

      console.error('❌ Erreur reconnaissance vocale:', event.error);
    };

    recognition.onend = () => {
      setIsListening(false);
      console.log('⏹️ Écoute terminée');
    };

  }, [language, continuous, interimResults, maxAlternatives]);

  /**
   * Nettoyer lors du démontage
   */
  useEffect(() => {
    return () => {
      if (recognitionRef.current && isListening) {
        recognitionRef.current.abort();
      }
    };
  }, [isListening]);

  /**
   * Démarrer l'écoute
   * 
   * @param {Object} [overrides] - Options à surcharger
   * @returns {Promise<void>}
   */
  const startListening = useCallback(async (overrides = {}) => {
    if (!isSupported || !recognitionRef.current) {
      setError({
        code: 'NOT_SUPPORTED',
        message: 'La reconnaissance vocale n\'est pas supportée',
      });
      return;
    }

    try {
      // Vérifier la permission microphone
      try {
        const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
        // Libérer immédiatement (on a juste besoin de la permission)
        stream.getTracks().forEach(track => track.stop());
      } catch (permError) {
        if (permError.name === 'NotAllowedError' || permError.name === 'PermissionDeniedError') {
          setError({
            code: 'PERMISSION_DENIED',
            message: 'L\'accès au microphone a été refusé. Veuillez autoriser l\'accès dans les paramètres de votre navigateur.',
            originalError: permError,
          });
          return;
        }
        throw permError;
      }

      // Appliquer les overrides si fournis
      if (overrides.language) {
        recognitionRef.current.lang = overrides.language;
      }

      // Démarrer la reconnaissance
      recognitionRef.current.start();
      console.log('🎤 Démarrage de l\'écoute...');

    } catch (err) {
      setIsListening(false);
      setError({
        code: 'UNEXPECTED_ERROR',
        message: err.message || 'Une erreur inattendue est survenue',
        originalError: err,
      });
      console.error('❌ Erreur inattendue startListening:', err);
    }
  }, [isSupported]);

  /**
   * Arrêter l'écoute
   */
  const stopListening = useCallback(() => {
    if (recognitionRef.current && isListening) {
      recognitionRef.current.stop();
      console.log('⏹️ Arrêt de l\'écoute...');
    }
  }, [isListening]);

  /**
   * Abandonner l'écoute (arrêt immédiat)
   */
  const abort = useCallback(() => {
    if (recognitionRef.current && isListening) {
      recognitionRef.current.abort();
      setIsListening(false);
      console.log('🛑 Écoute abandonnée');
    }
  }, [isListening]);

  /**
   * Effacer le transcript
   */
  const clearTranscript = useCallback(() => {
    setTranscript('');
    finalTranscriptRef.current = '';
  }, []);

  return {
    transcript,
    isListening,
    isSupported,
    error,
    startListening,
    stopListening,
    abort,
    clearTranscript,
  };
}

export default useSpeechRecognition;

