// @generated by Cursor AI (Claude) — verified by Kevin

import { useState, useEffect, useCallback, useRef } from 'react';

/**
 * Custom Hook pour la synthèse vocale (Text-to-Speech)
 * 
 * Utilise l'API Web Speech API SpeechSynthesis pour convertir du texte en parole.
 * 
 * Fonctionnalités :
 * - Parler un texte avec une voix configurée
 * - Arrêter la parole en cours
 * - Gérer les erreurs (API non supportée, voix non disponible)
 * - Détecter quand la parole est terminée
 * - Support multilingue (FR, Wolof)
 * 
 * @param {Object} [options] - Options du hook
 * @param {string} [options.language='fr-FR'] - Langue de la voix
 * @param {number} [options.rate=1] - Vitesse de parole (0.1 à 10)
 * @param {number} [options.pitch=1] - Hauteur de la voix (0 à 2)
 * @param {number} [options.volume=1] - Volume (0 à 1)
 * 
 * @returns {Object} État et fonctions de synthèse vocale
 * @property {boolean} isSpeaking - true si la synthèse vocale est en cours
 * @property {boolean} isSupported - true si l'API est supportée
 * @property {Object|null} error - Erreur éventuelle
 * @property {function} speak - Parler un texte
 * @property {function} stop - Arrêter la parole en cours
 * @property {function} pause - Mettre en pause (si supporté)
 * @property {function} resume - Reprendre (si supporté)
 * 
 * @example
 * const { speak, stop, isSpeaking, isSupported } = useTextToSpeech({ language: 'fr-FR' });
 * 
 * // Parler un texte
 * speak("Bonjour ! Je vais vous aider à créer votre compte.");
 * 
 * // Arrêter
 * if (isSpeaking) {
 *   stop();
 * }
 */
export function useTextToSpeech(options = {}) {
  const {
    language = 'fr-FR',
    rate = 1,
    pitch = 1,
    volume = 1,
  } = options;

  const [isSpeaking, setIsSpeaking] = useState(false);
  const [isSupported, setIsSupported] = useState(false);
  const [error, setError] = useState(null);
  
  const utteranceRef = useRef(null);
  const onEndCallbackRef = useRef(null);
  const onStartCallbackRef = useRef(null);

  /**
   * Vérifier si l'API SpeechSynthesis est supportée
   */
  useEffect(() => {
    if ('speechSynthesis' in window) {
      setIsSupported(true);
      setError(null);
    } else {
      setIsSupported(false);
      setError({
        code: 'NOT_SUPPORTED',
        message: 'La synthèse vocale n\'est pas supportée par ce navigateur',
      });
    }
  }, []);

  /**
   * Nettoyer lors du démontage
   */
  useEffect(() => {
    return () => {
      if (utteranceRef.current && isSpeaking) {
        window.speechSynthesis.cancel();
      }
    };
  }, [isSpeaking]);

  /**
   * Parler un texte
   * 
   * @param {string} text - Texte à prononcer
   * @param {Object} [overrides] - Options à surcharger (language, rate, pitch, volume)
   * @param {Function} [onEnd] - Callback appelé quand la parole est terminée
   * @param {Function} [onStart] - Callback appelé quand la parole commence
   * 
   * @returns {Promise<void>}
   */
  const speak = useCallback(async (text, overrides = {}, onEnd = null, onStart = null) => {
    if (!isSupported) {
      setError({
        code: 'NOT_SUPPORTED',
        message: 'La synthèse vocale n\'est pas supportée',
      });
      return;
    }

    if (!text || typeof text !== 'string' || text.trim() === '') {
      setError({
        code: 'INVALID_TEXT',
        message: 'Le texte à prononcer ne peut pas être vide',
      });
      return;
    }

    try {
      // Arrêter toute parole en cours
      window.speechSynthesis.cancel();

      // Créer un nouvel utterance
      const utterance = new SpeechSynthesisUtterance(text);
      
      // Configurer les options
      utterance.lang = overrides.language || language;
      utterance.rate = overrides.rate !== undefined ? overrides.rate : rate;
      utterance.pitch = overrides.pitch !== undefined ? overrides.pitch : pitch;
      utterance.volume = overrides.volume !== undefined ? overrides.volume : volume;

      // Stocker la référence
      utteranceRef.current = utterance;
      onEndCallbackRef.current = onEnd;
      onStartCallbackRef.current = onStart;

      // Gérer les événements
      utterance.onstart = () => {
        setIsSpeaking(true);
        setError(null);
        console.log('🔊 Synthèse vocale démarrée:', text.substring(0, 50) + '...');
        
        // Appeler le callback onStart si fourni
        if (onStartCallbackRef.current) {
          onStartCallbackRef.current();
          onStartCallbackRef.current = null;
        }
      };

      utterance.onend = () => {
        setIsSpeaking(false);
        utteranceRef.current = null;
        onStartCallbackRef.current = null;
        console.log('✅ Synthèse vocale terminée');
        
        // Appeler le callback si fourni
        if (onEndCallbackRef.current) {
          onEndCallbackRef.current();
          onEndCallbackRef.current = null;
        }
      };

      utterance.onerror = (event) => {
        setIsSpeaking(false);
        utteranceRef.current = null;
        onStartCallbackRef.current = null;
        
        const errorMessage = event.error || 'Erreur lors de la synthèse vocale';
        setError({
          code: 'SPEECH_ERROR',
          message: errorMessage,
          originalError: event,
        });
        
        console.error('❌ Erreur synthèse vocale:', event);
        
        // Appeler le callback même en cas d'erreur
        if (onEndCallbackRef.current) {
          onEndCallbackRef.current();
          onEndCallbackRef.current = null;
        }
      };

      // Démarrer la synthèse vocale
      window.speechSynthesis.speak(utterance);

    } catch (err) {
      setIsSpeaking(false);
      setError({
        code: 'UNEXPECTED_ERROR',
        message: err.message || 'Une erreur inattendue est survenue',
        originalError: err,
      });
      console.error('❌ Erreur inattendue speak:', err);
    }
  }, [isSupported, language, rate, pitch, volume]);

  /**
   * Arrêter la parole en cours
   */
  const stop = useCallback(() => {
    if (window.speechSynthesis && isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
      utteranceRef.current = null;
      onEndCallbackRef.current = null;
      onStartCallbackRef.current = null;
      console.log('⏹️ Synthèse vocale arrêtée');
    }
  }, [isSpeaking]);

  /**
   * Mettre en pause (si supporté)
   */
  const pause = useCallback(() => {
    if (window.speechSynthesis && isSpeaking) {
      window.speechSynthesis.pause();
      console.log('⏸️ Synthèse vocale mise en pause');
    }
  }, [isSpeaking]);

  /**
   * Reprendre (si supporté)
   */
  const resume = useCallback(() => {
    if (window.speechSynthesis && !isSpeaking) {
      window.speechSynthesis.resume();
      console.log('▶️ Synthèse vocale reprise');
    }
  }, [isSpeaking]);

  return {
    isSpeaking,
    isSupported,
    error,
    speak,
    stop,
    pause,
    resume,
  };
}

export default useTextToSpeech;

