// @generated by Cursor AI (Claude) — verified by Kevin

import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Loader2, AlertCircle, CheckCircle } from 'lucide-react';
import { authService } from '@/services/authService';
import { authApi } from '@/api/authApi';
import { useAuth } from '@/context/AuthContext';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import OAuthProfileCompletionModal from '@/components/shared/OAuthProfileCompletionModal';

/**
 * Page de callback OAuth
 * 
 * Rôle :
 * - Gère le callback après connexion OAuth (Google, etc.)
 * - Vérifie la session créée par Supabase
 * - Crée le profil utilisateur si nouveau user
 * - Redirige vers le dashboard approprié
 * 
 * Route : /auth/callback
 * 
 * Flow :
 * 1. User clique "Se connecter avec Google" → Redirigé vers Google
 * 2. Google authentifie → Redirige vers /auth/callback?code=...
 * 3. Supabase traite le code → Crée session
 * 4. Cette page vérifie session → Crée profil si nécessaire → Redirige
 */
function AuthCallback() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const { checkAuth } = useAuth(); // Pour mettre à jour le contexte après OAuth

  const [status, setStatus] = useState('processing'); // 'processing' | 'success' | 'error' | 'needsProfile'
  const [error, setError] = useState(null);
  const [user, setUser] = useState(null);
  const [showProfileModal, setShowProfileModal] = useState(false);

  useEffect(() => {
    /**
     * Traiter le callback OAuth
     */
    const handleCallback = async () => {
      try {
        setStatus('processing');

        // Gérer le callback OAuth (vérifier session, créer profil si nécessaire)
        const result = await authService.handleOAuthCallback('fr');

        if (!result.success) {
          setError(result.error || 'Erreur lors de la connexion OAuth');
          setStatus('error');
          return;
        }

        // Succès : Mettre à jour le contexte AuthContext
        await checkAuth();

        // ⚠️ IMPORTANT : Récupérer le profil complet depuis la base de données
        // car result.user peut ne pas avoir toutes les colonnes (ex: age)
        let userProfile = result.user;
        
        // Si c'est un citoyen, récupérer le profil complet pour vérifier age et commune_id
        if (userProfile?.role === 'citizen') {
          try {
            const { supabase } = await import('@/config/supabase');
            const session = await authApi.getSession();
            
            if (session?.user?.id) {
              const { data: fullProfile, error: profileError } = await supabase
                .from('users')
                .select('id, name, email, role, commune_id, age, phone')
                .eq('id', session.user.id)
                .single();
              
              if (!profileError && fullProfile) {
                userProfile = fullProfile;
              }
            }
          } catch (err) {
            console.warn('Erreur récupération profil complet:', err);
            // Continuer avec result.user si erreur
          }
        }

        // Vérifier si le profil est complet (pour tous les citoyens, nouveaux ou existants)
        // Un profil est complet si : age ET commune_id ET phone sont définis
        const needsCompletion = userProfile?.role === 'citizen' && (!userProfile.age || !userProfile.commune_id || !userProfile.phone);
        
        console.log('🔍 Vérification profil:', {
          role: userProfile?.role,
          age: userProfile?.age,
          commune_id: userProfile?.commune_id,
          phone: userProfile?.phone,
          needsCompletion,
        });
        
        if (needsCompletion) {
          // Profil incomplet → Afficher la modal de complétion
          console.log('📝 Profil incomplet, affichage de la modal');
          setUser(userProfile);
          setShowProfileModal(true);
          setStatus('needsProfile');
          return;
        }

        // Profil complet ou user existant → Rediriger
        setStatus('success');

        // Si user avec role 'citizen' → Rediriger vers /home (citoyen)
        if (result.user?.role === 'citizen') {
          setTimeout(() => {
            navigate('/home', { replace: true });
          }, 1500);
          return;
        }

        // User avec role (agent/admin) → Rediriger vers dashboard approprié
        const redirectPath = authService.getRedirectPath(result.user.role);
        setTimeout(() => {
          navigate(redirectPath, { replace: true });
        }, 1500);

      } catch (err) {
        console.error('🔴 Erreur callback OAuth:', err);
        console.error('🔴 Détails:', {
          message: err.message,
          code: err.code,
          details: err.details,
          hint: err.hint,
        });
        
        // En développement, afficher plus de détails
        const errorMessage = process.env.NODE_ENV === 'development'
          ? `Erreur: ${err.message || 'Erreur inconnue'}${err.details ? ` (${err.details})` : ''}`
          : 'Une erreur est survenue. Veuillez réessayer';
        
        setError(errorMessage);
        setStatus('error');
      }
    };

    // Traiter le callback immédiatement
    handleCallback();
  }, [navigate, checkAuth]);

  /**
   * Callback appelé après complétion du profil
   */
  const handleProfileComplete = async (updatedUser) => {
    setShowProfileModal(false);
    setStatus('success');
    await checkAuth(); // Rafraîchir le contexte avec le profil complet

    // Rediriger vers /home après un court délai
    setTimeout(() => {
      navigate('/home', { replace: true });
    }, 1500);
  };

  // ═══════════════════════════════════════════════════════════
  // RENDER
  // ═══════════════════════════════════════════════════════════

  // Modal de complétion de profil
  if (showProfileModal && user) {
    return (
      <>
        <div className="min-h-screen flex items-center justify-center bg-neutral-50 p-4">
          <Card className="w-full max-w-md">
            <CardContent className="pt-6">
              <div className="flex flex-col items-center space-y-4">
                <CheckCircle className="h-12 w-12 text-success-600" />
                <p className="text-neutral-700 font-medium text-center">
                  {t('oauth.callback.success', { defaultValue: 'Connexion réussie !' })}
                </p>
                <p className="text-sm text-neutral-500 text-center">
                  {t('oauth.callback.completingProfile', { defaultValue: 'Complétons votre profil...' })}
                </p>
              </div>
            </CardContent>
          </Card>
        </div>
        <OAuthProfileCompletionModal
          open={showProfileModal}
          onComplete={handleProfileComplete}
          user={user}
        />
      </>
    );
  }

  if (status === 'processing') {
    return (
      <div className="min-h-screen flex items-center justify-center bg-neutral-50 p-4">
        <Card className="w-full max-w-md">
          <CardContent className="pt-6">
            <div className="flex flex-col items-center space-y-4">
              <Loader2 className="h-12 w-12 animate-spin text-primary-600" />
              <p className="text-neutral-700 font-medium text-center">
                {t('oauth.callback.processing', { defaultValue: 'Connexion en cours...' })}
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (status === 'success') {
    return (
      <div className="min-h-screen flex items-center justify-center bg-neutral-50 p-4">
        <Card className="w-full max-w-md">
          <CardContent className="pt-6">
            <div className="flex flex-col items-center space-y-4">
              <CheckCircle className="h-12 w-12 text-success-600" />
              <p className="text-neutral-700 font-medium text-center">
                {t('oauth.callback.success', { defaultValue: 'Connexion réussie !' })}
              </p>
              <p className="text-sm text-neutral-500 text-center">
                {t('oauth.callback.redirecting', { defaultValue: 'Redirection en cours...' })}
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  // Status = 'error'
  return (
    <div className="min-h-screen flex items-center justify-center bg-neutral-50 p-4">
      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle className="text-center">
            {t('oauth.callback.error', { defaultValue: 'Erreur de connexion' })}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center gap-2 text-error-600">
            <AlertCircle className="h-5 w-5" />
            <p className="text-sm">{error || t('oauth.callback.errorMessage', { defaultValue: 'Impossible de finaliser la connexion' })}</p>
          </div>
          <Button
            onClick={() => navigate('/welcome', { replace: true })}
            className="w-full"
          >
            {t('oauth.callback.backToWelcome', { defaultValue: 'Retour à l\'inscription' })}
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}

export default AuthCallback;

