// @generated by Cursor AI (Claude) — verified by Kevin

/**
 * Configuration Gemini API
 * 
 * Initialise le client Gemini pour l'extraction de données structurées
 * depuis les transcriptions vocales.
 */

const geminiApiKey = import.meta.env.VITE_GEMINI_API_KEY;

if (!geminiApiKey) {
  console.warn('⚠️ VITE_GEMINI_API_KEY non configurée. L\'extraction IA sera désactivée.');
}

export { geminiApiKey };

export default {
  apiKey: geminiApiKey,
  model: 'gemini-2.0-flash-exp', // Modèle rapide et économique pour l'extraction de texte
  enabled: !!geminiApiKey,
};

