// @generated by Cursor AI (Claude) — verified by [developer name]
/**
 * API Service pour l'authentification vocale
 * Communique avec le backend FastAPI (wattu-voice-api)
 */

// URL de l'API vocale (configurable via .env)
const VOICE_API_URL = import.meta.env.VITE_VOICE_API_URL || 'http://localhost:8000';

/**
 * Enrôlement vocal - Étape 1
 * Envoie l'audio au backend pour transcription et extraction d'embedding
 * 
 * @param {Blob} audioBlob - Fichier audio (WebM ou WAV)
 * @returns {Promise<Object>} - { success, temp_user_id, name, prenom, transcribed_text, voice_embedding, temp_voice_url }
 */
export async function enrollVoice(audioBlob) {
  try {
    const formData = new FormData();
    formData.append('file', audioBlob, 'enrollment.webm');

    const response = await fetch(`${VOICE_API_URL}/api/enroll`, {
      method: 'POST',
      body: formData,
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.detail || `Erreur ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error('❌ Erreur enrollVoice:', error);
    return {
      success: false,
      error: error.message || 'Erreur lors de l\'enrôlement vocal',
    };
  }
}

/**
 * Confirmation d'enrôlement - Étape 2
 * Confirme le nom/prénom (corrigé par l'utilisateur si nécessaire)
 * et crée l'utilisateur vocal dans la base de données
 * 
 * @param {Object} data - { temp_user_id, name, prenom, voice_embedding }
 * @returns {Promise<Object>} - { success, user_id, name, prenom, message }
 */
export async function confirmEnrollment(data) {
  try {
    const response = await fetch(`${VOICE_API_URL}/api/enroll/confirm`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.detail || `Erreur ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error('❌ Erreur confirmEnrollment:', error);
    return {
      success: false,
      error: error.message || 'Erreur lors de la confirmation',
    };
  }
}

/**
 * Vérification vocale (Login)
 * Compare l'audio avec l'embedding stocké
 * 
 * @param {string} userId - ID de l'utilisateur vocal
 * @param {Blob} audioBlob - Fichier audio (WebM ou WAV)
 * @returns {Promise<Object>} - { success, similarity, threshold, match, user_id, name, prenom, message }
 */
export async function verifyVoice(userId, audioBlob) {
  try {
    const formData = new FormData();
    formData.append('file', audioBlob, 'verification.webm');

    const response = await fetch(`${VOICE_API_URL}/api/verify/${userId}`, {
      method: 'POST',
      body: formData,
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.detail || `Erreur ${response.status}`);
    }

    return await response.json();
  } catch (error) {
    console.error('❌ Erreur verifyVoice:', error);
    return {
      success: false,
      error: error.message || 'Erreur lors de la vérification vocale',
    };
  }
}

/**
 * Health check de l'API vocale
 * Vérifie si le backend FastAPI est accessible
 * 
 * @returns {Promise<boolean>} - true si l'API est disponible
 */
export async function checkVoiceApiHealth() {
  try {
    const response = await fetch(`${VOICE_API_URL}/health`, {
      method: 'GET',
    });
    return response.ok;
  } catch (error) {
    console.error('❌ Voice API non disponible:', error);
    return false;
  }
}

export const voiceAuthApi = {
  enrollVoice,
  confirmEnrollment,
  verifyVoice,
  checkVoiceApiHealth,
};

export default voiceAuthApi;

