// @generated by Cursor AI (Claude) — verified by Kevin

import { supabase } from '@/config/supabase';

/**
 * Créer un bucket Supabase Storage s'il n'existe pas
 * 
 * @param {string} bucketName - Nom du bucket à créer
 * @param {Object} options - Options du bucket
 * @param {boolean} options.public - Si le bucket est public (défaut: true)
 * @param {number} options.fileSizeLimit - Taille max des fichiers en bytes (défaut: 10MB)
 * @param {string[]} options.allowedMimeTypes - Types MIME autorisés (optionnel)
 * 
 * @returns {Promise<{success: boolean, error: Object|null, bucket: Object|null}>}
 * 
 * @example
 * const result = await createStorageBucket('report-audio', {
 *   public: true,
 *   fileSizeLimit: 10 * 1024 * 1024, // 10MB
 * });
 */
export async function createStorageBucket(bucketName, options = {}) {
  const {
    public: isPublic = true,
    fileSizeLimit = 10 * 1024 * 1024, // 10MB par défaut
    allowedMimeTypes = null,
  } = options;

  try {
    console.log(`🔍 Vérification du bucket "${bucketName}"...`);

    // Vérifier si le bucket existe déjà
    const { data: existingBuckets, error: listError } = await supabase.storage.listBuckets();

    if (listError) {
      console.error('❌ Erreur lors de la vérification des buckets:', listError);
      return {
        success: false,
        error: listError,
        bucket: null,
      };
    }

    // Vérifier si le bucket existe
    const bucketExists = existingBuckets?.some((bucket) => bucket.name === bucketName);

    if (bucketExists) {
      console.log(`✅ Le bucket "${bucketName}" existe déjà`);
      const existingBucket = existingBuckets.find((b) => b.name === bucketName);
      return {
        success: true,
        error: null,
        bucket: existingBucket,
        alreadyExists: true,
      };
    }

    console.log(`📦 Création du bucket "${bucketName}"...`);

    // Créer le bucket
    // Note: Supabase Storage API nécessite l'utilisation de l'API REST directement
    // car le client JS ne supporte pas la création de buckets directement
    // On va utiliser fetch avec le service_role key si disponible, sinon on retourne une erreur

    // Pour créer un bucket, on doit utiliser l'API REST Supabase avec un token admin
    // Malheureusement, le client JS ne permet pas de créer des buckets directement
    // Il faut le faire via l'interface Supabase ou via l'API REST avec service_role

    // Solution temporaire : retourner une erreur avec instructions
    const error = {
      code: 'BUCKET_CREATION_NOT_SUPPORTED',
      message: `Le bucket "${bucketName}" n'existe pas. Veuillez le créer manuellement via l'interface Supabase Dashboard : Storage > New bucket > Nom: "${bucketName}", Public: ${isPublic}`,
      instructions: [
        `1. Allez sur https://supabase.com/dashboard/project/${supabase.supabaseUrl?.split('//')[1]?.split('.')[0]}/storage/buckets`,
        `2. Cliquez sur "New bucket"`,
        `3. Nom: "${bucketName}"`,
        `4. Public: ${isPublic ? 'Oui' : 'Non'}`,
        `5. File size limit: ${(fileSizeLimit / 1024 / 1024).toFixed(0)}MB`,
        `6. Cliquez sur "Create bucket"`,
      ],
    };

    console.error('❌', error.message);
    console.log('📋 Instructions:', error.instructions);

    return {
      success: false,
      error,
      bucket: null,
    };
  } catch (err) {
    console.error('❌ Erreur inattendue createStorageBucket:', err);
    return {
      success: false,
      error: {
        code: 'UNEXPECTED_ERROR',
        message: err.message || 'Erreur inattendue lors de la création du bucket',
        originalError: err,
      },
      bucket: null,
    };
  }
}

/**
 * Vérifier si un bucket existe
 * 
 * @param {string} bucketName - Nom du bucket à vérifier
 * @returns {Promise<{exists: boolean, bucket: Object|null, error: Object|null}>}
 */
export async function checkBucketExists(bucketName) {
  try {
    const { data: buckets, error } = await supabase.storage.listBuckets();

    if (error) {
      return {
        exists: false,
        bucket: null,
        error,
      };
    }

    const bucket = buckets?.find((b) => b.name === bucketName);

    return {
      exists: !!bucket,
      bucket: bucket || null,
      error: null,
    };
  } catch (err) {
    return {
      exists: false,
      bucket: null,
      error: {
        code: 'UNEXPECTED_ERROR',
        message: err.message || 'Erreur inattendue',
        originalError: err,
      },
    };
  }
}

export default {
  createStorageBucket,
  checkBucketExists,
};

