// @generated by Cursor AI (Claude) — verified by Kevin

import { parseFieldValue, normalizeText, parseFrenchNumber, extractEmail, extractPhone, findCommuneInText } from './voiceDataParser';

/**
 * Configuration des questions pour l'inscription vocale
 * 
 * Chaque question contient :
 * - id: Identifiant unique du champ
 * - question: Texte de la question (peut être une fonction pour interpolation)
 * - validation: Fonction de validation (retourne true/false)
 * - errorMessage: Message d'erreur si validation échoue
 * - parser: Fonction pour parser la réponse vocale
 * - required: Si le champ est obligatoire (default: true)
 */

/**
 * Créer la configuration des questions
 * 
 * @param {Array} communes - Liste des communes disponibles (pour validation/parsing)
 * @param {string} language - Langue ('fr' | 'wo')
 * @returns {Array} Liste des questions configurées
 */
export function createSignupQuestions(communes = [], language = 'fr') {
  const questions = [
    {
      id: 'firstName',
      question: (collectedData) => {
        if (language === 'fr') {
          return 'Bonjour ! Je vais vous aider à créer votre compte. Commençons par votre prénom.';
        }
        return 'Salaam ! Damaa la jëkk ci defar sa kont. Jëkk, maa ngi la laaj sa turu jëkk.';
      },
      validation: (value) => {
        if (!value || typeof value !== 'string') return false;
        const trimmed = value.trim();
        return trimmed.length >= 2 && trimmed.length <= 50;
      },
      errorMessage: language === 'fr' 
        ? 'Le prénom doit contenir entre 2 et 50 caractères.'
        : 'Tur bu jëkk bi daf war a am 2 ba 50 xaraf.',
      parser: (text) => normalizeText(text),
      required: true,
    },
    {
      id: 'lastName',
      question: (collectedData) => {
        if (language === 'fr') {
          return `Parfait, ${collectedData.firstName || ''}. Quel est votre nom de famille ?`;
        }
        return `Waaw, ${collectedData.firstName || ''}. Lan mooy sa turu mag ?`;
      },
      validation: (value) => {
        if (!value || typeof value !== 'string') return false;
        const trimmed = value.trim();
        return trimmed.length >= 2 && trimmed.length <= 50;
      },
      errorMessage: language === 'fr'
        ? 'Le nom doit contenir entre 2 et 50 caractères.'
        : 'Tur bu mag bi daf war a am 2 ba 50 xaraf.',
      parser: (text) => normalizeText(text),
      required: true,
    },
    {
      id: 'age',
      question: (collectedData) => {
        if (language === 'fr') {
          return 'Merci. Quel est votre âge ?';
        }
        return 'Jërëjëf. Ñaata at nga am ?';
      },
      validation: (value) => {
        if (value === null || value === undefined) return false;
        const age = typeof value === 'number' ? value : parseInt(value);
        return !isNaN(age) && age >= 1 && age <= 120;
      },
      errorMessage: language === 'fr'
        ? 'L\'âge doit être un nombre entre 1 et 120.'
        : 'At bi daf war a nekk lim bu nekk ci 1 ak 120.',
      parser: (text) => parseFrenchNumber(text),
      required: true,
    },
    {
      id: 'commune_id',
      question: (collectedData) => {
        if (language === 'fr') {
          return 'Dans quelle commune habitez-vous ? Dites simplement le nom de la commune, par exemple "Dakar" ou "Saint-Louis".';
        }
        return 'Ana fa nga dëkk ? Wax ci turu dëkk bi, mel ni "Dakar" walla "Saint-Louis".';
      },
      validation: (value) => {
        if (!value) return false;
        // Vérifier que la commune existe dans la liste
        if (communes.length > 0) {
          return communes.some(c => c.id === value);
        }
        return true; // Si pas de communes chargées, accepter n'importe quelle valeur
      },
      errorMessage: language === 'fr'
        ? 'Je n\'ai pas reconnu cette commune. Veuillez répéter uniquement le nom de votre commune, par exemple "Dakar" ou "Saint-Louis".'
        : 'Damaa ko xamul. Waxaat ci sa dëkk, mel ni "Dakar" walla "Saint-Louis".',
      parser: async (text) => {
        const commune = await findCommuneInText(text, communes);
        return commune ? commune.id : null;
      },
      required: true,
    },
    {
      id: 'phone',
      question: (collectedData) => {
        if (language === 'fr') {
          return 'Quel est votre numéro de téléphone ?';
        }
        return 'Lan mooy sa nimëroo telefone ?';
      },
      validation: (value) => {
        if (!value || typeof value !== 'string') return false;
        // Format Sénégal : 9 chiffres (77, 78, 76, 70, etc.)
        const digits = value.replace(/\D/g, '');
        return digits.length === 9 && /^[0-9]{9}$/.test(digits);
      },
      errorMessage: language === 'fr'
        ? 'Le numéro de téléphone doit contenir 9 chiffres.'
        : 'Nimëroo telefone bi daf war a am 9 xaraf.',
      parser: (text) => extractPhone(text),
      required: true,
    },
    {
      id: 'address',
      question: (collectedData) => {
        if (language === 'fr') {
          return 'Quelle est votre adresse complète ?';
        }
        return 'Lan mooy sa adres bu wuute ?';
      },
      validation: (value) => {
        if (!value || typeof value !== 'string') return false;
        const trimmed = value.trim();
        return trimmed.length >= 5 && trimmed.length <= 200;
      },
      errorMessage: language === 'fr'
        ? 'Votre adresse semble trop courte. Veuillez donner plus de détails, par exemple "Rue 12, quartier Plateau, Dakar".'
        : 'Adres bi tuuti la. Wax ko ci lu gën a wuute, mel ni "Rue 12, quartier Plateau, Dakar".',
      parser: async (text) => {
        // Essayer d'abord le parsing classique
        const normalized = normalizeText(text, true);
        // Si le résultat semble incomplet, essayer avec Gemini AI
        if (normalized.length < 10) {
          try {
            const { normalizeAddressWithAI } = await import('@/services/geminiParserService');
            const aiAddress = await normalizeAddressWithAI(text);
            if (aiAddress && aiAddress.length >= 10) {
              return aiAddress;
            }
          } catch (error) {
            console.warn('⚠️ Erreur normalisation adresse avec Gemini:', error);
          }
        }
        return normalized;
      },
      required: true,
    },
    {
      id: 'email',
      question: (collectedData) => {
        if (language === 'fr') {
          return 'Enfin, quel est votre adresse email ? Vous pouvez l\'épeler en disant "point" pour le point et "at" pour l\'arobase, par exemple "amadou point diallo at gmail point com".';
        }
        return 'Ci mujj, lan mooy sa adres email ? Wax ko ci xaraf, mel ni "amadou point diallo at gmail point com".';
      },
      validation: (value) => {
        if (!value || typeof value !== 'string') return false;
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        return emailRegex.test(value.trim());
      },
      errorMessage: language === 'fr'
        ? 'Je n\'ai pas compris votre email. Dites-le en épelant, par exemple "amadou point diallo at gmail point com" ou "amadou.diallo@gmail.com".'
        : 'Damaa ko xamul. Wax ko ci xaraf, mel ni "amadou point diallo at gmail point com".',
      parser: async (text) => await extractEmail(text),
      required: true,
    },
  ];

  return questions;
}

/**
 * Obtenir une question par son ID
 * 
 * @param {string} questionId - ID de la question
 * @param {Array} communes - Liste des communes
 * @param {string} language - Langue
 * @returns {Object|null} Question ou null
 */
export function getQuestionById(questionId, communes = [], language = 'fr') {
  const questions = createSignupQuestions(communes, language);
  return questions.find(q => q.id === questionId) || null;
}

/**
 * Obtenir le nombre total de questions
 * 
 * @returns {number}
 */
export function getTotalQuestions() {
  return createSignupQuestions().length;
}

export default {
  createSignupQuestions,
  getQuestionById,
  getTotalQuestions,
};

