// @generated by Cursor AI (Claude) — verified by Kevin

import { lazy, Suspense } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { TrendingUp, Loader2 } from 'lucide-react';
import { useTranslation } from 'react-i18next';

// Lazy load Recharts
const LineChart = lazy(() => import('recharts').then(module => ({ default: module.LineChart })));
const Line = lazy(() => import('recharts').then(module => ({ default: module.Line })));
const XAxis = lazy(() => import('recharts').then(module => ({ default: module.XAxis })));
const YAxis = lazy(() => import('recharts').then(module => ({ default: module.YAxis })));
const CartesianGrid = lazy(() => import('recharts').then(module => ({ default: module.CartesianGrid })));
const Tooltip = lazy(() => import('recharts').then(module => ({ default: module.Tooltip })));
const ResponsiveContainer = lazy(() => import('recharts').then(module => ({ default: module.ResponsiveContainer })));
const Legend = lazy(() => import('recharts').then(module => ({ default: module.Legend })));

/**
 * Graphique d'évolution des signalements dans le temps (pour agent)
 * 
 * @param {Object} props
 * @param {Array} props.trends - Données de tendance [{ date: '2025-01-01', count: 5 }, ...]
 * @param {boolean} [props.loading] - État de chargement
 * 
 * @example
 * <AgentTrendsChart trends={trends} loading={loading} />
 */
function AgentTrendsChart({ trends = [], loading = false }) {
  const { t } = useTranslation('agent');

  if (loading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <TrendingUp className="w-5 h-5 text-primary-600" />
            {t('trends.over_time.title', { defaultValue: 'Évolution des signalements' })}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="h-80 bg-neutral-100 rounded-lg animate-pulse" />
        </CardContent>
      </Card>
    );
  }

  if (!trends || trends.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <TrendingUp className="w-5 h-5 text-primary-600" />
            {t('trends.over_time.title', { defaultValue: 'Évolution des signalements' })}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-neutral-500 text-center py-12">
            {t('trends.no_data', { defaultValue: 'Aucune donnée disponible' })}
          </p>
        </CardContent>
      </Card>
    );
  }

  // Formater les données pour Recharts
  const formattedTrends = trends.map((item) => {
    const date = new Date(item.date);
    const day = date.getDate();
    const month = date.getMonth() + 1;
    
    return {
      ...item,
      displayDate: `${day}/${month}`,
      fullDate: item.date
    };
  });

  // Custom Tooltip
  const CustomTooltip = ({ active, payload }) => {
    if (active && payload && payload.length) {
      const data = payload[0].payload;
      const date = new Date(data.fullDate);
      const formattedDate = date.toLocaleDateString('fr-FR', { 
        day: '2-digit', 
        month: 'long', 
        year: 'numeric' 
      });

      return (
        <div className="bg-white border-2 border-primary-200 rounded-lg p-3 shadow-lg">
          <p className="text-sm font-medium text-neutral-900">{formattedDate}</p>
          <p className="text-lg font-bold text-primary-600">
            {data.count} signalement{data.count > 1 ? 's' : ''}
          </p>
        </div>
      );
    }
    return null;
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <TrendingUp className="w-5 h-5 text-primary-600" />
          {t('trends.over_time.title', { defaultValue: 'Évolution des signalements' })}
        </CardTitle>
      </CardHeader>
      <CardContent>
        <Suspense
          fallback={
            <div className="h-80 flex items-center justify-center">
              <Loader2 className="h-8 w-8 animate-spin text-primary-600" />
            </div>
          }
        >
          <ResponsiveContainer width="100%" height={320}>
            <LineChart
              data={formattedTrends}
              margin={{ top: 5, right: 20, left: 0, bottom: 5 }}
            >
              <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
              <XAxis 
                dataKey="displayDate" 
                tick={{ fontSize: 12 }}
                stroke="#6b7280"
                interval="preserveStartEnd"
              />
              <YAxis 
                tick={{ fontSize: 12 }}
                stroke="#6b7280"
                allowDecimals={false}
              />
              <Tooltip content={<CustomTooltip />} />
              <Legend 
                wrapperStyle={{ fontSize: '14px', paddingTop: '10px' }}
                iconType="line"
              />
              <Line 
                type="monotone" 
                dataKey="count" 
                name={t('trends.reports', { defaultValue: 'Signalements' })}
                stroke="#2563eb" 
                strokeWidth={3}
                dot={{ fill: '#2563eb', r: 4 }}
                activeDot={{ r: 6 }}
              />
            </LineChart>
          </ResponsiveContainer>
        </Suspense>
      </CardContent>
    </Card>
  );
}

export default AgentTrendsChart;

