// @generated by Cursor AI (Claude) — verified by Kevin

import { useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { BarChart3, Loader2 } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import {
  BarChart,
  Bar,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer
} from 'recharts';

/**
 * Graphique en barres pour la répartition par priorité
 * 
 * @param {Object} props
 * @param {Object} props.byPriority - Répartition par priorité { low: 5, normal: 10, ... }
 * @param {boolean} [props.loading] - État de chargement
 * 
 * @example
 * <PriorityDistributionChart byPriority={{ low: 5, normal: 10, high: 3 }} />
 */
function PriorityDistributionChart({ byPriority = {}, loading = false, namespace = 'agent' }) {
  const { t } = useTranslation(namespace);

  // Couleurs pour chaque priorité
  const COLORS = {
    low: '#6b7280', // gray
    normal: '#3b82f6', // blue
    high: '#f59e0b', // amber
    urgent: '#ef4444', // red
  };

  // Préparer les données pour le graphique (mémorisé pour éviter les re-renders)
  const data = useMemo(() => [
    {
      name: t('priority.low', { defaultValue: 'Basse' }),
      value: byPriority.low || 0,
      priority: 'low'
    },
    {
      name: t('priority.normal', { defaultValue: 'Normale' }),
      value: byPriority.normal || 0,
      priority: 'normal'
    },
    {
      name: t('priority.high', { defaultValue: 'Haute' }),
      value: byPriority.high || 0,
      priority: 'high'
    },
    {
      name: t('priority.urgent', { defaultValue: 'Urgente' }),
      value: byPriority.urgent || 0,
      priority: 'urgent'
    }
  ], [byPriority.low, byPriority.normal, byPriority.high, byPriority.urgent, t]);

  if (loading) {
    return (
      <Card className="bg-gradient-to-br from-rose-50/50 via-white to-pink-50/30 border-2 border-rose-200/50 shadow-md">
        <CardHeader className="bg-gradient-to-r from-rose-50 to-transparent border-b border-rose-200/30">
          <CardTitle className="flex items-center gap-2 text-rose-900">
            <BarChart3 className="w-5 h-5 text-rose-600" />
            {t(`${namespace === 'admin' ? 'analytics' : 'trends'}.by_priority.title`, { defaultValue: 'Répartition par priorité' })}
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-6">
          <div className="h-80 bg-neutral-100 rounded-lg animate-pulse" />
        </CardContent>
      </Card>
    );
  }

  const total = data.reduce((sum, item) => sum + item.value, 0);
  if (total === 0) {
    return (
      <Card className="bg-gradient-to-br from-rose-50/50 via-white to-pink-50/30 border-2 border-rose-200/50 shadow-md">
        <CardHeader className="bg-gradient-to-r from-rose-50 to-transparent border-b border-rose-200/30">
          <CardTitle className="flex items-center gap-2 text-rose-900">
            <BarChart3 className="w-5 h-5 text-rose-600" />
            {t(`${namespace === 'admin' ? 'analytics' : 'trends'}.by_priority.title`, { defaultValue: 'Répartition par priorité' })}
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-6">
          <p className="text-rose-700 text-center py-12 font-medium">
            {t(`${namespace === 'admin' ? 'analytics' : 'trends'}.no_data`, { defaultValue: 'Aucune donnée disponible' })}
          </p>
        </CardContent>
      </Card>
    );
  }

  const CustomTooltip = ({ active, payload }) => {
    if (active && payload && payload.length) {
      const data = payload[0].payload;
      return (
        <div className="bg-white border-2 border-primary-200 rounded-lg p-3 shadow-lg">
          <p className="text-sm font-medium text-neutral-900">{data.name}</p>
          <p className="text-lg font-bold text-primary-600">
            {data.value} signalement{data.value > 1 ? 's' : ''}
          </p>
        </div>
      );
    }
    return null;
  };

  return (
    <Card className="bg-gradient-to-br from-rose-50/50 via-white to-pink-50/30 border-2 border-rose-200/50 shadow-md">
      <CardHeader className="bg-gradient-to-r from-rose-50 to-transparent border-b border-rose-200/30">
        <CardTitle className="flex items-center gap-2 text-rose-900">
          <BarChart3 className="w-5 h-5 text-rose-600" />
          {t(`${namespace === 'admin' ? 'analytics' : 'trends'}.by_priority.title`, { defaultValue: 'Répartition par priorité' })}
        </CardTitle>
      </CardHeader>
      <CardContent className="pt-6">
        <ResponsiveContainer width="100%" height={320}>
          <BarChart data={data} margin={{ top: 5, right: 20, left: 0, bottom: 5 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
            <XAxis 
              dataKey="name" 
              tick={{ fontSize: 12 }}
              stroke="#6b7280"
            />
            <YAxis 
              tick={{ fontSize: 12 }}
              stroke="#6b7280"
              allowDecimals={false}
            />
            <Tooltip content={<CustomTooltip />} />
            <Bar dataKey="value" radius={[8, 8, 0, 0]}>
              {data.map((entry, index) => (
                <Cell key={`cell-${index}`} fill={COLORS[entry.priority]} />
              ))}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </CardContent>
    </Card>
  );
}

export default PriorityDistributionChart;

