// @generated by Cursor AI (Claude) — verified by Kevin

import { useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { BarChart3, Loader2 } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import {
  BarChart,
  Bar,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer
} from 'recharts';

/**
 * Graphique en barres pour la répartition par statut
 * 
 * @param {Object} props
 * @param {Object} props.byStatus - Répartition par statut { pending: 5, in_progress: 3, ... }
 * @param {boolean} [props.loading] - État de chargement
 * 
 * @example
 * <StatusDistributionChart byStatus={{ pending: 10, in_progress: 5 }} />
 */
function StatusDistributionChart({ byStatus = {}, loading = false, namespace = 'agent' }) {
  const { t } = useTranslation(namespace);

  // Couleurs pour chaque statut
  const COLORS = {
    pending: '#f59e0b', // amber
    in_progress: '#3b82f6', // blue
    resolved: '#10b981', // green
    rejected: '#ef4444', // red
  };

  // Préparer les données pour le graphique (mémorisé pour éviter les re-renders)
  const data = useMemo(() => [
    {
      name: t('status.pending', { defaultValue: 'En attente' }),
      value: byStatus.pending || 0,
      status: 'pending'
    },
    {
      name: t('status.in_progress', { defaultValue: 'En cours' }),
      value: byStatus.in_progress || 0,
      status: 'in_progress'
    },
    {
      name: t('status.resolved', { defaultValue: 'Résolu' }),
      value: byStatus.resolved || 0,
      status: 'resolved'
    },
    {
      name: t('status.rejected', { defaultValue: 'Rejeté' }),
      value: byStatus.rejected || 0,
      status: 'rejected'
    }
  ], [byStatus.pending, byStatus.in_progress, byStatus.resolved, byStatus.rejected, t]);

  if (loading) {
    return (
      <Card className="bg-gradient-to-br from-teal-50/50 via-white to-cyan-50/30 border-2 border-teal-200/50 shadow-md">
        <CardHeader className="bg-gradient-to-r from-teal-50 to-transparent border-b border-teal-200/30">
          <CardTitle className="flex items-center gap-2 text-teal-900">
            <BarChart3 className="w-5 h-5 text-teal-600" />
            {t(`${namespace === 'admin' ? 'analytics' : 'trends'}.by_status.title`, { defaultValue: 'Répartition par statut' })}
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-6">
          <div className="h-80 bg-neutral-100 rounded-lg animate-pulse" />
        </CardContent>
      </Card>
    );
  }

  const total = data.reduce((sum, item) => sum + item.value, 0);
  if (total === 0) {
    return (
      <Card className="bg-gradient-to-br from-teal-50/50 via-white to-cyan-50/30 border-2 border-teal-200/50 shadow-md">
        <CardHeader className="bg-gradient-to-r from-teal-50 to-transparent border-b border-teal-200/30">
          <CardTitle className="flex items-center gap-2 text-teal-900">
            <BarChart3 className="w-5 h-5 text-teal-600" />
            {t(`${namespace === 'admin' ? 'analytics' : 'trends'}.by_status.title`, { defaultValue: 'Répartition par statut' })}
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-6">
          <p className="text-teal-700 text-center py-12 font-medium">
            {t(`${namespace === 'admin' ? 'analytics' : 'trends'}.no_data`, { defaultValue: 'Aucune donnée disponible' })}
          </p>
        </CardContent>
      </Card>
    );
  }

  const CustomTooltip = ({ active, payload }) => {
    if (active && payload && payload.length) {
      const data = payload[0].payload;
      return (
        <div className="bg-white border-2 border-primary-200 rounded-lg p-3 shadow-lg">
          <p className="text-sm font-medium text-neutral-900">{data.name}</p>
          <p className="text-lg font-bold text-primary-600">
            {data.value} signalement{data.value > 1 ? 's' : ''}
          </p>
        </div>
      );
    }
    return null;
  };

  return (
    <Card className="bg-gradient-to-br from-teal-50/50 via-white to-cyan-50/30 border-2 border-teal-200/50 shadow-md">
      <CardHeader className="bg-gradient-to-r from-teal-50 to-transparent border-b border-teal-200/30">
        <CardTitle className="flex items-center gap-2 text-teal-900">
          <BarChart3 className="w-5 h-5 text-teal-600" />
          {t(`${namespace === 'admin' ? 'analytics' : 'trends'}.by_status.title`, { defaultValue: 'Répartition par statut' })}
        </CardTitle>
      </CardHeader>
      <CardContent className="pt-6">
        <ResponsiveContainer width="100%" height={320}>
          <BarChart data={data} margin={{ top: 5, right: 20, left: 0, bottom: 5 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
            <XAxis 
              dataKey="name" 
              tick={{ fontSize: 12 }}
              stroke="#6b7280"
            />
            <YAxis 
              tick={{ fontSize: 12 }}
              stroke="#6b7280"
              allowDecimals={false}
            />
            <Tooltip content={<CustomTooltip />} />
            <Bar dataKey="value" radius={[8, 8, 0, 0]}>
              {data.map((entry, index) => (
                <Cell key={`cell-${index}`} fill={COLORS[entry.status]} />
              ))}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </CardContent>
    </Card>
  );
}

export default StatusDistributionChart;

