// @generated by Cursor AI (Claude) — verified by Kevin

import { useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { PieChart as PieChartIcon, Loader2 } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  Legend,
  ResponsiveContainer
} from 'recharts';

/**
 * Graphique en camembert pour la répartition par type de signalement
 * 
 * @param {Object} props
 * @param {Object} props.byType - Répartition par type { road: 5, lighting: 3, ... }
 * @param {boolean} [props.loading] - État de chargement
 * 
 * @example
 * <TypeDistributionChart byType={{ road: 10, lighting: 5 }} />
 */
function TypeDistributionChart({ byType = {}, loading = false, namespace = 'agent' }) {
  const { t } = useTranslation(namespace);

  // Couleurs pour chaque type
  const COLORS = {
    road: '#3b82f6', // blue
    lighting: '#f59e0b', // amber
    water: '#06b6d4', // cyan
    waste: '#10b981', // green
    security: '#ef4444', // red
    health: '#ec4899', // pink
    electricity: '#fbbf24', // yellow
    sanitation: '#8b5cf6', // purple
    green_spaces: '#22c55e', // green
    other: '#6b7280', // gray
  };

  // Préparer les données pour le graphique (mémorisé pour éviter les re-renders)
  const data = useMemo(() => Object.entries(byType)
    .filter(([_, count]) => count > 0) // Filtrer les types avec 0 signalement
    .map(([type, count]) => ({
      name: t(`report_types.${type}`, { defaultValue: type.replace('_', ' ') }),
      value: count,
      type: type
    }))
    .sort((a, b) => b.value - a.value), // Trier par valeur décroissante
    [byType, t]
  );

  if (loading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <PieChartIcon className="w-5 h-5 text-primary-600" />
            {t(`${namespace === 'admin' ? 'analytics' : 'trends'}.by_type.title`, { defaultValue: 'Répartition par type' })}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="h-80 bg-neutral-100 rounded-lg animate-pulse" />
        </CardContent>
      </Card>
    );
  }

  if (data.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <PieChartIcon className="w-5 h-5 text-primary-600" />
            {t(`${namespace === 'admin' ? 'analytics' : 'trends'}.by_type.title`, { defaultValue: 'Répartition par type' })}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-neutral-500 text-center py-12">
            {t(`${namespace === 'admin' ? 'analytics' : 'trends'}.no_data`, { defaultValue: 'Aucune donnée disponible' })}
          </p>
        </CardContent>
      </Card>
    );
  }

  const CustomTooltip = ({ active, payload }) => {
    if (active && payload && payload.length) {
      const data = payload[0];
      return (
        <div className="bg-white border-2 border-primary-200 rounded-lg p-3 shadow-lg">
          <p className="text-sm font-medium text-neutral-900">{data.name}</p>
          <p className="text-lg font-bold text-primary-600">
            {data.value} signalement{data.value > 1 ? 's' : ''}
          </p>
        </div>
      );
    }
    return null;
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <PieChartIcon className="w-5 h-5 text-primary-600" />
          {t(`${namespace === 'admin' ? 'analytics' : 'trends'}.by_type.title`, { defaultValue: 'Répartition par type' })}
        </CardTitle>
      </CardHeader>
      <CardContent>
        <ResponsiveContainer width="100%" height={320}>
          <PieChart>
            <Pie
              data={data}
              cx="50%"
              cy="50%"
              labelLine={false}
              label={({ name, percent }) => `${name}: ${(percent * 100).toFixed(0)}%`}
              outerRadius={100}
              fill="#8884d8"
              dataKey="value"
            >
              {data.map((entry, index) => (
                <Cell key={`cell-${index}`} fill={COLORS[entry.type] || COLORS.other} />
              ))}
            </Pie>
            <Tooltip content={<CustomTooltip />} />
            <Legend />
          </PieChart>
        </ResponsiveContainer>
      </CardContent>
    </Card>
  );
}

export default TypeDistributionChart;

