// @generated by Cursor AI (Claude) — verified by Kevin

import { useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { PieChart as PieChartIcon, Loader2 } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  Legend,
  ResponsiveContainer
} from 'recharts';

/**
 * Graphique en camembert pour la répartition par type de signalement
 * 
 * @param {Object} props
 * @param {Object} props.byType - Répartition par type { road: 5, lighting: 3, ... }
 * @param {boolean} [props.loading] - État de chargement
 * 
 * @example
 * <TypeDistributionChart byType={{ road: 10, lighting: 5 }} />
 */
function TypeDistributionChart({ byType = {}, loading = false, namespace = 'agent' }) {
  const { t } = useTranslation(namespace);

  // Couleurs pour chaque type (types réels de la base de données)
  const COLORS = {
    voirie: '#3b82f6', // blue
    eclairage: '#f59e0b', // amber
    eau: '#06b6d4', // cyan
    dechets: '#10b981', // green
    securite: '#ef4444', // red
    assainissement: '#8b5cf6', // purple
    espaces_verts: '#22c55e', // green
    transport: '#6366f1', // indigo
    autre: '#6b7280', // gray
  };

  // Préparer les données pour le graphique (mémorisé pour éviter les re-renders)
  const data = useMemo(() => Object.entries(byType)
    .filter(([_, count]) => count > 0) // Filtrer les types avec 0 signalement
    .map(([type, count]) => ({
      name: t(`report_types.${type}`, { defaultValue: type.replace('_', ' ') }),
      value: count,
      type: type
    }))
    .sort((a, b) => b.value - a.value), // Trier par valeur décroissante
    [byType, t]
  );

  if (loading) {
    return (
      <Card className="bg-gradient-to-br from-violet-50/50 via-white to-purple-50/30 border-2 border-violet-200/50 shadow-md">
        <CardHeader className="bg-gradient-to-r from-violet-50 to-transparent border-b border-violet-200/30">
          <CardTitle className="flex items-center gap-2 text-violet-900">
            <PieChartIcon className="w-5 h-5 text-violet-600" />
            {t(`${namespace === 'admin' ? 'analytics' : 'trends'}.by_type.title`, { defaultValue: 'Répartition par type' })}
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-6">
          <div className="h-80 bg-neutral-100 rounded-lg animate-pulse" />
        </CardContent>
      </Card>
    );
  }

  if (data.length === 0) {
    return (
      <Card className="bg-gradient-to-br from-violet-50/50 via-white to-purple-50/30 border-2 border-violet-200/50 shadow-md">
        <CardHeader className="bg-gradient-to-r from-violet-50 to-transparent border-b border-violet-200/30">
          <CardTitle className="flex items-center gap-2 text-violet-900">
            <PieChartIcon className="w-5 h-5 text-violet-600" />
            {t(`${namespace === 'admin' ? 'analytics' : 'trends'}.by_type.title`, { defaultValue: 'Répartition par type' })}
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-6">
          <p className="text-violet-700 text-center py-12 font-medium">
            {t(`${namespace === 'admin' ? 'analytics' : 'trends'}.no_data`, { defaultValue: 'Aucune donnée disponible' })}
          </p>
        </CardContent>
      </Card>
    );
  }

  const CustomTooltip = ({ active, payload }) => {
    if (active && payload && payload.length) {
      const data = payload[0];
      return (
        <div className="bg-white border-2 border-primary-200 rounded-lg p-3 shadow-lg">
          <p className="text-sm font-medium text-neutral-900">{data.name}</p>
          <p className="text-lg font-bold text-primary-600">
            {data.value} signalement{data.value > 1 ? 's' : ''}
          </p>
        </div>
      );
    }
    return null;
  };

  return (
    <Card className="bg-gradient-to-br from-violet-50/50 via-white to-purple-50/30 border-2 border-violet-200/50 shadow-md">
      <CardHeader className="bg-gradient-to-r from-violet-50 to-transparent border-b border-violet-200/30">
        <CardTitle className="flex items-center gap-2 text-violet-900">
          <PieChartIcon className="w-5 h-5 text-violet-600" />
          {t(`${namespace === 'admin' ? 'analytics' : 'trends'}.by_type.title`, { defaultValue: 'Répartition par type' })}
        </CardTitle>
      </CardHeader>
      <CardContent className="pt-6">
        <ResponsiveContainer width="100%" height={320}>
          <PieChart>
            <Pie
              data={data}
              cx="50%"
              cy="50%"
              labelLine={false}
              label={({ name, percent }) => `${name}: ${(percent * 100).toFixed(0)}%`}
              outerRadius={100}
              fill="#8884d8"
              dataKey="value"
            >
              {data.map((entry, index) => (
                <Cell key={`cell-${index}`} fill={COLORS[entry.type] || COLORS.other} />
              ))}
            </Pie>
            <Tooltip content={<CustomTooltip />} />
            <Legend />
          </PieChart>
        </ResponsiveContainer>
      </CardContent>
    </Card>
  );
}

export default TypeDistributionChart;

