// @generated by Cursor AI (Claude) — verified by Kevin

import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useAuth } from '@/context/AuthContext';
import { Loader2, AlertCircle } from 'lucide-react';
import CitizenReportList from '@/components/citizen/CitizenReportList';
import ReportDetailBottomSheet from '@/components/citizen/ReportDetailBottomSheet';
import NotificationCenter from '@/components/citizen/NotificationCenter';
import { useNotifications } from '@/hooks/useNotifications';
import * as reportApi from '@/api/reportApi';
import { Card, CardContent } from '@/components/ui/card';

/**
 * Page CitizenDashboard - Dashboard du citoyen
 * 
 * Affiche :
 * - Statistiques des signalements (total, en attente, résolus, etc.)
 * - Liste des signalements du citoyen avec statut
 * - Navigation vers les détails d'un signalement
 * 
 * @example
 * <CitizenDashboard />
 */
function CitizenDashboard() {
  const { t } = useTranslation('common');
  const { user, getVoiceUser, isVoiceAuthenticated } = useAuth();

  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [statusFilter, setStatusFilter] = useState(null); // null = tous
  const [selectedReportId, setSelectedReportId] = useState(null);
  const [showDetailSheet, setShowDetailSheet] = useState(false);

  // Déterminer l'ID utilisateur (Supabase user OU voice user)
  const voiceUser = getVoiceUser();
  const isVoice = isVoiceAuthenticated();
  const userId = isVoice ? voiceUser?.id : user?.id;
  const userName = isVoice ? `${voiceUser?.prenom || ''} ${voiceUser?.name || ''}`.trim() : user?.name;

  // Debug: Log pour vérifier l'état d'authentification
  useEffect(() => {
    console.log('🔍 CitizenDashboard - Auth State:', {
      hasUser: !!user,
      hasVoiceUser: !!voiceUser,
      isVoice,
      userId,
      voiceUserAuthenticated: voiceUser?.authenticated
    });
  }, [user, voiceUser, isVoice, userId]);

  // Gestion des notifications en temps réel (seulement pour Supabase users)
  const {
    notifications,
    unreadCount,
    isSubscribed,
    markAsRead,
    markAllAsRead,
    removeNotification,
    clearAll,
  } = useNotifications(user?.id, {
    enableRealtime: !isVoice, // Désactiver realtime pour voice users
    showToasts: true,
  });

  useEffect(() => {
    if (!userId) {
      setError({ message: t('citizen.dashboard.not_authenticated', { defaultValue: 'Vous devez être connecté' }) });
      setLoading(false);
      return;
    }

    loadDashboardData();
  }, [userId, statusFilter]);

  const loadDashboardData = async () => {
    if (!userId) return;

    setLoading(true);
    setError(null);

    try {
      // Charger les signalements
      const reportsResult = await reportApi.getCitizenReports(userId, { 
        status: statusFilter || undefined,
        limit: 50,
      });

      if (reportsResult.error) {
        setError(reportsResult.error);
      } else {
        setReports(reportsResult.data || []);
      }
    } catch (err) {
      console.error('❌ Erreur chargement dashboard:', err);
      setError({
        message: err.message || t('citizen.dashboard.load_error', { defaultValue: 'Erreur lors du chargement' }),
      });
    } finally {
      setLoading(false);
    }
  };

  // Vérifier si l'utilisateur est authentifié (Supabase OU voice)
  if (!user && !isVoice) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Card>
          <CardContent className="p-6">
            <p className="text-center text-neutral-600">
              {t('citizen.dashboard.not_authenticated', { defaultValue: 'Vous devez être connecté' })}
            </p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen py-6 px-4">
      <div className="max-w-7xl mx-auto space-y-6">
        {/* Header */}
        <div>
          <h1 className="text-3xl font-bold text-white mb-2">
            {t('citizen.dashboard.title', { defaultValue: 'Mes signalements' })}
          </h1>
          <p className="text-neutral-300">
            {t('citizen.dashboard.subtitle', {
              defaultValue: 'Consultez l\'historique et le statut de vos signalements',
            })}
          </p>
        </div>

        {/* Filtres */}
        <section>
          <div className="flex flex-wrap gap-2">
            <button
              onClick={() => setStatusFilter(null)}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                statusFilter === null
                  ? 'bg-primary-600 text-white'
                  : 'bg-white text-neutral-700 border border-neutral-300 hover:bg-neutral-50'
              }`}
            >
              {t('citizen.dashboard.filter.all', { defaultValue: 'Tous' })}
            </button>
            <button
              onClick={() => setStatusFilter('pending')}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                statusFilter === 'pending'
                  ? 'bg-primary-600 text-white'
                  : 'bg-white text-neutral-700 border border-neutral-300 hover:bg-neutral-50'
              }`}
            >
              {t('citizen.dashboard.filter.pending', { defaultValue: 'En attente' })}
            </button>
            <button
              onClick={() => setStatusFilter('in_progress')}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                statusFilter === 'in_progress'
                  ? 'bg-primary-600 text-white'
                  : 'bg-white text-neutral-700 border border-neutral-300 hover:bg-neutral-50'
              }`}
            >
              {t('citizen.dashboard.filter.in_progress', { defaultValue: 'En cours' })}
            </button>
            <button
              onClick={() => setStatusFilter('resolved')}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                statusFilter === 'resolved'
                  ? 'bg-primary-600 text-white'
                  : 'bg-white text-neutral-700 border border-neutral-300 hover:bg-neutral-50'
              }`}
            >
              {t('citizen.dashboard.filter.resolved', { defaultValue: 'Résolus' })}
            </button>
          </div>
        </section>

        {/* Centre de notifications */}
        {notifications.length > 0 && (
          <section>
            <NotificationCenter
              notifications={notifications}
              unreadCount={unreadCount}
              onMarkAsRead={markAsRead}
              onMarkAllAsRead={markAllAsRead}
              onRemove={removeNotification}
              onClearAll={clearAll}
            />
          </section>
        )}

        {/* Liste des signalements */}
        <section>
          <h2 className="text-xl font-semibold text-white mb-4">
            {t('citizen.dashboard.reports_title', { defaultValue: 'Historique' })}
          </h2>
          {loading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="w-8 h-8 animate-spin text-primary-600" />
            </div>
          ) : error ? (
            <Card className="border-red-200 bg-red-50">
              <CardContent className="p-6">
                <div className="flex items-center gap-3">
                  <AlertCircle className="w-5 h-5 text-red-600" />
                  <div>
                    <p className="font-semibold text-red-900">
                      {t('citizen.dashboard.error', { defaultValue: 'Erreur' })}
                    </p>
                    <p className="text-sm text-red-700">{error.message || error}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          ) : (
            <CitizenReportList 
              reports={reports} 
              loading={false} 
              error={null}
              onReportClick={(reportId) => {
                setSelectedReportId(reportId);
                setShowDetailSheet(true);
              }}
            />
          )}
        </section>
      </div>

      {/* Bottom Sheet pour les détails d'un signalement */}
      <ReportDetailBottomSheet
        open={showDetailSheet}
        onClose={() => {
          setShowDetailSheet(false);
          setSelectedReportId(null);
        }}
        reportId={selectedReportId}
      />
    </div>
  );
}

export default CitizenDashboard;

