// @generated by Cursor AI (Claude) — verified by Kevin Mendy
import { useTranslation } from 'react-i18next';
import { Link } from 'react-router-dom';
import { PlusCircle, Map } from 'lucide-react';

/**
 * Page d'accueil pour citoyens (Dashboard public)
 * 
 * Contenu :
 * - Héro avec CTA principal
 * - 2 accès rapides (Signaler + Carte)
 * - Section "Comment ça marche"
 * 
 * TODO : Remplir avec le contenu complet
 */
function HomePage() {
  const { t } = useTranslation('common');

  return (
    <div className="space-y-12">
      {/* Héro Section */}
      <section className="text-center space-y-6 py-12">
        <h1 className="text-4xl md:text-5xl font-bold text-neutral-900">
          {t('home.hero.title', { defaultValue: 'Signalez les problèmes de votre ville' })}
        </h1>
        <p className="text-lg text-neutral-600 max-w-2xl mx-auto">
          {t('home.hero.subtitle', { defaultValue: 'Aidez votre commune à améliorer votre quotidien' })}
        </p>
        <Link
          to="/signalements/nouveau"
          className="inline-flex items-center gap-2 px-6 py-3 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors font-semibold"
        >
          <PlusCircle className="w-5 h-5" />
          {t('home.hero.cta', { defaultValue: 'Faire un signalement' })}
        </Link>
      </section>

      {/* Accès Rapides */}
      <section className="grid md:grid-cols-2 gap-6">
        <Link
          to="/signalements/nouveau"
          className="p-6 bg-white rounded-xl border-2 border-neutral-200 hover:border-primary-500 transition-all hover:shadow-lg"
        >
          <PlusCircle className="w-12 h-12 text-primary-600 mb-4" />
          <h3 className="text-xl font-semibold mb-2">
            {t('home.quick.report.title', { defaultValue: 'Nouveau signalement' })}
          </h3>
          <p className="text-neutral-600">
            {t('home.quick.report.desc', { defaultValue: 'Signalez un problème dans votre ville' })}
          </p>
        </Link>

        <Link
          to="/carte"
          className="p-6 bg-white rounded-xl border-2 border-neutral-200 hover:border-primary-500 transition-all hover:shadow-lg"
        >
          <Map className="w-12 h-12 text-primary-600 mb-4" />
          <h3 className="text-xl font-semibold mb-2">
            {t('home.quick.map.title', { defaultValue: 'Voir la carte' })}
          </h3>
          <p className="text-neutral-600">
            {t('home.quick.map.desc', { defaultValue: 'Découvrez les signalements de votre ville' })}
          </p>
        </Link>
      </section>

      {/* Comment ça marche */}
      <section className="bg-white rounded-xl p-8 space-y-6">
        <h2 className="text-2xl font-bold text-center">
          {t('home.howto.title', { defaultValue: 'Comment ça marche ?' })}
        </h2>
        <div className="grid md:grid-cols-4 gap-6">
          <div className="text-center">
            <div className="w-12 h-12 bg-primary-100 text-primary-600 rounded-full flex items-center justify-center mx-auto mb-3 text-xl font-bold">
              1
            </div>
            <p className="text-neutral-700">
              {t('home.howto.step1', { defaultValue: 'Décrivez le problème' })}
            </p>
          </div>
          <div className="text-center">
            <div className="w-12 h-12 bg-primary-100 text-primary-600 rounded-full flex items-center justify-center mx-auto mb-3 text-xl font-bold">
              2
            </div>
            <p className="text-neutral-700">
              {t('home.howto.step2', { defaultValue: 'Ajoutez une photo' })}
            </p>
          </div>
          <div className="text-center">
            <div className="w-12 h-12 bg-primary-100 text-primary-600 rounded-full flex items-center justify-center mx-auto mb-3 text-xl font-bold">
              3
            </div>
            <p className="text-neutral-700">
              {t('home.howto.step3', { defaultValue: 'Indiquez l\'emplacement' })}
            </p>
          </div>
          <div className="text-center">
            <div className="w-12 h-12 bg-primary-100 text-primary-600 rounded-full flex items-center justify-center mx-auto mb-3 text-xl font-bold">
              4
            </div>
            <p className="text-neutral-700">
              {t('home.howto.step4', { defaultValue: 'Votre commune s\'en occupe' })}
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}

export default HomePage;
