// @generated by Cursor AI (Claude) — verified by Kevin Mendy
import { useTranslation } from 'react-i18next';
import SignalementForm from '@/components/forms/SignalementForm';

/**
 * Page Nouveau Signalement
 * 
 * Contenu :
 * - Formulaire complet de soumission
 * - Type, description, photo, GPS, commune, contact
 * - Validation des champs
 * - Modal de succès après soumission
 */
function NewSignalement() {
  const { t } = useTranslation('common');

  return (
    <div className="max-w-2xl mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-neutral-900 mb-2">
          {t('signalement.new.title', { defaultValue: 'Nouveau signalement' })}
        </h1>
        <p className="text-neutral-600">
          {t('signalement.new.subtitle', { defaultValue: 'Signalez un problème dans votre ville' })}
        </p>
      </div>

      <div className="bg-white rounded-xl p-6 md:p-8 border border-neutral-200 shadow-sm">
        <SignalementForm />
      </div>
    </div>
  );
}

export default NewSignalement;

