// @generated by Cursor AI (Claude) — verified by Kevin

import { useTranslation } from 'react-i18next';
import { useSearchParams } from 'react-router-dom';
import SignalementForm from '@/components/forms/SignalementForm';

/**
 * Page Nouveau Signalement
 * 
 * Contenu :
 * - Formulaire complet de soumission
 * - Type, description, photo, GPS, commune, contact
 * - Validation des champs
 * - Modal de succès après soumission
 */
function NewSignalement() {
  const { t } = useTranslation('common');
  const [searchParams] = useSearchParams();
  const typeFromUrl = searchParams.get('type'); // Récupérer le type depuis l'URL

  return (
    <div className="max-w-2xl mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-white">
          {t('signalement.new.title', { defaultValue: 'Nouveau signalement' })}
        </h1>
      </div>

      <div className="bg-white rounded-xl p-6 md:p-8 border border-neutral-200 shadow-sm">
        <SignalementForm initialType={typeFromUrl} />
      </div>
    </div>
  );
}

export default NewSignalement;

