// @generated by Cursor AI (Claude) — verified by [developer name]
/**
 * Page de vérification vocale (Login)
 * 
 * Route : /voice-verify
 * 
 * Processus :
 * 1. Récupérer l'utilisateur vocal depuis localStorage
 * 2. L'utilisateur enregistre sa voix
 * 3. L'audio est comparé avec l'embedding stocké
 * 4. Si match → Redirection vers le dashboard citoyen
 */

import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Mic, MicOff, Loader2, AlertCircle, CheckCircle, User } from 'lucide-react';
import { toast } from 'sonner';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import Logo from '@/components/shared/Logo';
import { useAudioRecording } from '@/hooks/useAudioRecording';
import { voiceAuthApi } from '@/api/voiceAuthApi';

function VoiceVerify() {
  const { t } = useTranslation('common');
  const navigate = useNavigate();

  // États du processus
  const [step, setStep] = useState('record'); // 'record' | 'processing' | 'success' | 'failed'
  const [error, setError] = useState(null);
  const [voiceUser, setVoiceUser] = useState(null);
  const [verificationResult, setVerificationResult] = useState(null);

  // Hook d'enregistrement audio
  const {
    isSupported,
    isRecording,
    duration,
    maxDuration,
    audioBlob,
    error: recordingError,
    startRecording,
    stopRecording,
    resetRecording,
  } = useAudioRecording({ maxDuration: 10 });

  // Charger l'utilisateur vocal depuis localStorage
  useEffect(() => {
    const storedUser = localStorage.getItem('voiceUser');
    if (storedUser) {
      const user = JSON.parse(storedUser);
      setVoiceUser(user);
    } else {
      // Pas d'utilisateur vocal → Rediriger vers enrôlement
      toast.error('Veuillez d\'abord vous inscrire');
      navigate('/voice-enroll', { replace: true });
    }
  }, [navigate]);

  // Traiter l'audio quand l'enregistrement est terminé
  useEffect(() => {
    if (audioBlob && step === 'record' && voiceUser) {
      handleVerifyVoice();
    }
  }, [audioBlob, voiceUser]);

  /**
   * Envoie l'audio au backend pour vérification
   */
  const handleVerifyVoice = async () => {
    if (!audioBlob || !voiceUser) return;

    setStep('processing');
    setError(null);

    try {
      const result = await voiceAuthApi.verifyVoice(voiceUser.id, audioBlob);

      if (result.success && result.match) {
        // Vérification réussie
        setVerificationResult(result);
        setStep('success');

        // Mettre à jour le statut dans localStorage
        const updatedUser = {
          ...voiceUser,
          authenticated: true,
          lastVerifiedAt: new Date().toISOString(),
        };
        localStorage.setItem('voiceUser', JSON.stringify(updatedUser));

        toast.success(t('voiceAuth.verify.success', { defaultValue: 'Voix reconnue !' }));

        // Rediriger vers le dashboard après 2 secondes
        setTimeout(() => {
          navigate('/home', { replace: true });
        }, 2000);

      } else if (result.success && !result.match) {
        // Voix non reconnue
        setVerificationResult(result);
        setStep('failed');
        setError(t('voiceAuth.verify.errors.voiceNotRecognized', { defaultValue: 'Voix non reconnue. Veuillez réessayer.' }));
        resetRecording();
      } else {
        // Erreur
        setError(result.error || result.message || t('voiceAuth.verify.errors.verificationFailed', { defaultValue: 'Erreur lors de la vérification. Veuillez réessayer.' }));
        setStep('record');
        resetRecording();
      }
    } catch (err) {
      console.error('Erreur vérification:', err);
      const errorMessage = err.message || t('voiceAuth.verify.errors.verificationFailed', { defaultValue: 'Une erreur est survenue. Veuillez réessayer.' });
      setError(errorMessage);
      setStep('record');
      resetRecording();
    }
  };

  /**
   * Recommencer la vérification
   */
  const handleRetry = () => {
    setStep('record');
    setError(null);
    setVerificationResult(null);
    resetRecording();
  };

  /**
   * Formater la durée en mm:ss
   */
  const formatDuration = (seconds) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  // Afficher erreur de support navigateur
  if (!isSupported) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-primary-50 via-white to-neutral-50 px-4">
        <Card className="w-full max-w-md">
          <CardContent className="pt-6 text-center">
            <AlertCircle className="h-12 w-12 text-error-500 mx-auto mb-4" />
            <h2 className="text-lg font-semibold text-neutral-900 mb-2">
              Navigateur non supporté
            </h2>
            <p className="text-sm text-neutral-600">
              Votre navigateur ne supporte pas l'enregistrement audio.
            </p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gradient-to-br from-primary-50 via-white to-neutral-50 px-4 py-8">
      {/* Logo */}
      <div className="mb-6 text-center">
        <div className="flex justify-center mb-4">
          <Logo size="lg" withLink={false} />
        </div>
        <h1 className="text-xl font-bold text-neutral-900">
          {t('voiceAuth.verify.title', { defaultValue: 'Vérification vocale' })}
        </h1>
      </div>

      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle className="text-lg text-center">
            {step === 'record' && t('voiceAuth.verify.title', { defaultValue: 'Confirmez votre identité' })}
            {step === 'processing' && t('voiceAuth.verify.processing', { defaultValue: 'Vérification en cours...' })}
            {step === 'success' && t('voiceAuth.verify.success', { defaultValue: 'Identité confirmée !' })}
            {step === 'failed' && t('voiceAuth.verify.errors.voiceNotRecognized', { defaultValue: 'Voix non reconnue' })}
          </CardTitle>
          <CardDescription className="text-center">
            {step === 'record' && t('voiceAuth.verify.instruction', { defaultValue: 'Dites votre prénom et nom' })}
            {step === 'processing' && t('voiceAuth.verify.processing', { defaultValue: 'Veuillez patienter' })}
            {step === 'success' && t('voiceAuth.verify.redirecting', { defaultValue: 'Redirection en cours...' })}
            {step === 'failed' && t('voiceAuth.verify.retry', { defaultValue: 'Veuillez réessayer' })}
          </CardDescription>
        </CardHeader>

        <CardContent className="space-y-6">
          {/* Info utilisateur */}
          {voiceUser && step !== 'success' && (
            <div className="flex items-center gap-3 p-3 bg-neutral-50 rounded-lg">
              <div className="w-10 h-10 rounded-full bg-primary-100 flex items-center justify-center">
                <User className="h-5 w-5 text-primary-600" />
              </div>
              <div>
                <p className="font-medium text-neutral-900">
                  {voiceUser.prenom} {voiceUser.name}
                </p>
                <p className="text-xs text-neutral-500">
                  {t('voiceAuth.verify.enrolledAt', { defaultValue: 'Inscrit le' })} {new Date(voiceUser.enrolledAt).toLocaleDateString('fr-FR')}
                </p>
              </div>
            </div>
          )}

          {/* Erreur globale */}
          {error && (
            <div className="p-3 rounded-lg bg-error-50 border border-error-200 flex items-start gap-2">
              <AlertCircle className="h-5 w-5 text-error-500 flex-shrink-0 mt-0.5" />
              <p className="text-sm text-error-700">{error}</p>
            </div>
          )}

          {/* Étape 1 : Enregistrement */}
          {step === 'record' && (
            <div className="flex flex-col items-center space-y-6">
              {/* Indicateur de durée */}
              <div className="text-center">
                <p className="text-3xl font-mono font-bold text-neutral-900">
                  {formatDuration(duration)}
                </p>
                <p className="text-xs text-neutral-500">
                  max {formatDuration(maxDuration)}
                </p>
              </div>

              {/* Bouton d'enregistrement */}
              <button
                onClick={isRecording ? stopRecording : startRecording}
                className={`
                  w-24 h-24 rounded-full flex items-center justify-center
                  transition-all duration-300 shadow-lg
                  ${isRecording 
                    ? 'bg-error-500 hover:bg-error-600 animate-pulse' 
                    : 'bg-primary-600 hover:bg-primary-700'
                  }
                `}
              >
                {isRecording ? (
                  <MicOff className="h-10 w-10 text-white" />
                ) : (
                  <Mic className="h-10 w-10 text-white" />
                )}
              </button>

              <p className="text-sm text-neutral-600 text-center">
                {isRecording 
                  ? t('voiceAuth.verify.instruction', { defaultValue: 'Dites votre prénom et nom, puis appuyez pour arrêter' })
                  : t('voiceAuth.verify.instruction', { defaultValue: 'Appuyez pour commencer' })
                }
              </p>
            </div>
          )}

          {/* Étape 2 : Traitement */}
          {step === 'processing' && (
            <div className="flex flex-col items-center space-y-4 py-8">
              <Loader2 className="h-12 w-12 text-primary-600 animate-spin" />
              <p className="text-sm text-neutral-600">
                {t('voiceAuth.verify.processing', { defaultValue: 'Comparaison de votre voix...' })}
              </p>
            </div>
          )}

          {/* Étape 3 : Succès */}
          {step === 'success' && verificationResult && (
            <div className="flex flex-col items-center space-y-4 py-8">
              <div className="w-16 h-16 rounded-full bg-success-100 flex items-center justify-center">
                <CheckCircle className="h-10 w-10 text-success-600" />
              </div>
              <div className="text-center">
                <p className="text-lg font-semibold text-neutral-900">
                  {t('voiceAuth.verify.success', { defaultValue: 'Bienvenue' })} {verificationResult.prenom} !
                </p>
                <p className="text-sm text-neutral-600 mt-2">
                  {t('voiceAuth.verify.redirecting', { defaultValue: 'Redirection en cours...' })}
                </p>
              </div>
              <Loader2 className="h-5 w-5 text-primary-600 animate-spin" />
            </div>
          )}

          {/* Étape 4 : Échec */}
          {step === 'failed' && (
            <div className="flex flex-col items-center space-y-4 py-4">
              <div className="w-16 h-16 rounded-full bg-error-100 flex items-center justify-center">
                <AlertCircle className="h-10 w-10 text-error-600" />
              </div>
              <p className="text-sm text-neutral-600 text-center">
                {error || t('voiceAuth.verify.errors.voiceNotRecognized', { defaultValue: 'Votre voix n\'a pas été reconnue. Veuillez réessayer.' })}
              </p>
              <Button onClick={handleRetry} className="w-full">
                {t('voiceAuth.verify.retry', { defaultValue: 'Réessayer' })}
              </Button>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Affichage des erreurs d'enregistrement */}
      {(error || recordingError) && step !== 'failed' && (
        <div className="mt-4 p-3 rounded-lg bg-error-50 border border-error-200 flex items-start gap-2">
          <AlertCircle className="h-5 w-5 text-error-500 flex-shrink-0 mt-0.5" />
          <p className="text-sm text-error-700">
            {error || recordingError?.message || t('voiceAuth.verify.errors.recordingFailed', { defaultValue: 'Erreur lors de l\'enregistrement' })}
          </p>
        </div>
      )}

      {/* Liens */}
      <div className="mt-6 flex gap-4">
        <Button
          variant="ghost"
          onClick={() => navigate('/welcome')}
        >
          ← {t('buttons.back', { defaultValue: 'Retour' })}
        </Button>
        {step !== 'success' && (
          <Button
            variant="ghost"
            onClick={() => navigate('/voice-enroll')}
          >
            {t('welcome.startVoiceSignup', { defaultValue: 'Nouvelle inscription' })}
          </Button>
        )}
      </div>
    </div>
  );
}

export default VoiceVerify;

