// @generated by Cursor AI (Claude) — verified by [developer name]
/**
 * Page d'enrôlement vocal
 * 
 * Route : /voice-enroll
 * 
 * Processus :
 * 1. L'utilisateur enregistre sa voix (dit son nom et prénom)
 * 2. L'audio est envoyé au backend pour transcription
 * 3. Le nom transcrit est affiché pour confirmation/correction
 * 4. Après confirmation, l'utilisateur est créé et redirigé vers vérification
 */

import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Mic, MicOff, Loader2, AlertCircle, CheckCircle, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import Logo from '@/components/shared/Logo';
import { useAudioRecording } from '@/hooks/useAudioRecording';
import { voiceAuthApi } from '@/api/voiceAuthApi';

function VoiceEnroll() {
  const { t } = useTranslation('common');
  const navigate = useNavigate();

  // États du processus
  const [step, setStep] = useState('record'); // 'record' | 'processing' | 'confirm' | 'saving'
  const [error, setError] = useState(null);

  // Données d'enrôlement (reçues du backend)
  const [enrollmentData, setEnrollmentData] = useState(null);

  // Formulaire de correction du nom
  const [editedName, setEditedName] = useState('');
  const [editedPrenom, setEditedPrenom] = useState('');

  // Hook d'enregistrement audio
  const {
    isSupported,
    isRecording,
    duration,
    maxDuration,
    audioBlob,
    error: recordingError,
    startRecording,
    stopRecording,
    resetRecording,
  } = useAudioRecording({ maxDuration: 10 }); // 10 secondes max pour dire son nom

  // Vérifier si l'API vocale est disponible
  useEffect(() => {
    const checkApi = async () => {
      const isAvailable = await voiceAuthApi.checkVoiceApiHealth();
      if (!isAvailable) {
        setError('Le service d\'authentification vocale n\'est pas disponible. Veuillez réessayer plus tard.');
      }
    };
    checkApi();
  }, []);

  // Traiter l'audio quand l'enregistrement est terminé
  useEffect(() => {
    if (audioBlob && step === 'record' && !isRecording) {
      handleProcessAudio();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [audioBlob, step, isRecording]);

  /**
   * Envoie l'audio au backend pour traitement
   */
  const handleProcessAudio = async () => {
    if (!audioBlob) return;

    setStep('processing');
    setError(null);

    try {
      const result = await voiceAuthApi.enrollVoice(audioBlob);

      if (result.success) {
        setEnrollmentData(result);
        setEditedPrenom(result.prenom || '');
        setEditedName(result.name || '');
        setStep('confirm');
        
        // Si transcription réussie, afficher succès, sinon juste passer à la confirmation
        if (result.transcribed_text && result.transcribed_text.trim()) {
          toast.success(t('voiceAuth.enroll.success', { defaultValue: 'Voix analysée avec succès !' }));
        } else {
          toast.info(t('voiceAuth.enroll.errors.transcriptionFailed', { defaultValue: 'Veuillez saisir votre nom et prénom manuellement.' }));
        }
      } else {
        setError(result.error || result.message || t('voiceAuth.enroll.errors.enrollmentFailed', { defaultValue: 'Erreur lors de l\'analyse de la voix' }));
        setStep('record');
        resetRecording();
      }
    } catch (err) {
      console.error('Erreur traitement audio:', err);
      const errorMessage = err.message || t('voiceAuth.enroll.errors.enrollmentFailed', { defaultValue: 'Une erreur est survenue. Veuillez réessayer.' });
      setError(errorMessage);
      setStep('record');
      resetRecording();
    }
  };

  /**
   * Confirme l'enrôlement avec le nom corrigé
   */
  const handleConfirmEnrollment = async () => {
    if (!enrollmentData || !editedPrenom.trim()) {
      setError(t('voiceAuth.enroll.errors.nameExtractionFailed', { defaultValue: 'Veuillez saisir au moins votre prénom' }));
      return;
    }

    setStep('saving');
    setError(null);

    try {
      const result = await voiceAuthApi.confirmEnrollment({
        temp_user_id: enrollmentData.temp_user_id,
        name: editedName.trim(),
        prenom: editedPrenom.trim(),
        voice_embedding: enrollmentData.voice_embedding,
      });

      if (result.success) {
        // Stocker l'utilisateur vocal dans localStorage
        const voiceUser = {
          id: result.user_id,
          name: result.name,
          prenom: result.prenom,
          authenticated: false, // Pas encore vérifié
          enrolledAt: new Date().toISOString(),
        };
        localStorage.setItem('voiceUser', JSON.stringify(voiceUser));

        toast.success(`Bienvenue ${result.prenom} ! Veuillez confirmer votre voix.`);
        
        // Rediriger vers la page de vérification
        navigate('/voice-verify', { replace: true });
      } else {
        setError(result.error || 'Erreur lors de la création du compte');
        setStep('confirm');
      }
    } catch (err) {
      console.error('Erreur confirmation:', err);
      setError('Une erreur est survenue. Veuillez réessayer.');
      setStep('confirm');
    }
  };

  /**
   * Recommencer l'enregistrement
   */
  const handleRetry = () => {
    setStep('record');
    setEnrollmentData(null);
    setEditedName('');
    setEditedPrenom('');
    setError(null);
    resetRecording();
  };

  /**
   * Formater la durée en mm:ss
   */
  const formatDuration = (seconds) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  // Afficher erreur de support navigateur
  if (!isSupported) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-primary-50 via-white to-neutral-50 px-4">
        <Card className="w-full max-w-md">
          <CardContent className="pt-6 text-center">
            <AlertCircle className="h-12 w-12 text-error-500 mx-auto mb-4" />
            <h2 className="text-lg font-semibold text-neutral-900 mb-2">
              Navigateur non supporté
            </h2>
            <p className="text-sm text-neutral-600">
              Votre navigateur ne supporte pas l'enregistrement audio. 
              Veuillez utiliser Chrome, Firefox ou Safari.
            </p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gradient-to-br from-primary-50 via-white to-neutral-50 px-4 py-8">
      {/* Logo */}
      <div className="mb-6 text-center">
        <div className="flex justify-center mb-4">
          <Logo size="lg" withLink={false} />
        </div>
        <h1 className="text-xl font-bold text-neutral-900">
          {t('voiceAuth.enroll.title', { defaultValue: 'Inscription vocale' })}
        </h1>
      </div>

      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle className="text-lg text-center">
            {step === 'record' && t('voiceAuth.enroll.instruction', { defaultValue: 'Enregistrez votre voix' })}
            {step === 'processing' && t('voiceAuth.enroll.processing', { defaultValue: 'Analyse en cours...' })}
            {step === 'confirm' && t('voiceAuth.enroll.confirm', { defaultValue: 'Confirmez votre nom' })}
            {step === 'saving' && t('voiceAuth.enroll.saving', { defaultValue: 'Création du compte...' })}
          </CardTitle>
          <CardDescription className="text-center">
            {step === 'record' && t('voiceAuth.enroll.instruction', { defaultValue: 'Dites clairement votre prénom et nom' })}
            {step === 'processing' && t('voiceAuth.enroll.processing', { defaultValue: 'Veuillez patienter' })}
            {step === 'confirm' && t('voiceAuth.enroll.confirm', { defaultValue: 'Vérifiez et corrigez si nécessaire' })}
            {step === 'saving' && t('voiceAuth.enroll.saving', { defaultValue: 'Veuillez patienter' })}
          </CardDescription>
        </CardHeader>

        <CardContent className="space-y-6">
          {/* Erreur globale */}
          {(error || recordingError) && (
            <div className="p-3 rounded-lg bg-error-50 border border-error-200 flex items-start gap-2">
              <AlertCircle className="h-5 w-5 text-error-500 flex-shrink-0 mt-0.5" />
              <p className="text-sm text-error-700">
                {error || recordingError?.message || t('voiceAuth.enroll.errors.recordingFailed', { defaultValue: 'Erreur lors de l\'enregistrement' })}
              </p>
            </div>
          )}

          {/* Étape 1 : Enregistrement */}
          {step === 'record' && (
            <div className="flex flex-col items-center space-y-6">
              {/* Indicateur de durée */}
              <div className="text-center">
                <p className="text-3xl font-mono font-bold text-neutral-900">
                  {formatDuration(duration)}
                </p>
                <p className="text-xs text-neutral-500">
                  max {formatDuration(maxDuration)}
                </p>
              </div>

              {/* Bouton d'enregistrement */}
              <button
                onClick={async () => {
                  if (isRecording) {
                    stopRecording();
                  } else {
                    const result = await startRecording();
                    if (!result.success && result.error) {
                      setError(t('voiceAuth.enroll.errors.microphoneDenied', { defaultValue: 'Impossible de démarrer l\'enregistrement. Vérifiez les permissions du micro.' }));
                    }
                  }
                }}
                disabled={recordingError && !isRecording}
                className={`
                  w-24 h-24 rounded-full flex items-center justify-center
                  transition-all duration-300 shadow-lg
                  ${isRecording 
                    ? 'bg-error-500 hover:bg-error-600 animate-pulse' 
                    : 'bg-primary-600 hover:bg-primary-700'
                  }
                  ${recordingError && !isRecording ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}
                `}
              >
                {isRecording ? (
                  <MicOff className="h-10 w-10 text-white" />
                ) : (
                  <Mic className="h-10 w-10 text-white" />
                )}
              </button>

              <p className="text-sm text-neutral-600 text-center">
                {isRecording 
                  ? t('voiceAuth.enroll.instruction', { defaultValue: 'Dites votre prénom et nom, puis appuyez pour arrêter' })
                  : t('voiceAuth.enroll.instruction', { defaultValue: 'Appuyez pour commencer l\'enregistrement' })
                }
              </p>

              {/* Instructions */}
              <div className="bg-neutral-50 p-4 rounded-lg w-full">
                <p className="text-sm text-neutral-700 font-medium mb-2">
                  💡 {t('voiceAuth.enroll.example', { defaultValue: 'Exemple' })} :
                </p>
                <p className="text-sm text-neutral-600 italic">
                  "{t('voiceAuth.enroll.example', { defaultValue: 'Je m\'appelle Ousmane Diouf' })}"
                </p>
              </div>
            </div>
          )}

          {/* Étape 2 : Traitement */}
          {step === 'processing' && (
            <div className="flex flex-col items-center space-y-4 py-8">
              <Loader2 className="h-12 w-12 text-primary-600 animate-spin" />
              <p className="text-sm text-neutral-600">
                {t('voiceAuth.enroll.processing', { defaultValue: 'Analyse de votre voix...' })}
              </p>
            </div>
          )}

          {/* Étape 3 : Confirmation du nom */}
          {step === 'confirm' && enrollmentData && (
            <div className="space-y-4">
              {/* Texte transcrit (si disponible) */}
              {enrollmentData.transcribed_text && enrollmentData.transcribed_text.trim() && (
                <div className="bg-neutral-50 p-3 rounded-lg">
                  <p className="text-xs text-neutral-500 mb-1">{t('voiceAuth.enroll.transcription', { defaultValue: 'Transcription' })} :</p>
                  <p className="text-sm text-neutral-700 italic">
                    "{enrollmentData.transcribed_text}"
                  </p>
                </div>
              )}
              
              {/* Message si pas de transcription */}
              {(!enrollmentData.transcribed_text || !enrollmentData.transcribed_text.trim()) && (
                <div className="bg-primary-50 p-3 rounded-lg border border-primary-200">
                  <p className="text-sm text-primary-700">
                    {t('voiceAuth.enroll.errors.transcriptionFailed', { defaultValue: 'La transcription automatique n\'a pas fonctionné. Veuillez saisir votre nom et prénom manuellement.' })}
                  </p>
                </div>
              )}

              {/* Formulaire de correction */}
              <div className="space-y-4">
                <div>
                  <Label htmlFor="prenom">{t('voiceAuth.enroll.prenom', { defaultValue: 'Prénom' })} *</Label>
                  <Input
                    id="prenom"
                    value={editedPrenom}
                    onChange={(e) => setEditedPrenom(e.target.value)}
                    placeholder={t('voiceAuth.enroll.prenomPlaceholder', { defaultValue: 'Votre prénom' })}
                    className="mt-1"
                  />
                </div>

                <div>
                  <Label htmlFor="name">{t('voiceAuth.enroll.name', { defaultValue: 'Nom' })}</Label>
                  <Input
                    id="name"
                    value={editedName}
                    onChange={(e) => setEditedName(e.target.value)}
                    placeholder={t('voiceAuth.enroll.namePlaceholder', { defaultValue: 'Votre nom de famille' })}
                    className="mt-1"
                  />
                </div>
              </div>

              {/* Boutons */}
              <div className="flex gap-3 pt-2">
                <Button
                  variant="outline"
                  className="flex-1"
                  onClick={handleRetry}
                >
                  <RefreshCw className="h-4 w-4 mr-2" />
                  {t('voiceAuth.enroll.retry', { defaultValue: 'Recommencer' })}
                </Button>
                <Button
                  className="flex-1"
                  onClick={handleConfirmEnrollment}
                  disabled={!editedPrenom.trim()}
                >
                  <CheckCircle className="h-4 w-4 mr-2" />
                  {t('voiceAuth.enroll.confirmButton', { defaultValue: 'Confirmer' })}
                </Button>
              </div>
            </div>
          )}

          {/* Étape 4 : Sauvegarde */}
          {step === 'saving' && (
            <div className="flex flex-col items-center space-y-4 py-8">
              <Loader2 className="h-12 w-12 text-primary-600 animate-spin" />
              <p className="text-sm text-neutral-600">
                Création de votre compte...
              </p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Lien retour */}
      <div className="mt-6">
        <Button
          variant="ghost"
          onClick={() => navigate('/welcome')}
        >
          ← Retour
        </Button>
      </div>
    </div>
  );
}

export default VoiceEnroll;

