// @generated by Cursor AI (Claude) — verified by Kevin

import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Mic } from 'lucide-react';
import Logo from '@/components/shared/Logo';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';

/**
 * Page d'accueil / Inscription pour les citoyens
 * 
 * Route : /welcome
 * 
 * Contenu :
 * - Logo WattU
 * - Option d'inscription vocale (authentification biométrique)
 * - Option de connexion vocale (pour utilisateurs déjà inscrits)
 * 
 * Design :
 * - Centré, mobile-friendly
 * - Support FR/Wolof
 */
function Welcome() {
  const { t } = useTranslation('common');
  const navigate = useNavigate();

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-black px-4 py-8">
      {/* Logo */}
      <div className="mb-8 text-center">
        <div className="flex justify-center mb-4">
          <Logo size="xl" withLink={false} />
        </div>
        <h1 className="text-2xl font-bold text-white mb-2">
          {t('welcome.title', { defaultValue: 'Bienvenue sur WattU' })}
        </h1>
        <p className="text-sm text-white">
          {t('welcome.subtitle', { defaultValue: 'Créez votre compte pour signaler les problèmes de votre ville' })}
        </p>
      </div>

      {/* Authentification vocale */}
      <Card className="w-full max-w-md shadow-lg">
        <CardContent className="pt-8 pb-8 space-y-6">
          {/* Icône visuelle */}
          <div className="flex justify-center">
            <div className="rounded-full bg-primary-100 p-4">
              <Mic className="w-8 h-8 text-primary-600" />
            </div>
          </div>

          {/* Boutons d'action */}
          <div className="flex flex-col gap-3">
            <Button
              variant="default"
              className="w-full h-12 text-base font-semibold"
              onClick={() => navigate('/voice-enroll')}
            >
              {t('welcome.startVoiceSignup', { defaultValue: "M'enroller" })}
            </Button>
              <Button
                variant="outline"
              className="w-full h-12 text-base"
              onClick={() => navigate('/voice-verify')}
              >
              {t('welcome.voiceLogin', { defaultValue: 'Me connecter' })}
              </Button>
            </div>
        </CardContent>
      </Card>

      {/* Footer */}
      <div className="mt-8 text-center">
        <p className="text-xs text-white">
          © 2025 WattU · {t('welcome.version', { defaultValue: 'v1.0.0' })}
        </p>
      </div>
    </div>
  );
}

export default Welcome;
