// @generated by Cursor AI (Claude) — verified by Kevin

import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import Logo from '@/components/shared/Logo';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';

/**
 * Page d'accueil / Inscription pour les citoyens
 * 
 * Route : /welcome
 * 
 * Contenu :
 * - Logo WattU
 * - Option d'inscription vocale (authentification biométrique)
 * - Option de connexion vocale (pour utilisateurs déjà inscrits)
 * 
 * Design :
 * - Centré, mobile-friendly
 * - Support FR/Wolof
 */
function Welcome() {
  const { t } = useTranslation('common');
  const navigate = useNavigate();

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gradient-to-br from-primary-50 via-white to-neutral-50 px-4 py-8">
      {/* Logo */}
      <div className="mb-8 text-center">
        <div className="flex justify-center mb-4">
          <Logo size="xl" withLink={false} />
        </div>
        <h1 className="text-2xl font-bold text-neutral-900 mb-2">
          {t('welcome.title', { defaultValue: 'Bienvenue sur WattU' })}
        </h1>
        <p className="text-sm text-neutral-600">
          {t('welcome.subtitle', { defaultValue: 'Créez votre compte pour signaler les problèmes de votre ville' })}
        </p>
      </div>

      {/* Authentification vocale */}
      <Card className="w-full max-w-md">
        <CardContent className="pt-6 space-y-6">
          {/* Explication simple */}
          <div className="text-center space-y-3">
            <p className="text-base text-neutral-700 font-medium">
              Authentification par reconnaissance vocale
            </p>
            <p className="text-sm text-neutral-600 leading-relaxed">
              Votre voix est unique. Dites simplement votre nom et prénom pour créer votre compte. 
              Votre voix servira ensuite à vous identifier de manière sécurisée.
            </p>
          </div>

          {/* Boutons d'action */}
          <div className="flex flex-col gap-3">
            <Button
              variant="default"
              className="w-full"
              onClick={() => navigate('/voice-enroll')}
            >
              {t('welcome.startVoiceSignup', { defaultValue: 'Nouvelle inscription' })}
            </Button>
              <Button
                variant="outline"
                className="w-full"
              onClick={() => navigate('/voice-verify')}
              >
              {t('welcome.voiceLogin', { defaultValue: 'Déjà inscrit ? Se connecter' })}
              </Button>
            </div>
        </CardContent>
      </Card>

      {/* Footer */}
      <div className="mt-8 text-center">
        <p className="text-xs text-neutral-500">
          © 2025 WattU · {t('welcome.version', { defaultValue: 'v1.0.0' })}
        </p>
      </div>
    </div>
  );
}

export default Welcome;
