// @generated by Cursor AI (Claude) — verified by Kevin

import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { RefreshCw } from 'lucide-react';
import { useAdminAnalytics } from '@/hooks/useAdminAnalytics';
import TrendsChart from '@/components/admin/TrendsChart';
import TypeDistributionChart from '@/components/agent/TypeDistributionChart';
import StatusDistributionChart from '@/components/agent/StatusDistributionChart';
import PriorityDistributionChart from '@/components/agent/PriorityDistributionChart';
import CommuneDistributionChart from '@/components/admin/CommuneDistributionChart';

/**
 * Page des analytics statistiques pour les admins
 * 
 * Affiche :
 * - Évolution des signalements dans le temps (graphique linéaire)
 * - Répartition par type (camembert)
 * - Répartition par statut (barres)
 * - Répartition par priorité (barres)
 * - Répartition par commune (barres, top 10)
 * - Filtre de période (7j, 30j, 90j, tout)
 * 
 * @example
 * <Route path="/admin/analytics" element={<AdminAnalytics />} />
 */
function AdminAnalytics() {
  const { t } = useTranslation('admin');
  const [periodDays, setPeriodDays] = useState(30);

  const { trends, byType, byStatus, byPriority, byCommune, loading, error, refetch } = useAdminAnalytics(
    periodDays
  );

  /**
   * Gérer le changement de période
   */
  const handlePeriodChange = (value) => {
    const days = value === 'all' ? null : parseInt(value);
    setPeriodDays(days);
  };

  /**
   * Rafraîchir les données
   */
  const handleRefresh = () => {
    refetch();
  };

  return (
    <div className="space-y-6">
      {/* ═══════════════════════════════════════════════════════════
          HEADER
          ═══════════════════════════════════════════════════════════ */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-neutral-900">
            {t('analytics.title', { defaultValue: 'Analytics' })}
          </h1>
          <p className="text-neutral-600 mt-1">
            {t('analytics.subtitle', { defaultValue: 'Analyse statistique globale de la plateforme' })}
          </p>
        </div>

        <div className="flex items-center gap-3">
          {/* Sélecteur de période */}
          <Select value={periodDays?.toString() || 'all'} onValueChange={handlePeriodChange}>
            <SelectTrigger className="w-[140px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="7">{t('analytics.period.7d', { defaultValue: '7 derniers jours' })}</SelectItem>
              <SelectItem value="30">{t('analytics.period.30d', { defaultValue: '30 derniers jours' })}</SelectItem>
              <SelectItem value="90">{t('analytics.period.90d', { defaultValue: '90 derniers jours' })}</SelectItem>
              <SelectItem value="all">{t('analytics.period.all', { defaultValue: 'Tout' })}</SelectItem>
            </SelectContent>
          </Select>

          {/* Bouton rafraîchir */}
          <Button variant="outline" size="icon" onClick={handleRefresh} disabled={loading}>
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
          </Button>
        </div>
      </div>

      {/* ═══════════════════════════════════════════════════════════
          ERREUR
          ═══════════════════════════════════════════════════════════ */}
      {error && (
        <Card className="border-red-200 bg-red-50">
          <CardContent className="p-6">
            <p className="text-red-700">
              {error.message || t('analytics.error', { defaultValue: 'Erreur lors du chargement des analytics' })}
            </p>
          </CardContent>
        </Card>
      )}

      {/* ═══════════════════════════════════════════════════════════
          GRAPHIQUES
          ═══════════════════════════════════════════════════════════ */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Évolution dans le temps (pleine largeur) */}
        <div className="lg:col-span-2">
          <TrendsChart trends={trends} loading={loading} />
        </div>

        {/* Répartition par type */}
        <TypeDistributionChart byType={byType} loading={loading} namespace="admin" />

        {/* Répartition par statut */}
        <StatusDistributionChart byStatus={byStatus} loading={loading} namespace="admin" />

        {/* Répartition par priorité */}
        <PriorityDistributionChart byPriority={byPriority} loading={loading} namespace="admin" />

        {/* Répartition par commune (pleine largeur) */}
        <div className="lg:col-span-2">
          <CommuneDistributionChart byCommune={byCommune} loading={loading} />
        </div>
      </div>
    </div>
  );
}

export default AdminAnalytics;

